### PR TITLE
lint: serika

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
passes linter from https://github.com/helix-editor/helix/pull/3234
image
image

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
@VuiMuich please sanity check my choices :)

**Comment by VuiMuich** [comment]
Will do bus most certainly not before Tuesday. 

Btw: locally I am running with `nasty-red` as `fg` for `diagnostic` as I found `dark-red` is really hard to read, when whole block of code is linted.

If you don't want to add it to this PR, I can fix this later, as I wanted to overhaul the pastel tones slightly more saturated.

**Comment by AlexanderBrevig** [comment]
Updated to `nasty_red`

**Comment by AlexanderBrevig** [comment]
Moved to bulk PR https://github.com/helix-editor/helix/pull/3587

**Pull request closed without merging**
