### PR TITLE
Fix picker won't scroll down when it hits the bottom #1544

### LINKED ISSUE #1544: Picker won't scroll down when it hits the bottom
The Picker doesn't scroll when the cursor hits the bottom.

This bug seems to have been introduced with f5b0821860940782567a0baa17280aef04f845e3

### Reproduction steps

1. Open File Picker in sufficiently large workspace
2. Try to move the cursor past the last entry visible in the list

### Environment

- Platform: Linux
- Terminal emulator: foot
- Helix version: v0.5.0

### PR DESCRIPTION
**Pull request by hahanein**
This fixes #1544

### CODE REVIEW

**Comment by k2d222** [comment]
`a / b * c` vs `a / (b * c)`.
try `let offset = self.cursor / std::cmp::max(1, (rows as usize)) * (rows as usize);`

**Comment by hahanein** [comment]
> try `let offset = self.cursor / std::cmp::max(1, (rows as usize)) * (rows as usize);`

That would alter the result in cases in which `rows <= 1`

I'm assuming that's correct regardless because this state is not useful anyway?

**Comment by k2d222** [comment]
looking back at the code, this would be my favourite solution:
`let offset = self.cursor - (self.cursor % rows as usize);`
Its also a bit clearer what it does in my opinion.

**Comment by hahanein** [comment]
This alters the result in all cases?

**Comment by hahanein** [comment]
Works for me 👍🏻

**Comment by k2d222** [comment]
Not for me haha :) sorry I didn't know the remainder operation also fails with 0. Third time's the charm ;)
`self.cursor - (self.cursor % std::cmp::max(1, rows as usize));`
of `self.cursor / std::cmp::max(1, rows as usize) * (rows as usize)`

**Comment by hahanein** [comment]
I quit (maths) 👍🏻

**Review by pickfire — APPROVED** [review]
Nice, thanks for fixing the issue.

**Comment by pickfire** [comment]
I think the check is stuck or something, I don't see the approve and run button, maybe need to create a new pull request?

**Pull request closed without merging**
