### PR TITLE
Do not accept keydown to enter in autocomplete popup

### PR DESCRIPTION
**Pull request by p1gp1g**
I must open a new PR since I have force-pushed a change for https://github.com/helix-editor/helix/pull/4141 when it was closed and I cannot reopen it.

This is a fix for #2027. If `arrows_to_enter_completion` is set to false, user must use `tab` or `C-n` to enter the autocompletion pop and can use arrows once in the pop up.

<details><summary>Old description</summary>
So, after moving around, this is just a fix for https://github.com/helix-editor/helix/issues/2027 (and related issues) if timeout is set to 0. Maybe it is better to add a new parameter instead of timeout 0 ? For instance `arrows_to_enter_autocompletion_popup` with default to `true` (current behaviour)
</details>

### CODE REVIEW

**Comment by the-mikedavis** [comment]
How do you use the completion menu? Do you ever use arrow keys for it?

I think this change is too specific - it only prevents up/down from interacting once the completion menu has already opened and when the idle-timeout is exactly 0. It would be better to be able to unbind up/down for the completion menu or to prevent the completion menu from opening at all after any navigation in insert mode

**Comment by archseer** [comment]
I think this also demonstrates that `idle-timeout` should never be set to `0` but a very small number.

**Comment by p1gp1g** [comment]
At this moment, I have to set `idle-timeout` to `2000` and regularly tap `<C-x>` to see if there is a completion and I still often ends up tapping `<C-c>` because I've entered in the pop while moving around.

And with this change I see when there are suggestions and I do `<tab>` then arrows.

> I think this also demonstrates that `idle-timeout` should never be set to `0` but a very small number.

It sounds like going in favor of a different behavior if `idle-timeout` is set to `0` to me :)

**Comment by archseer** [comment]
`idle-timeout` is used in other areas than just autocompletion, i.e. https://github.com/helix-editor/helix/commit/a85e3862988933953d1c0e7435969604d3722959

Setting it to `0` isn't recommended since you'll keep re-triggering various behaviors _immediately_ and waste a lot of CPU cycles. Even setting it to something as low as `2` or `5` would be better.

**Comment by p1gp1g** [comment]
Ok, it makes sens. I think the [documentation](https://docs.helix-editor.com/configuration.html) should be updated (it recommends 0 to instant pop ups)

What about another config parameter like `arrows_to_enter_autocompletion` default to `true` ?

**Comment by archseer** [comment]
This just seems like a very specific workaround to me. What about adding support for `C-o` instead? https://github.com/helix-editor/helix/issues/2027#issuecomment-1275809112

I'd also propose removing arrow key support from the completion popup and only using `C-n`/`C-p` as intended but I'm not sure I'm prepared for the [next wave of outrage](https://github.com/helix-editor/helix/pull/3671)

**Comment by p1gp1g** [comment]
I think the issue linked i(#2027) is the same than the one I have : we want to see the pop up and choose when we to use it. So `C-o` doesn't work : i hides the pop up.

Actually I had the same issue on kakoune too and I ended up mapping `tab` and `s-tab` to use the completion and unmapping it as soon as the completion pop up is hidden. I have searched how to do `tab-arrows` without success.

**Comment by p1gp1g** [comment]
0509c34 adds a parameter. I can then set `idle-timeout` to 20 and `arrows_to_enter_completion` to false : I can see the completion suggestions while still being able to move around in insert mode. :)

**Comment by kendfss** [comment]
How about:
- creating `prev_completion` and `next_completion` commands, ideally defaulting to `shift+tab` and `tab`, and allowing for the completions window to be cancelled by line-changes?
- or changing the behaviour of `esc` so that it closes the first overlying sub-display, or [returns to] normal mode if no overlying display is present. Could also help with #5549 
Either of the above would allow for navigation to be decoupled from insertion without compromising the user's ability to [get the most out of the modal editing paradigm](https://github.com/helix-editor/helix/issues/1381#issuecomment-1001187403).

**Comment by p1gp1g** [comment]
Closing in favor of #5803

**Pull request closed without merging**
