### PR TITLE
Add movement shortcut for history

### PR DESCRIPTION
**Pull request by pickfire**
alt-u and alt-U

### CODE REVIEW

**Comment by pickfire** [comment]
cc @Omnikar since he worked on https://github.com/helix-editor/helix/pull/981

**Comment by pickfire** [comment]
I wonder would if be useful if we mentioned to the user how many steps were done?

**Comment by Omnikar** [comment]
I haven't looked at the code but… I'm confused; what's the difference between `earlier`/`later` and `undo`/`redo`?

**Comment by pickfire** [comment]
insert `a`

    a

insert `a`

    aa

insert `a`

    aaa

undo <kbd>u</kbd>

    aa

insert `b`

    aab

move backward in history <kbd>alt</kbd><kbd>u</kbd>

    aaa

move forward in history <kbd>alt</kbd><kbd>U</kbd>

    aab

Basically if you messed up after you undo, you can still go back. Like undo tree but think it is two dimension, the normal undo is one branch of the undo tree, but this traverse by time of the undo tree rather than by branch.

**Comment by Omnikar** [comment]
Ah, that's quite useful.

**Review by archseer — APPROVED** [review]

**Pull request merged**
