### PR TITLE
highlight(sql): Update tree-sitter-sql to `98a7fc9`

### PR DESCRIPTION
**Pull request by LeoniePhiline**
# Changes:

Updates `tree-sitter-sql` [from `3a3f92b29c880488a08bc2baaf1aca6432ec3380` to  `c5b1548ec95956c8da6393dceacf30aa349a6e9f`](https://github.com/DerekStride/tree-sitter-sql/compare/3a3f92b29c880488a08bc2baaf1aca6432ec3380...c5b1548ec95956c8da6393dceacf30aa349a6e9f#commits_bucket).

[Full `grammar.js`](https://github.com/DerekStride/tree-sitter-sql/blob/c5b1548ec95956c8da6393dceacf30aa349a6e9f/grammar.js).

Note that to avoid further diff noise, the tree sitter JSON and C sources were moved onto the [`gh-pages`  branch](https://github.com/DerekStride/tree-sitter-sql/commits/gh-pages).

This is why `languages.toml` references https://github.com/DerekStride/tree-sitter-sql/commit/7cbac0472e5b8f8486ce64ffbcf1982d5cd5fc8d on the `gh-pages` branch, which contains the sources for https://github.com/DerekStride/tree-sitter-sql/commit/98a7fc965e455c38e508c1424671685dd6c610ab on the `main` branch ([the latest grammar change on `main`](https://github.com/DerekStride/tree-sitter-sql/compare/98a7fc965e455c38e508c1424671685dd6c610ab...c5b1548ec95956c8da6393dceacf30aa349a6e9f)).

## Merged PRs:

- https://github.com/DerekStride/tree-sitter-sql/pull/105
- https://github.com/DerekStride/tree-sitter-sql/pull/109
- https://github.com/DerekStride/tree-sitter-sql/pull/112
- https://github.com/DerekStride/tree-sitter-sql/pull/110
- https://github.com/DerekStride/tree-sitter-sql/pull/113
- https://github.com/DerekStride/tree-sitter-sql/pull/114
- https://github.com/DerekStride/tree-sitter-sql/pull/118
- https://github.com/DerekStride/tree-sitter-sql/pull/116
- https://github.com/DerekStride/tree-sitter-sql/pull/100
- https://github.com/DerekStride/tree-sitter-sql/pull/119
- https://github.com/DerekStride/tree-sitter-sql/pull/117
- https://github.com/DerekStride/tree-sitter-sql/pull/121
- https://github.com/DerekStride/tree-sitter-sql/pull/123
- https://github.com/DerekStride/tree-sitter-sql/pull/125
- https://github.com/DerekStride/tree-sitter-sql/pull/124
- https://github.com/DerekStride/tree-sitter-sql/pull/126
- https://github.com/DerekStride/tree-sitter-sql/pull/127
- https://github.com/DerekStride/tree-sitter-sql/pull/130
- https://github.com/DerekStride/tree-sitter-sql/pull/131
- https://github.com/DerekStride/tree-sitter-sql/pull/132
- https://github.com/DerekStride/tree-sitter-sql/pull/134
- https://github.com/DerekStride/tree-sitter-sql/pull/136
- https://github.com/DerekStride/tree-sitter-sql/pull/138
- https://github.com/DerekStride/tree-sitter-sql/pull/139
- https://github.com/DerekStride/tree-sitter-sql/pull/141
- https://github.com/DerekStride/tree-sitter-sql/pull/143
- https://github.com/DerekStride/tree-sitter-sql/pull/146
- https://github.com/DerekStride/tree-sitter-sql/pull/148
- https://github.com/DerekStride/tree-sitter-sql/pull/152
- https://github.com/DerekStride/tree-sitter-sql/pull/153
- https://github.com/DerekStride/tree-sitter-sql/pull/156
- https://github.com/DerekStride/tree-sitter-sql/pull/157

# (Solved) Issue with `keyword_language`

During review you might notice that `(keyword_language)` is commented out in [line 210](https://github.com/helix-editor/helix/compare/master...LeoniePhiline:helix:master?expand=1#diff-0e56156c3c29f2784cb489d716f1779ece60bfe4c44691dbe8e6d398589c10b9R210).

It seems to me like this query _should_ work, but as long as this keyword query is enabled, helix fails parsing with:

```
helix_core::syntax [ERROR] Could not parse queries for language "sql". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 209, column: 3, offset: 3657, message: "keyword_language", kind: NodeType }
```

This seems to be a [`TSQueryError` from tree-sitter's C `ts_query_new`](https://tree-sitter.github.io/tree-sitter/using-parsers#the-query-api).

[The symbol](https://github.com/DerekStride/tree-sitter-sql/blob/92018a36833c284c3f5d923de7ec253f35c6e610/grammar.js#L201) [is defined](https://github.com/DerekStride/tree-sitter-sql/blob/gh-pages/src/grammar.json#L666-L669) in `grammar.json`.

But it is not defined in [`node-types.json`](https://github.com/DerekStride/tree-sitter-sql/blob/gh-pages/src/node-types.json).

In [`parser.c`](https://raw.githubusercontent.com/DerekStride/tree-sitter-sql/gh-pages/src/parser.c), it is defined as `aux_sym_keyword_language_token1`. 🤔 (see also [the codegen](https://github.com/tree-sitter/tree-sitter/blob/d0029a15273e526925a764033e9b7f18f96a7ce5/cli/src/generate/render.rs#L1482))

`(keyword_language)` [appears to be unused](https://github.com/DerekStride/tree-sitter-sql/blob/92018a36833c284c3f5d923de7ec253f35c6e610/grammar.js#L946) and thus declassified by the tree-sitter codegen to an auxiliary symbol.

Disabling `(keyword_language)` in the queries list is a viable workaround. I'd completely remove it if it is removed [upstream](https://github.com/DerekStride/tree-sitter-sql/issues/155).

### CODE REVIEW

**Review by the-mikedavis — DISMISSED** [review]
Thanks!

**Comment by the-mikedavis** [comment]
Yeah as you noted in the issue it looks like that node is unused. When the tree-sitter C library checks the queries ("query analysis") it will reject patterns that can't possibly match. When it says that for named nodes that exist in the `grammar.js` it either means that the named node is unused like in this case or that it's used but always aliased to something else. So if a node can't appear in the syntax tree we'll see that error.

**Comment by LeoniePhiline** [comment]
I'll add one more patch, since https://github.com/DerekStride/tree-sitter-sql/issues/154 got fixed.

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]
Thanks!

**Pull request merged**
