### PR TITLE
Update gix to version 0.62

### PR DESCRIPTION
**Pull request by blinxen**
This update contains a security fix for
https://rustsec.org/advisories/RUSTSEC-2024-0335.html

### CODE REVIEW

**Comment by pascalkuthe** [comment]
It's fine to update but not really relevant to us since we don't use that gitoxide functionality. In fact the relevant features are disabled we don't even have the affected gix-transport in our dependency tree

**Comment by blinxen** [comment]
That is true, however this change is motivated by the `gitoxide` update in Fedora. Because the project (`gitoxide`) consists of around 70 crates, we can't support multiple versions of it. That is why I would like to update all Fedora packages that require `gitoxide` to use the new version. This makes the life of package maintainers easier :D.

**Comment by blinxen** [comment]
I would appreciate it if this could get merged however it doesn't really have a big priority right now.

**Review by pascalkuthe — APPROVED** [review]
We would have updated this automatically with dependabot (https://github.com/helix-editor/helix/pull/10453)

Just confused why this helps fedora since I would assume fedora would package the last release and not our master branch and just apply a patch to that.

**Review by the-mikedavis — APPROVED** [review]

**Comment by blinxen** [comment]
> We would have updated this automatically with dependabot (https://github.com/helix-editor/helix/pull/10453) so merging this is fine

Ah, I missed that PR

> Just confused why this helps fedora since I would assume fedora would package the last release and not our master branch and just apply a patch to that.

I created this PR to make sure it landed in the next release which according to the milestones should be soon.

**Pull request merged**
