### PR TITLE
Add ansible-language-server for yaml

### PR DESCRIPTION
**Pull request by lwandrebeck**
Add ansible support to yaml.
If this PR is accepted, I’ll update wiki accordingly.

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
You can fix the CI by running `cargo xtask docgen` and commiting the changes

**Review by the-mikedavis — APPROVED** [review]

**Comment by x70b1** [comment]
@the-mikedavis how can we get a 2nd approval here? It seems like this is the only thing thats missing here.

**Review by pascalkuthe — APPROVED** [review]

**Comment by RachaelMDavies** [comment]
Ansible language server does not appear to work, can someone confirm it does for them? Helix just says "language server exited".  I am using the latest Helix master with this commit and also have yaml language server installed.

```
2023-10-10T12:55:36.289 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2023-10-10T12:55:36.342 helix_term::application [ERROR] Language Server: Method window/showMessageRequest not found in request 3
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "/usr/local/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:565\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "                                               ^\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "ResponseError: Method not found: window/showMessageRequest\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "    at handleResponse (/usr/local/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "    at handleMessage (/usr/local/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "    at processMessageQueue (/usr/local/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "    at Immediate.<anonymous> (/usr/local/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "    at process.processImmediate (node:internal/timers:471:21) {\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "  code: -32601,\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "  data: undefined\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "}\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "\n"
2023-10-10T12:55:36.346 helix_lsp::transport [ERROR] ansible-language-server err <- "Node.js v18.13.0\n"
2023-10-10T12:55:36.354 helix_lsp::transport [ERROR] ansible-language-server err: <- StreamClosed
2023-10-10T12:55:36.621 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
```
```
$ ansible-language-server --version
1.2.1
```

**Comment by pascalkuthe** [comment]
This is a bug in the a able language server (as the logs say). Maybe it works with newer versions

**Comment by RachaelMDavies** [comment]
@pascalkuthe I am using the latest version. @lwandrebeck It works for you? If so, which version?

It should not be a default if it does not work!

**Comment by RachaelMDavies** [comment]
@lwandrebeck Would you be able to build the latest Helix from Master and try again? I am thinking it is most likely that something has changed in Helix, namely the `registerCapability request` feature.

I am running Debian 12, the only real difference between Debian and Rocky for this case might be the version of NodeJS used.

**Comment by lwandrebeck** [comment]
A quick update. I’ve written most of the past day yaml files, and ansible completion worked flawlessly. I did not encounter the error above anymore, even with WIP files. There’s something fishy somewhere…

**Comment by David-Else** [comment]
I have filed [an issue](https://github.com/ansible/ansible-language-server/issues/602) based on what @the-mikedavis reported above. If I made a mistake please can someone let me know and I will edit it.

@lwandrebeck Please keep looking for the fishy behaviour, I am sure we can get this sorted :)

**Comment by lwandrebeck** [comment]
I’ve done here and there some more ansible without problems. So I’m afraid I can’t help much on that point. Something new on your side ?

**Pull request merged**
