### PR TITLE
Update tree-sitter-sql and improve highlight queries

### LINKED ISSUE #5071: `illegal hardware instruction` when opening SQL file
### Summary

I tried to open a 13MB file and helix crashed

file: https://gist.github.com/tkellogg/bbf57f5c43489a1e122b4f1a8d0daa9b

to create the file, I did a `docker exec ... >tmp.sql`. Not sure if that creates unexpected characters. 

Helix was installed and then (today) updated via homebrew.

```
➜  ~ brew info helix
==> helix: stable 22.12 (bottled), HEAD
Post-modern modal text editor
https://helix-editor.com
/usr/local/Cellar/helix/22.12 (801 files, 121MB) *
  Poured from bottle on 2022-12-08 at 12:09:17
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/helix.rb
License: MPL-2.0
==> Dependencies
Build: rust ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 4,562 (30 days), 14,306 (90 days), 18,920 (365 days)
install-on-request: 4,578 (30 days), 14,324 (90 days), 18,937 (365 days)
build-error: 1 (30 days)
```

### Reproduction Steps

 

I tried this:

1. `hx tmp.sql`

Here's a link to the file: https://gist.github.com/tkellogg/bbf57f5c43489a1e122b4f1a8d0daa9b

I expected this to happen:
The file opens

Instead, this happened:
Helix hangs for ~60 seconds and then crashes with an error: 

```
[1]    98496 illegal hardware instruction  hx tmp.sql
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

Nothing seems relevant here

```
2022-11-07T11:12:13.459 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-07T11:12:53.358 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-07T17:00:47.548 helix_view::editor [ERROR] Failed to initialize the LSP for `source.bash` { cannot find binary path }
2022-11-10T15:39:11.363 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2022-11-10T15:43:06.944 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2022-11-10T15:47:09.482 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-22T09:03:45.806 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-22T09:04:14.649 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-22T10:44:36.778 helix_view::editor [ERROR] Failed to initialize the LSP for `text.html.basic` { cannot find binary path }
2022-11-22T10:49:06.976 helix_view::editor [ERROR] Failed to initialize the LSP for `source.css` { cannot find binary path }
2022-11-22T10:50:58.988 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-22T11:07:56.772 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-22T11:08:46.096 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-22T11:11:18.749 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-11-29T09:35:59.811 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }
2022-11-29T09:45:20.084 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }
2022-11-29T09:50:52.831 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }
2022-11-29T09:51:43.498 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }

```

</details>

### Platform

macOS 13.0.1

### Terminal Emulator

iTerm2 3.4.18

### Helix Version

helix 22.12 (96ff64a8)

### LINKED ISSUE #5186: SQL highlighting fails for `INSERT ... SET`, `INSERT ... VALUES` with multiple records, and `GROUP_CONCAT` with `SEPARATOR`
### Summary

**_Example SQL:_**

`INSERT INTO ... SET ...` syntax:

```sql
INSERT INTO some_table
  field = "String does not get highlight in INSERT SET syntax";
```

helix 22.12: String value does not get highlight:

image

`INSERT INTO ... (...) VALUES (...)` syntax with multiple values records:

```sql
INSERT INTO some_table
  (field)
VALUES
  ("String value"),
  ("String value");
```

helix 22.12: Values of second record do not get highlight:

image

`GROUP_CONCAT` with `SEPARATOR`:

```sql
SELECT GROUP_CONCAT(uid SEPARATOR ",") 
FROM some_table 
GROUP BY some_field;

SELECT GROUP_CONCAT(uid SEPARATOR ",") 
FROM some_table 
GROUP BY some_field;
```

helix 22.12: Separator string appears to not be expected (only `","` should be yellow):

image

Theme for all screenshots: `monokai_pro_spectrum`

### Reproduction Steps

 

**I tried this:**

Typed the above SQL queries (MySQL dialect) into helix.

Alternatively, copy-paste and use `:set-language sql` or write to an `*.sql` file.

**I expected this to happen:**

Proper highlighting (see GitHub highlight above).

**Instead, this happened:**

Erratic highlighting (see helix screenshots above).

### Helix log

(nothing relevant in the helix log)

### Platform

openSUSE Tumbleweed

### Terminal Emulator

konsole

### Helix Version

22.12

### LINKED ISSUE #5708: SQL `@constant.numeric` does not seem to work
### Summary

Numeric constants in SQL are highlighted in the `string` color, rather than the `constant.numeric` color:

**Extract from `monokai_pro_spectrum`:** (But the same happens with all other themes)
```ini
# strings
"string" = "yellow"

# integer, floating point
"constant.numeric" = "purple"
```

image `5` should be purple.

**`runtime/sql/highlights.scm` does attempt to match numbers, but that seems to fail:**
```lisp
(literal) @string

((literal) @constant.numeric
  (#match? @constant.numeric "^(-?\d*\.?\d*)$"))
```

### Reproduction Steps

 

**I tried this:**

1. `hx`
2. `:lang sql`
3. `:theme monokai_pro_spectrum` (But the same happens with all other themes).
4. Paste the following into the buffer:

```sql
SELECT * FROM foobar
WHERE !bang AND foo != "bar" OR pie = 5;
```

**I expected this to happen:**

Numeric literal `5` has a different color than string literal `"bar"`.

**Instead, this happened:**

Numeric literal `5` has the same color as string literal `"bar"`.

### Platform

openSUSE Tumbleweed - Linux

### Terminal Emulator

Konsole

### Helix Version

helix master, `runtime/sql/highlights.scm` from https://github.com/helix-editor/helix/pull/5683

### PR DESCRIPTION
**Pull request by LeoniePhiline**
Fixes #5186 
Fixes #5071
Fixes #5708

See also:

- Upstream bug https://github.com/DerekStride/tree-sitter-sql/issues/67
- Upstream fix https://github.com/DerekStride/tree-sitter-sql/pull/68
- Upstream instruction for `highlights.scm` https://github.com/DerekStride/tree-sitter-sql/issues/67#issuecomment-1400498613

### CODE REVIEW

**Comment by pascalkuthe** [comment]
Does this also fix  #5071? I would guess so since it was solved just by updating the SQL parser when that issue was first opened

**Comment by LeoniePhiline** [comment]
I tested the SQL dump linked at https://github.com/helix-editor/helix/issues/5071 (https://gist.github.com/tkellogg/bbf57f5c43489a1e122b4f1a8d0daa9b), which 
- opened fine (taking a long second), 
- was highlighted more or less correctly, 
- and I was able to scroll through it from top to bottom. (40851 lines)

The reporter of #5071 was on MacOS, while I am using Linux, with currently no access to a MacOS device to test on. 

Since you were able to reproduce the issue on Linux on 9 December, **I believe we can assume the crash issue might be fixed**.

Note that **typing is still unbearably slow** in this 13 MB file. (No matter if inserting at the top or bottom of the file.)

**Comment by pascalkuthe** [comment]
> I tested the SQL dump linked at #5071 ([gist.github.com/tkellogg/bbf57f5c43489a1e122b4f1a8d0daa9b](https://gist.github.com/tkellogg/bbf57f5c43489a1e122b4f1a8d0daa9b)), which
> 
>     * opened fine (taking a long second),
> 
>     * was highlighted more or less correctly,
> 
>     * and I was able to scroll through it from top to bottom. (40851 lines)
> 
> 
> The reporter of #5071 was on MacOS, while I am using Linux, with currently no access to a MacOS device to test on.
> 
> Since you were able to reproduce the issue on Linux on 9 December, **I believe we can assume the crash issue might be fixed**.
> 
> Note that **typing is still unbearably slow** in this 13 MB file. (No matter if inserting at the top or bottom of the file.)

Thanks for testing that! I think we can close that issue then once this PR is merged.

The performance can likely only be improved by speeding up the grammar although around those file-sizes TS sadly starts to hit its limit. We have enough open issues about that already and the specific crash seems to be solved

**Comment by LeoniePhiline** [comment]
I added "Fixes https://github.com/helix-editor/helix/issues/5071" to the PR.

**Review by the-mikedavis — COMMENTED** [review]
It would be nice to also add the new `bang` rule as an operator [DerekStride/tree-sitter-sql@`2743c7b5e710e6854d4e8c14c302548b436e2a1f...4fe05b2d81565ddb689d2f415e07afdacc515c52`#diff-919ac210ac](https://github.com/DerekStride/tree-sitter-sql/compare/2743c7b5e710e6854d4e8c14c302548b436e2a1f...4fe05b2d81565ddb689d2f415e07afdacc515c52#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR1438)

**Comment by LeoniePhiline** [comment]
What do you mean? The PR already updates to the latest commit.

**Comment by the-mikedavis** [comment]
Oh yeah that diff is not expanding properly. I meant this line https://github.com/DerekStride/tree-sitter-sql/blob/4fe05b2d81565ddb689d2f415e07afdacc515c52/grammar.js#L1438

It could be added to the big `[ ... ] @operator` list or for future-proofing we could mark all binary and unary operators as `@operator`:

```scm
(binary_expression
  operator: _ @operator)

(unary_expression
  operator: _ @operator)
```

**Comment by LeoniePhiline** [comment]
I've added `"!"` to the end of the `@operator` list. However, I am unfamiliar with the tree-sitter query syntax and was unsure how to implement your second request:

Is this something I can just copy-paste to the end of the `highlights.scm` file? (As far as I can see, such blocks do not exist yet.) 
Or should I replace the  `_` by each of the operator in the current `@operator` list?

**Comment by the-mikedavis** [comment]
I mean that you could replace the block here: https://github.com/helix-editor/helix/blob/4a59d337f4a2dae04c0726c70dc65463c561639d/runtime/queries/sql/highlights.scm#L45-L59

with:

```scm
(binary_expression
  operator: _ @operator)

(unary_expression
  operator: _ @operator)
```

as-is: `_` is a wildcard so it captures whatever node is there. `operator` is a field for both binary_expression and unary_expression ([here](https://github.com/DerekStride/tree-sitter-sql/blob/4fe05b2d81565ddb689d2f415e07afdacc515c52/grammar.js#L1386) and [here](https://github.com/DerekStride/tree-sitter-sql/blob/4fe05b2d81565ddb689d2f415e07afdacc515c52/grammar.js#L1408)).

Fields make it easy to capture some specific node in a pattern and can capture arbitrary things. For example you could use the `right` field from binary_expression to capture just the right-hand-side:

```
(binary_expression right: _ @something)
```

So they're nice for a case like this where we want to tag everything that could show up in that `operator` field as `@operator`.

**Comment by LeoniePhiline** [comment]
Thanks!

The difference here is that `*` is no longer highlighted (right-most column):

Original|Explicit operators|_Extracted operators_
---|---|---
image|image|image

**Comment by the-mikedavis** [comment]
Yeah, the original SQL queries were most likely written for nvim-treesitter which has the reverse precedence: in nvim-treesitter, later queries override earlier ones and in helix earlier queries override later queries. So swapping those two clauses should fix those highlights.

**Comment by the-mikedavis** [comment]
That `@special` highlight looks good for the all_fields node: that `*` is different from the `*` arithmetic operator so it will be nice to be able to distinguish between them 👍

**Comment by the-mikedavis** [comment]
You can check the `grammar.js` for the full list of node definitions. You can also use `:tree-sitter-subtree` within helix to see the nodes pretty-printed in a popup which can be useful for writing queries.

**Comment by LeoniePhiline** [comment]
> That @special highlight looks good for the all_fields node: that * is different from the * arithmetic operator so it will be nice to be able to distinguish between them +1

I added that to the PR in https://github.com/helix-editor/helix/pull/5683/commits/332ad7f67645a30020939bfd2635851bb0bb58cf 

> You can check the grammar.js for the full list of node definitions. You can also use :tree-sitter-subtree within helix to see the nodes pretty-printed in a popup which can be useful for writing queries.

Thank you, that was SO helpful! Together with the scopes at https://docs.helix-editor.com/themes.html#scopes and `:tree-sitter-scopes` I have all I need. 

> Also what about https://github.com/helix-editor/helix/issues/5708, I'm not sure how helix loads tree-sitter grammars (line by line or in some other way), but I just swapped [these lines](https://github.com/helix-editor/helix/blob/4a59d337f4a2dae04c0726c70dc65463c561639d/runtime/queries/sql/highlights.scm#L67-L70) and it seems the numbers are highlighted correctly now
> Yeah, the original SQL queries were most likely written for nvim-treesitter which has the reverse precedence: in nvim-treesitter, later queries override earlier ones and in helix earlier queries override later queries. So swapping those two clauses should fix those highlights.

I flipped the two directives in https://github.com/helix-editor/helix/pull/5683/commits/7e41845772d77d146b51384f67d75bb4241334af 
(Looks like GitHub hasn't yet updated the PR's commits. You can view the commit in branch context though: https://github.com/LeoniePhiline/helix/commit/7e41845772d77d146b51384f67d75bb4241334af)

**Review by the-mikedavis — APPROVED** [review]
Looks great, thanks for working on this!

**Pull request merged**
