### PR TITLE
add everforest_light, improve everforest_dark string color

### PR DESCRIPTION
**Pull request by WindSoilder**
I'm becoming a new fans of everforest theme....

Adding a new everforest light theme, and make everforest string color to green:
图片

It's just a copy of everforest_dark.toml with different color palette

### CODE REVIEW

**Comment by archseer** [comment]
\cc @CptPotato since you ported the original theme :)

**Comment by CptPotato** [comment]
Thanks for the ping 👍 

I'm not a user of light themes so I can't say how well it compares to others. However, it does look good to me in terms of contrast and readability.

The string color is a good point. I chose to deviate from the original theme and change it to a light grey. This was because both functions and strings shared the same color and lacked visual separation in my opinion. It was very noticable with "string heavy" code.

That being said, changing the color back to green makes the dark theme a more "correct" port of the original and I'm fine with that. I am currently using a [customized version (increased contrast)](https://gist.github.com/CptPotato/d71a389010d4180824f0c079cbf96a04) of this theme anyway, so I get to keep my preferred look anyway :)

**Comment by archseer** [comment]
Okay 👍🏻 the custom theme looks nice, you can upstream it or link to the gist from the wiki if you want?

**Comment by CptPotato** [comment]
> Okay 👍🏻 the custom theme looks nice, you can upstream it or link to the gist from the wiki if you want?

That's a possibility.
I also thought about creating a separate repo where I keep my themes in case I end up customizing or porting more. I might give [sonokai](https://github.com/sainnhe/sonokai) a shot next (it's a lowered contrast version of monokai pro which is already included in helix).

A separate repo would also prevent the additional maintenance burden and bloat, even though it means that themes are a bit harder to discover.

**Pull request merged**
