### PR TITLE
feat(statusline): add option to show total line numbers in file

### PR DESCRIPTION
**Pull request by joshpauline**
I made a PR for this feature a while back, however I was told to make another one after the status line config was implemented. It is a small feature however I think a few people would like the option

### CODE REVIEW

**Comment by poliorcetics** [comment]
I think you forgot to update the documentation ?

**Comment by joshpauline** [comment]
@poliorcetics ah yes let me to that now

**Review by dead10ck — APPROVED** [review]
This looks good to me!

**Comment by joshpauline** [comment]
@dead10ck thank you for accepting!

**Pull request merged**
