### PR TITLE
WIP: Add mouse support

### PR DESCRIPTION
**Pull request by wojciechkepka**
This PR enables mouse capture and adds basic scrolling. I plan to work on adding support for mouse clicks and selection later.

### CODE REVIEW

**Comment by archseer** [comment]
This actually kinda worked for me already since it emits `Up` / `Down` arrow key events on scroll if mouse mode isn't enabled.

I attempted something like this but wasn't sure about the performance since there was a lot of events emitted if I moved the mouse around quickly, enough to spike the CPU. We might need a debounce filter.

**Comment by pickfire** [comment]
It made the cursor scrolls past the screen.

**Comment by wojciechkepka** [comment]
I will close this for now and perhaps resubmit when I have something more.

**Comment by pickfire** [comment]
@wojciechkepka I think you can try mouse support first by clicking on text, that may be easier, scrolling can be done later.

**Pull request closed without merging**
