### PR TITLE
feat: config: allow configuring which providers to use for diffs

### PR DESCRIPTION
**Pull request by poliorcetics**
Completes a TODO that was in the code and prepare for #9643 (which I'll need to rebase on this before merging)

### CODE REVIEW

**Comment by poliorcetics** [comment]
I kept the git feature but since this PR makes it fully configurable and helix moved to gitoxide since the feature addition, maybe we could remove it and let people define `editor.vcs.providers = []` if they don't want any ?

**Comment by pascalkuthe** [comment]
> helix moved to gitoxide since the feature addition

helix has only ever used gitoxide. Gitocide doesn't work with wasm so that's why that feature is there



In general the current approach is not what I want to go with here (I don't want the whole cascading fallback approach that wasn't a good design and now that we have workspace local config you can simply configure your vcs per workspace or globally). There is actually a finished/reviewed PR in https://github.com/helix-editor/helix/pull/8056 that just needs to ber rebase

**Comment by poliorcetics** [comment]
> helix has only ever used gitoxide. Gitocide doesn't work with wasm so that's why that feature is there

Ah my bad I'm confusing it with others that migrated to gitoxide later then

Regarding the rest I commented on the other PR, I think the cascading fallback behavior is very useful and I think removing would be a big mistake

**Comment by pascalkuthe** [comment]
if we are going to have autodetection I would just always autodetect by default without the option to configure and allow the config option from that pr to overwrite autodection.

**Pull request closed without merging**
