### PR TITLE
feat: re-enable haskell syntax

### PR DESCRIPTION
**Pull request by billksun**
Updated tree-sitter-haskell to https://github.com/tree-sitter/tree-sitter-haskell/commit/bf7d643b494b7c7eed909ed7fbd8447231152cb0, and everything compiled. Also verified that syntax highlighting for Haskell is working on NixOS.

### CODE REVIEW

**Comment by archseer** [comment]
The problem was cross compilation to aarch64. I don't think that's easily solvable unless cargo-cross is updated to a newer GCC version. https://github.com/tree-sitter/tree-sitter-haskell/issues/34#issuecomment-855514179

**Comment by billksun** [comment]
Yeah, they have new instructions for building on MacOS: https://github.com/tree-sitter/tree-sitter-haskell#building-on-macos
 
From https://github.com/tree-sitter/tree-sitter-haskell/pull/46

**Comment by archseer** [comment]
Yeah, I had it building on macOS on CI previously. The issue is getting aarch64-linux to compile.

**Comment by archseer** [comment]
With https://github.com/helix-editor/helix/blob/e042121f43f26d1f20bcf0acbda96d169d7cd191/helix-syntax/build.rs#L61-L65 it compiled on macOS

**Pull request closed without merging**
