### PR TITLE
Fix build on aarch64-darwin

### PR DESCRIPTION
**Pull request by jdahm**
Removes `-Clink-arg=-Wl,--no-rosegment` and adds `-mno-outline-atomics` and stackprotector on Darwin and aarch64.

To do:
- decide whether to enable `-Wl,--no-rosegment` on non-aarch64 arches.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
This is looking good to me on x86_64-linux 👍 

Does this fix the flake install for you, or just `cargo build` from within the `nix develop` shell?

**Comment by jdahm** [comment]
Not quite... but it's so close! So far only fixes the `cargo build` in the `nix develop` shell. The flake build errors with:
```
error: builder for '/nix/store/bhx9cbs89vnvr2cxlvlwan2n2z30wh3p-helix-term-0.6.0.drv' failed with exit code 101;
       last 10 log lines:
       >           ld: warning: could not create compact unwind for _ts_node__prev_sibling.constprop.0: register 73 saved somewhere other than in frame
       >           Undefined symbols for architecture arm64:
       >             "___aarch64_ldadd4_acq_rel", referenced from:
       >                 _ts_subtree_retain in libtree_sitter-64cf1c9f9303e665.rlib(lib.o)
       >                 _ts_subtree_release in libtree_sitter-64cf1c9f9303e665.rlib(lib.o)
       >           ld: symbol(s) not found for architecture arm64
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
Let's keep this open for a few days and see if I can't iron out the issues out this path as well. Let me know if you have ideas.

**Comment by jdahm** [comment]
There are a few methods as mentioned in the docs, including adding it to the configuration for a specific target here https://doc.rust-lang.org/cargo/reference/config.html#configuration-format. Another option is setting that as an environment variable, which seems less "pure" in the nix sense. What do you think?

**Comment by the-mikedavis** [comment]
I would probably experiment with an environment variable (you should be able to set one within `helix-term` like we do [here](https://github.com/helix-editor/helix/blob/cf8f59ddd0fa6a18b52fc14cf1f3722b494a5be3/flake.nix#L42)), but the cargo config might be ideal so other packagers don't have to deal with the same problem.

**Comment by archseer** [comment]
Can we still enable `-Clink-arg=-Wl,--no-rosegment` on Linux? I added this in order to get proper flamegraph stack traces: https://github.com/flamegraph-rs/flamegraph#cargo-flamegraph

**Comment by jdahm** [comment]
I found that setting nix-cargo-integration to use `clang` on Mac fixes almost all the problems without having to hack custom flags. My current issue is figuring out how to set `packageMetadata.nix.cCompiler =clang` (or equivalent setting in `Cargo.toml`) when the system is `darwin`. Discussing that over in https://github.com/yusdacra/nix-cargo-integration/issues/65.

**Comment by jdahm** [comment]
`nix run .` is giving me a strange error on this branch: `error: Cannot find source for helix-term:0.6.0`. @the-mikedavis have you seen that one?

**Comment by the-mikedavis** [comment]
Hmm I see the same when doing `nix build` on this branch. I haven't seen that elsewhere though. It looks from the trace like it's from within dream2nix, maybe it's something to do with the update to nix-cargo-integration?

**Comment by yusdacra** [comment]
I can build this branch on the latest `nix-cargo-integration` (on a `x86_64-linux` machine, though). Whatever the issue related to sources was, it seems to be fixed.

**Comment by jdahm** [comment]
@yusdacra thanks for checking that! I guess that means we should get this merged. I'm on vacation right now and away from my computer, so I can't get to this until next week. I gave you access to my fork in case you'd rather do that sooner.

**Review by the-mikedavis — APPROVED** [review]
This branch builds for me (x86_64-linux) and when rebased on master. Let's merge as-is since it's a nice bump of the dependencies and the changes aren't scary.

Could you give this a try on your M1 machine @jdahm? No rush of course, please enjoy your vacation 😀

**Comment by the-mikedavis** [comment]
Thanks for your help here and in nix-cargo-integration @yusdacra!

**Pull request merged**
