### PR TITLE
helix-view: Fix jumpy cursor on vertical center

### PR DESCRIPTION
**Pull request by Aleksbgbg**
Previously, in the case where a high scrolloff was configured in order to center the cursor vertically, the scrolloff would be clamped to a maximum value - the number of lines above and below the center line.

The problem with this approach is that in the case where there are an even number of lines in the view, there are two center lines, and so the cursor would be allowed to visit them both without shifting the view.

To remedy the issue, dedicate the topmost center line as the true center, by splitting the scrolloff value into a top and bottom component where the bottom is one higher than the top.

In all other cases, the behaviour remains the same by setting both components to the same value as the original scrolloff.

### CODE REVIEW

**Comment by Aleksbgbg** [comment]
I just noticed the use of scrolloff in horizontal offset underneath (https://github.com/helix-editor/helix/pull/10795/files#diff-18195c1eaadd7a2747b6556008c6022d79f814d64624e9e69d0735a3e0bbe296R292-R298) that I didn't update. This causes a bug with horizontal scrolling.

@pascalkuthe could you explain why scrolloff is used on those lines? How does scrolloff (which I always assumed was vertical) relate to horizontal offset?

**Comment by Aleksbgbg** [comment]
I fixed the issue above by using the original scrolloff (scrolloff_top) for the horiontal calculations. This works fine and could be merged now, but perhaps I could clean it up with a better understanding of the usage there.

**Comment by senekor** [comment]
I essentially just wrote the exact same patch before finding this. It would be great if somebody reviewed this...

I think I can explain why scrolloff is used even further down: Apparantly, when softwrap is disabled, the scrolloff value is applied horizontally as well. In the current state of the code, this is even more buggy than vertical scrolloff though. With a high enough scrolloff value and if the view width is smaller than the height (e.g. when opening two windows side-by-side), the view violently shakes from left to right while navigating a long line horizontally.

I have also fixed the horizontal scrolloff in [my version of the patch](https://github.com/senekor/helix/compare/f34dca797cf696a19466ab2b3f7e1ca6ffa2bcb7...1323c8883e73b37113c1ed65f127521fbb36ca3d). Anybody feel free to use that. I would make a PR myself, but this one should get a review first.

I have softwrap enabled, so I would've never noticed this without reading the code.

**Comment by pascalkuthe** [comment]
I prefer the implementation by @senekor. Fixing horizontal scrolloff is nice and the use of `min` is easier to understand for me. 

This function should really be decoupled from view/document in the future so we can write tests for something like this... The function is rather complex and this is not the first bug.

**Comment by senekor** [comment]
I'm happy to help work towards better testability of this function. @pascalkuthe do you think that should be easy enough for an almost-first contribution? Fixing that single function was simple enough, but I don't know what I'm getting myself into with such a refactoring.

**Comment by pascalkuthe** [comment]
I was originally thinking of just extracting the method to a function that extracts all the data we extract from the (hard to construct) `View` and `Doucment` objects and passes them as individual arguments (which are individually easy to construct in a test). This would have been fairly straight forward.

But having thagught about it some more I have plans for a larger refactor that would probably shake out the isolation needed to write unit tests without doing that and I would essentially undo this change in the future. So I would rather wait for the larger refactor (that is something only a maintainer can work on) and just merge your PR as-is

**Comment by pascalkuthe** [comment]
closing as https://github.com/helix-editor/helix/pull/11323 was merged

**Pull request closed without merging**
