### PR TITLE
Add common trait for all frontends

### LINKED ISSUE #618: Add common trait for all frontends
that would unblock #39

### PR DESCRIPTION
**Pull request by gbaranski**
closes #618

### CODE REVIEW

**Comment by archseer** [comment]
This runs into the discussions under https://github.com/helix-editor/helix/issues/39, I was leaning towards either abstracting away the `ui` components, or at the very least sharing the components but keeping the rendering traits separate. That way frontends don't all have to look the same.

**Comment by sh7dm** [comment]
Probably this has common tasks with client/server model. Backend is responsible of holding and operating on the code, frontend just tells what to do. They will then share a common protocol

**Comment by gbaranski** [comment]
I think I am not familiar enough with helix internals to implement that big change. It'd be better if someone else handle this.

@archseer 
> I was leaning towards either abstracting away the ui components, or at the very least sharing the components but keeping the rendering traits separate.

My idea was making `Compositor` trait, and all frontends would implement it, and it'd look something like that
```rust
pub trait Compositor {
    fn regex_prompt(
        &mut self,
        prompt: String,
        fun: Box<dyn FnOnce(&mut View, &mut Document, &mut Registers, Regex)>,
    );
    fn command_mode<'a>(
        &mut self,
        completion_fn: Box<dyn FnMut(&str) -> Vec<Completion> + 'static>,
        callback: Box<dyn FnOnce(&mut Context, &str, widgets::prompt::Event)>,
    );
    fn file_picker(&mut self, root: std::path::PathBuf);
    fn buffer_picker(&mut self);
    fn suspend(&mut self);
    // ...
}
```

**Comment by pickfire** [comment]
I don't think it is a good idea to couple file picker and the rest with `Compositor`.

**Pull request closed without merging**
