### PR TITLE
chore: add "ui.virtual.jump-label" to solarized colorschemes

### PR DESCRIPTION
**Pull request by dpc**
I don't know if there are any recommendations, but red works for me - stands out, and I'm an exclusive solarized-dark user.

### CODE REVIEW

**Comment by pascalkuthe** [comment]
Most other themes make the jump label bold. I would dfinitly recommend that

**Comment by dpc** [comment]
> Most other themes make the jump label bold. I would dfinitly recommend that

I just tried and I find it far, far worse

Screenshot_20240330_155154

image

For a quick action like that, I want the keys to be immediately recognizable and for that they need to stand out.

Having said that, I just enabled it, and personally I can just keep my customizations, so I'm happy to change to bold in the PR. Just giving my feedback and fixing it while at it.

**Comment by the-mikedavis** [comment]
I think that @pascalkuthe was suggesting making it red and bold rather than one or the other

**Comment by dpc** [comment]
image

Oh. I see. I like that even better.

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Pull request merged**
