### PR TITLE
lint: papercolor-light

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
passes linter from https://github.com/helix-editor/helix/pull/3234
image

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
@uncomfyhalomacro please sanity check my choices :)

**Comment by uncomfyhalomacro** [comment]
> @uncomfyhalomacro please sanity check my choices :)

sorry. that really hurts my eyes and I don't really believe that's how papercolor uses those palettes. now thats your sanity check for the day ;)

**Comment by uncomfyhalomacro** [comment]
Will leave a review after I eat my breakfast in a few :)

**Comment by AlexanderBrevig** [comment]
Thanks! The only change I made is to try and add a cursorline. I don't particularly like that colour and would appreciate a suggestion. 

This is how it looks on master:
image

**Comment by uncomfyhalomacro** [comment]
@AlexanderBrevig I will open a new PR. I just realized I missed some

**Comment by uncomfyhalomacro** [comment]
See https://github.com/helix-editor/helix/pull/3585

**Comment by AlexanderBrevig** [comment]
Superseeded by #3585

**Pull request closed without merging**
