### PR TITLE
Add themecheck to validate color codes in themes, ignore current known errors.

### PR DESCRIPTION
**Pull request by askreet**
Looking for some feedback on approach here while thinking about #5709.

This patch:
* Adds a first-class concept of warnings to theme parsing, which currently catches all the hexcode parse errors from #5709.
* Updates `themelint` with a known issues list, so it can be enabled in CI and prevent new errors.

If this is interesting to folks the next steps would be:
* Adding it to CI.
* Plumbing the warnings from other bits of `theme.rs` up through `Loader::load`, too, and adding any known issues.

Notes:
* I moved the "//TODO: alert the user..." comment up to a higher level in the code as I think that goal relates more to sending an event to the UI, which I haven't looked into.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
A check in the CI that fails when there are missing hexcodes would be a good addition but we don't want to add themelint to the CI. (Actually we might remove it in the long-run https://github.com/helix-editor/helix/pull/5534#discussion_r1098511929.) If the palette check can be separated from the existing themelint xtask I think this would be a good change 👍

**Comment by askreet** [comment]
Great context, thanks @the-mikedavis. I'll separate these checks out.

**Comment by askreet** [comment]
Pushed up some changes to isolate a new check called `themecheck` that has been added to CI. Open to suggestions on the naming/scoping of the checks. @the-mikedavis

**Comment by askreet** [comment]
@archseer Can I get a quick 👍🏼  / 👎🏼 on whether this is interesting for the project? No pressure on merge timeline, but if you give me a 👍🏼 I will keep it up to date with master periodically, otherwise I'll close it out.

**Pull request closed without merging**
