### PR TITLE
adding markdown support (WIP)

### PR DESCRIPTION
**Pull request by skewballfox**
trying to add markdown support to helix.

will solve [#215](https://github.com/helix-editor/helix/issues/215)

I might be going about this the wrong way as I wasn't sure what changes were needed to add markdown support so I'm repeating the changes commited to [add latex support](https://github.com/helix-editor/helix/pull/276)

### CODE REVIEW

**Comment by kirawi** [comment]
You could also look at https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/markdown for the queries, though they might have to be slightly changed to fit with the [captures](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#highlights) Helix uses.

**Comment by skewballfox** [comment]
thanks, working on that this morning. btw, would line wraps be specified in `language.toml`? 

it seems that would be a pretty sane default given markdown is meant more for prose than programs.

**Comment by skewballfox** [comment]
I'm new to tree sitter grammars and scheme, so please bear with me. 

From what I've seen in other query folders, folds specifies the way in which sections should be folded by listing them in order. for something like header 1 through 6, is there a way to avoid hardcoding it? so that the `#` count determines fold level?

also where can I find the captures used by helix?

**Comment by archseer** [comment]
We don't support folds yet so you can ignore those :)

**Comment by ram02z** [comment]
Relevant issue:
https://github.com/nvim-treesitter/nvim-treesitter/issues/872

According to this, the markdown parser still has issues with crashing on latest.

**Comment by kirawi** [comment]
I would suggest deferring this to a plugin then until it's resolved. https://github.com/raphlinus/pulldown-cmark might be a good candidate.

**Comment by archseer** [comment]
Closed by https://github.com/helix-editor/helix/commit/49e067874133e12d10ad3ac0c941438e2d7025e7

**Pull request closed without merging**
