### PR TITLE
text-objects: add test capture & elixir queries

### PR DESCRIPTION
**Pull request by connorlay**
See https://github.com/helix-editor/helix/discussions/2792

### CODE REVIEW

**Comment by the-mikedavis** [comment]
This is looking good :)

I might push a commit or two with queries for more languages if that's alright

**Comment by connorlay** [comment]
> I might push a commit or two with queries for more languages if that's alright

Go for it! Which languages did you have in mind?

**Comment by the-mikedavis** [comment]
I was thinking at least Rust but also Erlang for my sake 😄

For Rust, we can capture the function following the `#[test]` attribute.

For a few of languages (Erlang EUnit tests and Gleam Gleeunit for example) we could have the captures be pretty much the same as `@function.*` but only for those functions with a name that have a name that ends in `_test`.

**Comment by connorlay** [comment]
@the-mikedavis What do you think about queries for languages that have a number of popular test frameworks, like JavaScript?

This leads me to wonder if Helix should support some kind of opt-in queries for specific frameworks? Highlights and textobjects for the Phoenix router DSL would be handy to have available, but I don't think belongs in the core Elixir queries.

**Comment by the-mikedavis** [comment]
Hmm I think we should aim to only support official language tooling in the core and leave framework-specific features to plugins (once implemented). Especially if two frameworks conflict, it's hard to be rigorous about which one should get support.

For this feature in particular though I don't see any harm in supporting javascript testing frameworks for example

**Review by archseer — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]
Thanks for working on this @connorlay, this is great!

**Pull request merged**
