### PR TITLE
Fix Typos in base16_transparent

### LINKED ISSUE #3373: "failed to load theme" logs despite it is a standard theme
### Summary

not a problem, but for some reason these "failed to load theme" messages appear in logs on every startup for standard themes, everything works fine.

sample:

```

2484   │ 2022-08-09T17:04:12.370 helix_view::theme [WARN] Theme: malformed hexcode: grey
2485   │ 2022-08-09T17:04:12.401 helix_view::theme [WARN] Theme: malformed hexcode: grey
2486   │ 2022-08-09T17:04:12.431 helix_view::theme [WARN] Theme: malformed hexcode: grey
2487   │ 2022-08-09T17:04:12.583 helix_view::theme [WARN] Theme: malformed hexcode: purple
2488   │ 2022-08-09T17:04:12.583 helix_view::theme [WARN] Theme: malformed hexcode: light-grey
2489   │ 2022-08-09T17:04:12.583 helix_view::theme [WARN] Theme: malformed hexcode: greay
2490   │ 2022-08-09T17:04:17.849 helix_view::theme [WARN] Theme: malformed hexcode: purple
2491   │ 2022-08-09T17:04:17.849 helix_view::theme [WARN] Theme: malformed hexcode: greay
2492   │ 2022-08-09T17:04:17.849 helix_view::theme [WARN] Theme: malformed hexcode: light-grey
2493   │ 2022-08-09T17:04:28.207 helix_view::theme [WARN] Theme: malformed hexcode: greay
2494   │ 2022-08-09T17:04:28.207 helix_view::theme [WARN] Theme: malformed hexcode: purple
2495   │ 2022-08-09T17:04:28.207 helix_view::theme [WARN] Theme: malformed hexcode: light-grey
2496   │ 2022-08-09T17:04:30.236 helix_view::theme [WARN] Theme: malformed hexcode: grey
2497   │ 2022-08-09T17:04:30.763 helix_view::theme [WARN] Theme: malformed hexcode: grey
2498   │ 2022-08-09T17:04:31.502 helix_view::theme [WARN] Theme: malformed hexcode: grey
2499   │ 2022-08-09T17:04:36.329 helix_view::theme [WARN] Theme: malformed hexcode: grey
2500   │ 2022-08-09T17:04:36.359 helix_view::theme [WARN] Theme: malformed hexcode: grey
2501   │ 2022-08-09T17:04:36.390 helix_view::theme [WARN] Theme: malformed hexcode: grey
2502   │ 2022-08-09T17:04:36.542 helix_view::theme [WARN] Theme: malformed hexcode: greay
2503   │ 2022-08-09T17:04:36.542 helix_view::theme [WARN] Theme: malformed hexcode: purple
2504   │ 2022-08-09T17:04:36.542 helix_view::theme [WARN] Theme: malformed hexcode: light-grey
2505   │ 2022-08-09T17:05:07.707 helix_view::theme [WARN] Theme: malformed hexcode: grey
2506   │ 2022-08-09T17:05:09.210 helix_view::theme [WARN] Theme: malformed hexcode: grey
2507   │ 2022-08-09T17:05:10.262 helix_view::theme [WARN] Theme: malformed hexcode: grey
2508   │ 2022-08-09T17:05:12.829 helix_view::theme [WARN] Theme: malformed hexcode: purple
2509   │ 2022-08-09T17:05:12.829 helix_view::theme [WARN] Theme: malformed hexcode: greay
2510   │ 2022-08-09T17:05:12.829 helix_view::theme [WARN] Theme: malformed hexcode: light-grey
2511   │ 2022-08-09T17:05:57.096 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
**2512   │ 2022-08-09T17:06:31.963 helix_term::application [WARN] failed to load theme `catppuccin-frappe` - No such file or directory (os error 2)**
```

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

_No response_

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1

### Helix Version

helix 22.05 (bf6f7042)

### PR DESCRIPTION
**Pull request by n0s4**
Fixes #3373.

### CODE REVIEW

**Comment by Omnikar** [comment]
It would appear there are `grey` mistakes in line 26 of all of the `ayu_*` themes as well.

**Comment by sbromberger** [comment]
"grey" is an acceptable spelling for the colo(u)r, though.

**Comment by n0s4** [comment]
Yes, but the [predefined name](https://docs.helix-editor.com/themes.html#color-palettes) for the terminal's grey colour is "gray". As for Ayu's case the colour is defined under the palette as "gray".

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks!

**Pull request merged**
