### PR TITLE
Prevent Helix from scrolling too far past the EOF

### PR DESCRIPTION
**Pull request by Xalfer**
Resolves issue #6966.
Also removes redundant variable `doc_text` because it is the same as `text`.

### CODE REVIEW

**Review by pascalkuthe — CHANGES_REQUESTED** [review]
This does not work with soft wrapped text, approximating with document lines doesn't work Jere as it prevents scrolling slk the way down with soft wrapped text

**Comment by Xalfer** [comment]
> This does not work with softwrapping or virtual text, approximating with document lines doesn't workh here as it prevents scrolling slk the way down with soft wrapped text (or virtual text lines). You need to use a relative visual offset from the EOF. However, that would make scrolling quite slow so that computation should only be done if we are past the threshold you are using here (even that might not be enough in the future with conceal but we will have to figure that out when we get to that)

True, after I made the pull request I've been thinking about the virtual lines and how this actually does nothing about them. When I get the time I'll try to come up with something. Thanks for the feedback.

**Comment by Xalfer** [comment]
So I made some changes and now it works. Now the problem is that the code looks really bad. I'd appriciate feedback from someone whose more knowledgable with the codebase than I do.

**Review by pascalkuthe — COMMENTED** [review]
You just need a single function call, calcutlting the initak position is unneeded and really slow/inefficient. Instead you van transverse from the bottom. There might be an one by off error in the code below you will habe to try but you should get the idea

``` rust 
char_idx_at_visual_offset(
                    text,
                    text.len_chars(),
                    - height as isize + scrolloff as isize,
                    0,
                    &text_fmt,
                    &annotations,
                );
            }
```

**Pull request closed without merging**
