### PR TITLE
bufferline mouse action

### PR DESCRIPTION
**Pull request by hunterliao29**
#5274

### CODE REVIEW

**Comment by gibbz00** [comment]
Maybe not the best to present two features in the PR but I'm guilty of it myself 😅

Anyhow, could the buffer-nth operations be incorporated into the default buffer-next and bugger-prev? Whereby 1 is the default unless a number is specified before the motion. Similar to how one can do `2w`.

**Comment by hunterliao29** [comment]
> Anyhow, could the buffer-nth operations be incorporated into the default buffer-next and bugger-prev? Whereby 1 is the default unless a number is specified before the motion. Similar to how one can do `2w`.

I'm not sure if I understanding this correctly.  Is this about 1 based index, where ```:buffer-nth 1``` should go to the first buffer?

**Comment by gibbz00** [comment]
No, meaning that if I do 3 buffer next i jump to the next buffer 3 times.

**Comment by hunterliao29** [comment]
What should be the behavior of  multiple ```buffer-nth 0```s?

**Comment by gibbz00** [comment]
0`buffer_next` nothing?

**Comment by hunterliao29** [comment]
```:buffer-nth 0``` will switch to the first open buffer, ```:buffer-nth 2``` will switch to the second if there is one and so on. It does not consider their current position like ```buffer_next```.  I am not sure if there is a use case for repeating it.

**Comment by AddictArts** [comment]
I'd like to see this feature happen, but seems to be stuck here. @hunterliao29 I think you might be missing what @gibbz00 is really asking. I think from reading, helix has a `buffer_next` code path; therefore, your `buffer_nth` is really duplicating in a sense what it does. The desire looks like just improving the existing `buffer_next` instead of adding yet another way to move between buffers. Maybe I have that wrong, but looking at code it does seem like one `buffer` motion code path could do both?

**Comment by pascalkuthe** [comment]
Closing this as its quite stale.The bufferline and mouse support are also not a priority.  Thank you for contributing!

**Pull request closed without merging**
