### PR TITLE
Add support for janet language

### PR DESCRIPTION
**Pull request by KittyBorgX**
Resolves : #4574

### CODE REVIEW

**Comment by KittyBorgX** [comment]
I'm sorry for the force pushes 😅 I forgot to add a few things and I didn't want to stack commits, so I rebased and pushed again.

**Comment by the-mikedavis** [comment]
Since Janet is a lisp and looks a lot like clojure, I wonder if we can re-use the clojure or scheme parsers and only write new queries?

**Comment by KittyBorgX** [comment]
> Since Janet is a lisp and looks a lot like clojure, I wonder if we can re-use the clojure or scheme parsers and only write new queries?

Does "new queries" mean injections and highlights in `runtime/queries` ?
I'm sorry, I'm kind of new to this repo and I'll take some time to absorb and understand stuff 😅

**Comment by the-mikedavis** [comment]
Yep correct. To share the same parser you will need to change the languages.toml entry to remove the new `[[grammar]]` sub-table and add a `grammar = "clojure"` or `grammar = "scheme"` entry to the new `[[language]]` sub-table. Then it will need queries in `runtime/queries/janet`

**Comment by KittyBorgX** [comment]
@the-mikedavis [Sorry for the mention!] Any update on this PR?

**Comment by the-mikedavis** [comment]
Hmm yeah, we might as well pull in a new grammar for this - when compiled, this parser is only 174KB. We can work on deduplicating grammars later, maybe we'll need to write a new grammar that's general enough to be used for any lisp.

**Comment by KittyBorgX** [comment]
> Hmm yeah, we might as well pull in a new grammar for this - when compiled, this parser is only 174KB. We can work on deduplicating grammars later, maybe we'll need to write a new grammar that's general enough to be used for any lisp.

Alright! Is there any pending work to be done on my end? (I'm really sorry for going back and forth over this PR) 😅

**Comment by the-mikedavis** [comment]
Yep this still needs `runtime/queries/janet/highlights.scm` queries https://docs.helix-editor.com/master/guides/adding_languages.html#queries

**Comment by KittyBorgX** [comment]
@the-mikedavis Is it alright if I reuse https://github.com/helix-editor/helix/blob/master/runtime/queries/clojure/highlights.scm with a bit of modification for janet atm? I know I'd told against it but I'm not finding enough time to roll out a new one for janet.

**Comment by the-mikedavis** [comment]
Yep that would be fine as long as the syntax is close enough. You can set the grammar to use the clojure one and then inherit the highlights:

```toml
# /languages.toml

[[language]]
name = "janet"
# .. other stuff ..
grammar = "clojure"
```

then in `runtime/queries/janet/highlights.scm`:

```scm
; inherits: clojure
```

to use all of the clojure highlight patterns, or just use the patterns that are needed

**Comment by KittyBorgX** [comment]
Thanks! Btw, How do i resolve the merge conflict? 😅 
Do I just pull the latest upstream changes and commit everything again?

**Comment by the-mikedavis** [comment]
You can pull down the master branch from this repo and `git merge` against that:

```
git remote add upstream https://github.com/helix-editor/helix
git fetch upstream
git merge upstream/master
```

**Comment by KittyBorgX** [comment]
(first off, im really sorry for the delay) 
@the-mikedavis I tried merging the conflicts but its only gotten worse. I want to complete the changes you suggested in this PR. Any advice?

**Comment by Plasma-Vortex** [comment]
It sounds like you have uncommitted changes in your local branch. You should commit them first before running `git merge upstream/master`

**Pull request closed without merging**
