### PR TITLE
Add dracula at night theme

### PR DESCRIPTION
**Pull request by samsartor**
Super simple. I just like a darker background lol

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]
This looks nice! I'm a fan of the higher contrast 🎨

**Comment by the-mikedavis** [comment]
The file name has dashes instead of underscores; it looks like we've mostly used underscores but there are exceptions. The inconsistency doesn't really bother me - do others have opinions on this? Should we prefer one or the other?

**Comment by the-mikedavis** [comment]
Don't forget to add this to the themes wiki once merged! https://github.com/helix-editor/helix/wiki/Themes

**Comment by David-Else** [comment]
> The file name has dashes instead of underscores; it looks like we've mostly used underscores but there are exceptions. The inconsistency doesn't really bother me - do others have opinions on this? Should we prefer one or the other?

They should all be underscores, it could be triggering for programmers to encounter the aberration of inconsistent file naming.

**Comment by the-mikedavis** [comment]
Just wait until I make a theme with a non-breaking whitespace character :P

**Pull request merged**
