### PR TITLE
lint: pop-dark

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
passes linter from https://github.com/helix-editor/helix/pull/3234
image

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
@workingj please sanity check my choices :)

**Comment by AlexanderBrevig** [comment]
Moved to bulk PR https://github.com/helix-editor/helix/pull/3587

**Comment by workingj** [comment]
@AlexanderBrevig aproved! :smile:

**Comment by workingj** [comment]
sry for the late response, busy days...

**Pull request closed without merging**
