### PR TITLE
lint: boo_berry

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
passes linter from https://github.com/helix-editor/helix/pull/3234
image

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
@bootradev please sanity check my choices :)

**Comment by Omnikar** [comment]
Is opening one PR for every one of the themes really necessary?

**Comment by AlexanderBrevig** [comment]
I wanted a way to get a follow up from each author. It would be pretty crowded in a "one PR to rule them all" situation.

But I can make a big PR if that is preferred.

**Comment by Omnikar** [comment]
Hm, I'm not sure.

**Comment by AlexanderBrevig** [comment]
Oh well. It's done now. Worked all night on this, and finally now I can actually choose a random Helix theme and actually get work done with it :) 

I will apologize in the Matrix chat for the noise it stirred up.

**Comment by bootradev** [comment]
What does it look like when the cursor is on a line with text on it?

**Comment by AlexanderBrevig** [comment]
it collided with selection, maybe going a slight tad up in brightness is better?
image

**Comment by bootradev** [comment]
Sure, have berry_dim be `#47345E`

**Comment by AlexanderBrevig** [comment]
Moved to bulk PR https://github.com/helix-editor/helix/pull/3587

**Pull request closed without merging**
