### PR TITLE
Fix inconsistent prompts

### PR DESCRIPTION
**Pull request by Omnikar**

### CODE REVIEW

**Review by sudormrfbin — COMMENTED** [review]
I think we should keep it to `Global search: ` and `Rename to: `, with a space at the end for readability.

**Comment by Omnikar** [comment]
I'm slightly less indifferent about the hyphen vs. space, but I definitely prefer not to begin prompts with capital letters. All the other prompts are already all-lowercase.

**Comment by pickfire** [comment]
I think global search should not be a prompt but be like the rest of the pickers.

**Comment by Omnikar** [comment]
> I think global search should not be a prompt but be like the rest of the pickers.

But… global search needs a pattern to search for

**Comment by archseer** [comment]
> I think global search should not be a prompt but be like the rest of the pickers.

Yeah an interactive global search is what I wanted but the initial implementation uses a prompt for the query since it was simpler to implement. See https://github.com/helix-editor/helix/issues/196, probably better to continue discuss it there

**Comment by archseer** [comment]
> that no space after the prompt is intentional

Yeah it's a bit easier to tell if you're typing a regex with a space at the start I think, I don't mind the lack of spacing

**Pull request merged**
