### PR TITLE
Add eb word selection trick to the tutor

### PR DESCRIPTION
**Pull request by matklad**
Maybe this is obvious, but it took me several days to google this up :-)

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
I like having an example for `w`/`b`/`e` for selecting words 👍

Finding a place for it will be a little tricky though: each tutor section has a constant height of 19 rows and this currently makes ch 3.2 too tall

**Comment by Omnikar** [comment]
We could give the extra stuff the space of one full other page, so that the uniformity is maintained.

**Comment by matklad** [comment]
What about this version? This also gives space to add an example for WORDS, which I think might be useful for people not already familiar with vim.

**Review by the-mikedavis — APPROVED** [review]
This looks great, thank you!

**Comment by matklad** [comment]
Filed https://github.com/helix-editor/helix/issues/5284 which sounds like a good `E-good-first-issue`.

**Pull request merged**
