### PR TITLE
Implement buffer fuzzy search

### PR DESCRIPTION
**Pull request by useche**
These patches implement the `buffer_search_picker` command that shows a picker to fuzzy search in the current buffer. Note that one of the patches is cleaning up `Picker::new` method somewhat.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
I'm wary of misusing the picker UI for information that doesn't need it, like the jumplist picker which in retrospect I don't think we should have merged. Loading all of a document's lines into a picker seems like an abuse of the picker component to me.

I'm not interested in pulling in the new picker but b4e83a0 is a good change that I might cherry-pick onto #9647

**Comment by the-mikedavis** [comment]
I'll push a commit with a [co-authored-by](https://github.com/helix-editor/helix/pull/10159#issuecomment-2041084272) annotation when I rebase that branch. I'm saying that I'm very hesitant to approve/merge this new picker at all. To me it seems like a solution looking for a problem - I don't understand the use case for it. It's also duplicating the entire file contents into a bunch of `String`s which is expensive for large files.

**Comment by useche** [comment]
I actually used it quite a bit when I was using neovim. It's useful for code navigation when you are not really sure what is the exact name of the thing you are looking for. Without this, you need to know exactly (including case-sensitive) what you are looking for. This is why I'm implementing it.

I do agree about the String using additional memory, especially for big files. I think that should be solvable by using `RopeSlice` instead of `String`, but I couldn't find a way to make the lifetime work (I'm pretty new to Rust).

**Comment by the-mikedavis** [comment]
You should search with `/` instead. Search is smart-cased by default so if you use all lowercase it will behave like a case insensitive search. Since we switched to regex-cursor searching operates on the RopeSlice rather than converting to a String so it's fairly efficient.

You can't use `RopeSlice` since picker items need to be owned and `RopeSlice` is a reference to the data owned by a `Rope`. It is possible to hack something together passing the doc's text as `menu::Item<Data = Rope>`:

<details><summary>Passing a Rope...</summary>

```rust
fn buffer_search_picker(cx: &mut Context) {
    struct SearchMeta {
        line_number: usize,
    }

    impl ui::menu::Item for SearchMeta {
        type Data = Rope;

        fn format(&self, data: &Self::Data) -> Row {
            format!("{} {}", self.line_number, data.line(self.line_number)).into()
        }
    }

    let doc = doc!(cx.editor);
    let doc_id = doc.id();
    // Cloning a Rope is very cheap - it does not clone the contents.
    let text = doc.text().clone();
    let picker = Picker::new(
        (1..text.len_lines()).map(|n| SearchMeta { line_number: n }),
        text,
        |cx, meta: &SearchMeta, _action| {
            goto_line_without_jumplist(cx.editor, NonZeroUsize::new(meta.line_number));

            let scrolloff = cx.editor.config().scrolloff;
            let (view, doc) = current!(cx.editor);
            view.ensure_cursor_in_view(doc, scrolloff);
        },
    )
    .with_preview(move |_editor, meta| {
        let line = meta.line_number;
        Some((doc_id.into(), Some((line, line))))
    });

    cx.push_layer(Box::new(overlaid(picker)));
}
```

</details>

But it still allocates a String for every line because of the formatting as a Row. Also the lookup of a line by index is an operation that runs in logarithmic time on a Rope. I don't see any way of making this picker efficient. Plus the display is hard to read: including the full line in the picker as an option means that most lines will be truncated even when you're running Helix in a fairly large window. Maybe we could consider a regex based searching picker that only operates on the current buffer or just the open documents like https://github.com/helix-editor/helix/issues/5597#issuecomment-1400922935 but I don't want to see a picker added that fuzzy matches on entire documents.

**Comment by zetashift** [comment]
I also regularly use fuzzy-find-in-buffer(s). I know that I could use `/` and press `n` a couple of times, but the overview in picker is a really nice(atleast in Emacs/consult) user experience.

For example, when I'm in a buffer without LSP, and I want to jump to a "symbol" in a fairly long(100+ lines) buffer. A picker works really nice for jumping through, atleast UI wise.
Another example: I had several HEEx(an Elixir thing) function components, and searching through `input` would have felt easier to me in a picker than `/` and pressing `n` a bunch of times.

> Maybe we could consider a regex based searching picker that only operates on the current buffer or just the open documents like https://github.com/helix-editor/helix/issues/5597#issuecomment-1400922935

This also works! I understand not wanting this in the main repo as well, but I hope atleast it'll be ergonomic to script such things in that case.

**Comment by useche** [comment]
I was looking at the fuzzy global search in #9647 and realized that the fuzzy search in the current buffer is a subset of the whole global search. So to have a fuzzy search in the current buffer you can open global search with the query "%path:current_buffer whatever_youre_searching". Maybe we can implement it that way? By using the global search somehow? It won't be able to search in buffers that have not backing, though. But I'm guessing that's fixable.

**Comment by the-mikedavis** [comment]
Yeah that could work, you could global search using your current path as the `path` column (entering it with `<C-r>%`). Not searching scratch buffers seems like not a big deal to me - usually scratch buffers are relatively small and short-lived so they usually don't have much of consequence in them. You also couldn't tell the difference between two scratch buffers (at least with the way we display scratch buffer paths at the moment).

I think it could be useful to have a picker that behaves the same as global search on #9647 but only searches within open documents. It would be much simpler than `global_search` too since we wouldn't need WalkBuilder

**Comment by useche** [comment]
Thanks @the-mikedavis for all the help. I think the global search in #9647 covers my use case pretty well.

**Comment by Axlefublr** [comment]
😭 I would love to have this \
but it might be a tall order to ask you to maintain this for the forkers, considering that upstream won't take this :c

**Pull request closed without merging**
