### PR TITLE
Simplify change/delete selection, remove blckhole register

### PR DESCRIPTION
**Pull request by kosciej**
From my understanding blackhole `'_'` register is used only in `delete_selection_noyank` and `change_selection_noyank`.

Blackhole `'_'` register also significantly changes logic in otherwise very simple `Record` struct.

This PR tries to remove blackhole register altogether, also unifying `yank` logic where applicable.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
The blackhole register is a feature though, and it comes from kakoune: https://github.com/mawww/kakoune/blob/master/doc/pages/registers.asciidoc#special-registers

**Comment by kosciej** [comment]
Ok, I get it. What might be possible usages of this register?

**Comment by ath3** [comment]
It can also be used with search if you dont want the searched term to be remembered.

**Comment by kosciej** [comment]
That sounds compelling. 
@the-mikedavis I can remove change removing blackhole register. Do you think refactor for `yank` from this commit would be useful, or should I close this PR?

**Comment by the-mikedavis** [comment]
Actually I kinda like the yanking behavior of `delete_selection_impl`. We could probably remove that `if cx.register != Some('_')` check in `delete_selection_impl` since it's only preventing us from writing to the blackhole register which is a noop anyways

**Comment by ath3** [comment]
> Actually I kinda like the yanking behavior of `delete_selection_impl`. We could probably remove that `if cx.register != Some('_')` check in `delete_selection_impl` since it's only preventing us from writing to the blackhole register which is a noop anyways

Its to prevent unnecessary cloning and collecting of the selected text in case we wont use it.

**Comment by the-mikedavis** [comment]
Closing as the blackhole register is an intentional feature

**Pull request closed without merging**
