### PR TITLE
Add suggestions in book(`remapping.md`)

### PR DESCRIPTION
**Pull request by python128**
These are some suggestions for users to make their own keymaps without any clash occuring.

### CODE REVIEW

**Comment by pickfire** [comment]
Shouldn't we keep a list that will clash instead? Also, later we can do a check on this.

**Comment by pickfire** [comment]
>  But this is only a list of keymaps which are not used, and can be re-mapped as per the user's preference.

And we need to maintain this. Currently people can easily miss book changes, with this it might need to have extra effort from contributors. At least that is what I think.

I do think it is okay to merge it, just that it may be outdated later on if we don't keep track.

**Comment by python128** [comment]
Actually, this was based from kakoune [wiki](https://github.com/mawww/kakoune/wiki/Normal-mode-commands#suggestions)..

So, if you want, I can add this to the wiki..

**Comment by archseer** [comment]
Yeah I'd rather see that, this way it's more informal and not necessarily up to date. Note that we don't guarantee those keys will stay available in the future

**Comment by python128** [comment]
Ok great 👍

**Comment by python128** [comment]
Where shall I add the page?

**Comment by sudormrfbin** [comment]
I think right after the keyboard layout image in https://github.com/helix-editor/helix/wiki/Keymap-brainstorm is okay (maybe with a disclaimer label of it being outdated).

**Comment by python128** [comment]
Done 👍

**Pull request closed without merging**
