### PR TITLE
feat: add wgsl_analyzer as wgsl language server

### PR DESCRIPTION
**Pull request by Hekno25**

### CODE REVIEW

**Comment by Hekno25** [comment]
This is the server's repo: [https://github.com/wgsl-analyzer/wgsl-analyzer](https://github.com/wgsl-analyzer/wgsl-analyzer)

**Review by the-mikedavis — APPROVED** [review]
Thanks!

**Comment by the-mikedavis** [comment]
Could you link the language server in the default language server installation wiki? https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

**Comment by Hekno25** [comment]
Sure thing!

**Pull request merged**
