### PR TITLE
Add Kaolin Dark, Light and Valley Dark themes

### PR DESCRIPTION
**Pull request by thlsrms**
Hi, I tried porting these variations based on the original [Kaolin themes](https://github.com/ogdenwebb/emacs-kaolin-themes) palette:

<details>
  <summary>Kaolin Dark</Summary>
  <br>

  kaolin-dark
</details>

<details>
  <summary>Kaolin Light</Summary>
  <br>
  
  kaolin-light
</details>

<details>
  <summary>Kaolin Valley Dark</Summary>
  <br>
  
  kaolin-valley-dark
</details>

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
Are these themes the same except for color choices? If they're similar enough, only one of the themes needs to be written out fully and then the others can inherit that theme and overwrite the palette: https://docs.helix-editor.com/master/themes.html#inheritance (for example see the gruvbox themes)

**Comment by thlsrms** [comment]
> Are these themes the same except for color choices? If they're similar enough, only one of the themes needs to be written out fully and then the others can inherit that theme and overwrite the palette: https://docs.helix-editor.com/master/themes.html#inheritance (for example see the gruvbox themes)

Makes sense. I pushed the changes using inheritance and overriding the palette and differing properties for the light and valley-dark variants.

**Review by the-mikedavis — APPROVED** [review]

**Comment by zoedsoupe** [comment]
i would like to ask for symbols support like for atoms in Elixir, Ruby’s symbol and Clojure’s keyword. they’re mean to semantically have the same color as modules, or in other worlds, a different color from common “strings”. how I could implement it?

**Comment by the-mikedavis** [comment]
You'll want to theme the `"string.special.symbol"` key:

```toml
# ~/.config/helix/themes/mytheme.toml
inherits = "kaolin-dark"
"string.special.symbol" = "info"
```

**Pull request merged**
