### PR TITLE
Document how to use modifier keys in macro remaps

### PR DESCRIPTION
**Pull request by adamchalmers**
Fixes https://github.com/helix-editor/helix/issues/11929

### CODE REVIEW

**Comment by adamchalmers** [comment]
Here you go @Gabrielbdd

**Review by the-mikedavis — APPROVED** [review]

**Comment by gabydd** [comment]
This looks ok, this and https://github.com/helix-editor/helix/pull/11953 intersect a bit but that pr can probably be rebased upon this pr if this pr is merged

**Comment by adamchalmers** [comment]
Hah, that PR was prompted by my Reddit post

**Comment by thomasaarholt** [comment]
Happy to rebase ontop of this 😊

**Pull request merged**
