### PR TITLE
Add error upon tutor requested without runtime dir

### PR DESCRIPTION
**Pull request by SoraTenshi**
As mentioned in #5050 it would be great to let the user immediately know whether or not the runtime directory is linked.

Might be beneficial especially for new users.

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
I think that the "Is the runtime directory linked?" phrase would be confusing for a new user. I'm not quite sure what the right words are. Maybe we could point to the healthcheck since it prints out the runtime directory?

**Comment by SoraTenshi** [comment]
> Maybe we could point to the healthcheck since it prints out the runtime directory?

Hm. Not really sure about that one, since the confidience of the tutor not being able to launch due to missing runtime dir is pretty high.

**Comment by the-mikedavis** [comment]
I mean that I'm not sure what the error message can say here that would help a new user fix the problem since explaining what the runtime directory is and how to link it usually takes quite a few words (for example https://github.com/helix-editor/helix/issues/3768#issuecomment-1344821332).

We could link to a wiki page or the text in the README but hyperlinks in error messages can be a little brittle. Ideally we could have a `:help` page on the runtime directory and the error message could say "Check `:help runtime` for more information" or something like that

**Comment by the-mikedavis** [comment]
For the scope of this PR though it's probably ok to word this as "Runtime directory not found" (we should avoid "linked" since distros usually setup the runtime directory by setting $HELIX_RUNTIME). Better in-editor docs for the runtime dir can be figured out in the future, this will be a nice improvement over the current blank file behavior on its own 👍

**Comment by SoraTenshi** [comment]
> I mean that I'm not sure what the error message can say here that would help a new user fix the problem since explaining what the runtime directory is and how to link it usually takes quite a few words (for example [#3768 (comment)](https://github.com/helix-editor/helix/issues/3768#issuecomment-1344821332)).
> 
> We could link to a wiki page or the text in the README but hyperlinks in error messages can be a little brittle. Ideally we could have a `:help` page on the runtime directory and the error message could say "Check `:help runtime` for more information" or something like that

I think the help section kind of sounds pretty neat.
I will create a mock up of it in a few hrs.

**Comment by SoraTenshi** [comment]
@the-mikedavis Alright, so i made a basic mockup implementation, however i am unsure how to formulate those message. Do you have an idea?

**Comment by gabydd** [comment]
There actually is already an in progress help pr #997, I was going to mention this yesterday but I totally forgot sorry

**Comment by SoraTenshi** [comment]
> There actually is already an in progress help pr #997, I was going to mention this yesterday but I totally forgot sorry

Oh wow. Didn't know this was a thing yet.
But it also seems like the PR is stale. Maybe it is a good idea to just convert it to draft for now and then merge the changes?

**Comment by the-mikedavis** [comment]
I've been looking at cleaning up that branch a bit and adding a page for the runtime directory https://github.com/helix-editor/helix/compare/master...help-command

We will probably want to embed the page for the runtime within the helix binary (since it should still show when the runtime directory is not there)

**Pull request closed without merging**
