### PR TITLE
Change twig tree-sitter grammar

### PR DESCRIPTION
**Pull request by gbprod**
https://github.com/eirabben/tree-sitter-twig seems to be abandonned. I suggest to use my  [twig tree-sitter parser](https://github.com/gbprod/tree-sitter-twig) instead :)

### CODE REVIEW

**Comment by EpocSquadron** [comment]
Tested this out with a large twig codebase I have lying around, this is pretty close! One thing I'm seeing is that with onelight theme things like `if` and `endif` are colored differently.

image

**Comment by gbprod** [comment]
It's because it's highlighted with `@tag`, maybe we should use `@keyword` instead.
I update the pull request.
Thanks for your feedback

**Comment by EpocSquadron** [comment]
Took a look again, didn't help. The `if` is a `conditional` in the grammar, whereas `endif` is a `tag`. I think the solution here is to special case `endif` in the grammar itself, and restore the tag highlighting to how you had it.

You can use `:tree-sitter-scopes` with the cursor on the element in question to see its parsed type.

**Comment by gbprod** [comment]
I fixed it in grammar :)
Thanks for your usefull feedback!

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Looks good, thanks for picking up this grammar!

**Pull request merged**
