### PR TITLE
update colors for papercolor-light

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
image
now looks like this

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
Nice!

**Comment by uncomfyhalomacro** [comment]
ready for merging

**Review by pickfire — APPROVED** [review]
Thanks, but please update the wiki as necessary. I wonder if we should have a script to automatically update the wiki based so that contributors don't have to manually do that.

**Comment by AlexanderBrevig** [comment]
> Thanks, but please update the wiki screenshots if necessary. I wonder if we should have a script to automatically update the wiki based so that contributors don't have to manually do that.

I definitely think we should do that. Do you know if anyone is working on it?

**Comment by AlexanderBrevig** [comment]
I will give it a try!

**Pull request merged**
