### PR TITLE
Reduce logos-with-text sizes (-323B -322B)

### PR DESCRIPTION
**Pull request by goyalyashpal**
#### chore(logo_dark): Pretty to reduce size by 323B ...
  * Current size:  6,930 B
  * Original size: 7,253 B
  * Add tab indentation (instead of 2/4 spaces)
  * Pretty Print by hand

#### chore(logo_light): Pretty to reduce size by 322B ...
  * Current size:  6,599 B
  * Original size: 6,922 B
  * Add tab indentation (instead of 2/4 spaces)
  * Pretty Print by hand

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Same as #9106, it'd be fine to minify these by stripping all unnecessary whitespace, the trailing newline and maybe stripping the inkscape attributes but I don't see any value in pretty printing. These files are formatted right now only because that's how inkscape exported them

**Comment by goyalyashpal** [comment]
_"minify"_

after 2-3 days.

_"strip ink's attribs"_

stripping ink's attribs would be a destructive operation. rendering these
equivalent to a useless build adtifact, unable to be modified later. all
the work put into this will be gone. are u _sure_ u want to do that?

**Comment by goyalyashpal** [comment]
> Same as #9106, it'd be fine to minify these by stripping ...

also, the case with logo and logo-with-text is not same for minification - as here, there are 2 versions. the prettification makes it trivial to compare both the themes.



rest the decision is onto u.

**Comment by the-mikedavis** [comment]
> \_"minify"\_ after 2-3 days

Yeah this is not exactly high priority. Let's leave the files as they are, they're just used for display purposes for the README.

**Pull request closed without merging**
