### PR TITLE
theme: Add Varua color scheme

### PR DESCRIPTION
**Pull request by kamek-pf**
Porting the color palette I've been using for a couple years before moving to Helix.
Cheers :)

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
Can you please add `"ui.cursorline.primary" = { bg = "something" }`
Which is a feature available in the next version. Replace something with what you want.

**Comment by kamek-pf** [comment]
Done ! I typically don't use a different color for the cursorline so I used the same color as the background. But it is defined now.

**Comment by AlexanderBrevig** [comment]
It will feel like a bug for people who have enabled cursorline if it does not show up though. I think themes should provide the features Helix allows for. Cursorline is disabled by default so you won't see it unless you enable it, at which point - I think you should see it. :)

**Comment by kamek-pf** [comment]
Yeah that makes sense, I picked a different color, it should look nice, I'll probably give the new feature a try :p

**Review by the-mikedavis — APPROVED** [review]
Looks nice, thanks! 🎨

**Comment by the-mikedavis** [comment]
Could you add a screenshot of this to the themes wiki? https://github.com/helix-editor/helix/wiki/Themes

**Comment by kamek-pf** [comment]
Screenshot was added. Thanks !

**Pull request merged**
