### PR TITLE
Update README.md to include shortcuts

### PR DESCRIPTION
**Pull request by eleijonmarck**

### CODE REVIEW

**Comment by kevinsjoberg** [comment]
@eleijonmarck might be worth noting that the current keymaps are also documented on the website. See https://docs.helix-editor.com/keymap.html.

**Comment by eleijonmarck** [comment]
@kevinsjoberg is it possible to get some input on how to get started with typescript/golang or rust to get the syntax highlighting and things working.
Unrelated to the PR

**Comment by archseer** [comment]
Yeah I'd rather see this add a link to the keymap doc.

Regarding highlighting: it should work for a larger range of languages, it's rust & go specifically for indents (and now typescript/js). If you aren't seeing any highlighting in development you need to make sure to set `HELIX_RUNTIME` to point to the `runtime/` folder, i.e. 

https://github.com/helix-editor/helix/blob/f4560cb68a24276789e8cdda918fc1ba705889de/shell.nix#L16

**Comment by eleijonmarck** [comment]
@archseer 
Thx for commenting!

soo i might be a bit noooob here.
But `runtime/` folder here is where the `go` src would be or the /bin/ i guess.

**Comment by IceDragon200** [comment]
Thank you

**Pull request merged**
