### PR TITLE
feat(ci): automatic homebrew tap updates

### PR DESCRIPTION
**Pull request by matoous**
Automatically update homebrew tap to latest tagged releaso of helix.

Fixes: https://github.com/helix-editor/helix/issues/9

### CODE REVIEW

**Comment by matoous** [comment]
Needs `COMMITTER_TOKEN` set to personal token with repo access, if the token has write access the action can merge directly, otherwise it submits PR.

**Comment by archseer** [comment]
We could also drop the tap altogether and upstream the formula?

**Comment by matoous** [comment]
Why not, will take a look 👍

**Comment by matoous** [comment]
closing in favor of: https://github.com/Homebrew/homebrew-core/pull/92085

**Pull request closed without merging**
