### PR TITLE
add tree-sitter-regex

### PR DESCRIPTION
**Pull request by the-mikedavis**
Example injected into elixir

regex

it's a pretty subtle improvement; I'm not too impressed yet. Let me dig into the grammar and see if we can write some more interesting queries beyond brackets and quantifiers.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
getting closer...

regex2

the grammar actually parses some cool stuff, I'm surprised the captures in the upstream repo are so thin :smile:

**Comment by kirawi** [comment]
Maybe you can upstream the queries :P

**Comment by the-mikedavis** [comment]
> Maybe you can upstream the queries :P

tree-sitter-regex is looking a bit in need of maintenance in general, I'll see if I can fixup some of the open issues and clean up queries and testing before opening up this PR for review :+1:

**Comment by the-mikedavis** [comment]
ok I dusted off the repo and upstreamed the queries

it's starting to look pretty good now:



I didn't look around too much for other languages to inject regex into. Seems like rust would be a good idea but I don't think there's a syntactic construct that is always a regex like `/foo/` in js or sigil-r in elixir? Maybe we can inject regex into any raw string argument to `Regex::new`?

**Comment by pickfire** [comment]
Are you looking into doing this in rust?
```scm
(call_expression
  function: (scoped_identifier
    path: (identifier) @_regex (#eq? @_regex "Regex")
    name: (identifier) @_new (#eq? @_new "new"))
  arguments: (arguments
    (raw_string_literal) @regex))

(call_expression
  function: (scoped_identifier
    path: (scoped_identifier (identifier) @_regex (#eq? @_regex "Regex").)
    name: (identifier) @_new (#eq? @_new "new"))
  arguments: (arguments
    (raw_string_literal) @regex))
```

**Comment by the-mikedavis** [comment]
rust-regex

Beautiful :tada:

**Review by pickfire — APPROVED** [review]
Nice, looks good to me. \o/

**Pull request merged**
