### PR TITLE
lint: snazzy

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
passes linter from https://github.com/helix-editor/helix/pull/3234
image

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
@nrdxp please sanity check my choices :)

**Comment by Omnikar** [comment]
Well, this is PR 24, you *almost* covered the whole first page

**Comment by AlexanderBrevig** [comment]
Yeah, I'm done now.

**Comment by Omnikar** [comment]
24 hour Github insights
image

**Comment by AlexanderBrevig** [comment]
How many hours did you spend on Helix contributions today? Are you trying to make me feel bad? 

I did offer to close them all and make a new PR if a core member asks me to.


@nrdxp sorry for derailing here, I were meaning to ask for your input on this.

**Comment by Omnikar** [comment]
> Are you trying to make me feel bad?

No not at all, thanks a lot for working on all of this, I just found the sheer quantity of PRs a bit funny.

**Comment by AlexanderBrevig** [comment]
Yeah :p it became quite a bit more work than I initially intended. Does reflect the feeling I had that the themes were lacking in some details. 

Sorry for getting defensive. I'm tired.

**Comment by archseer** [comment]
I think all of these could have been separate commits in a single PR?

**Comment by AlexanderBrevig** [comment]
> I think all of these could have been separate commits in a single PR?

Yeah. Do you want me to close them and make a new one?

**Comment by archseer** [comment]
If you don't mind, it would be slightly easier to review and merge

**Comment by AlexanderBrevig** [comment]
How should I indicate changes which have already been approved by original authors? 
I'll close and recreate tonight 👍

**Comment by AlexanderBrevig** [comment]
Moved to bulk PR https://github.com/helix-editor/helix/pull/3587

**Pull request closed without merging**
