### PR TITLE
Tree Explorer

### PR DESCRIPTION
**Pull request by evertonse**
Tree Explorer

helix-merge-showcase

### CODE REVIEW

**Comment by pascalkuthe** [comment]
I am guessing this is a rebase of #2377? It's good practice to credit the original or both in the commits and the PR description.

**Comment by archseer** [comment]
Agree, if this is just a rebase the original author should be retained on the commits.

**Comment by evertonse** [comment]
Sorry guys, big noob here. I just clicked pull request button as soons as I decided things were working properly.
I intend to credit the original guy @cossonleo . I'm trying to edit the part where I've put the img, but idk how.

**Comment by archseer** [comment]
How to amend commits: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-a-single-commit

**Comment by mvllow** [comment]
Would love to see this work out of the box without needing (I assume) a patched font.

E.g. folder icons:

Screenshot of folder icons in the file explorer rendering as white boxes instead of a folder.

## More subjective feedback

**Behaviour**

> Happy to see these as defaults or an added option if other users are also interested

- Toggle tree visibility via `space e` instead of toggling focus.
- Hide preview window when hovering a tree item. This adds a bit of clutter and this functionality exists already inside of `space f`.
- Allow sidebar to be swapped to the right side. More useful when quickly toggling the tree open/closed.

**Keymaps**

> Current decisions may be based on technical limitations or to ease maintainability

_Merge file/directory commands_

For example, replace `mf/md` (make file/make directory) with `a` (add file or directory). Create a directory if user input ends with a "/".

Thank you to everyone helping to build this feature, it's much appreciated 💜

**Comment by kirawi** [comment]
> Would love to see this work out of the box without needing (I assume) a patched font.

It shouldn't, unless this PR also includes https://github.com/helix-editor/helix/pull/2869

**Pull request closed without merging**
