### PR TITLE
feat(line-numbers): add total line numbers to position content

### PR DESCRIPTION
**Pull request by joshpauline**
I have been using helix as my main power house for work recently, however there are a couple things that would really like to integrate. The first of which is having a total line number indicator in the editor. 

Some may disagree but I like having it there.

### CODE REVIEW

**Comment by EpocSquadron** [comment]
Perhaps this could be rebased on to #2434 as I could see people wanting this to be configurable.

**Comment by heliostatic** [comment]
Adding a screenshot for more context.

Existing: 
2022-06-30 at 09 15 35 - Alacritty - CleanShot

Proposed:
2022-06-30 at 09 09 51 - Alacritty - CleanShot

**Comment by the-mikedavis** [comment]
Yeah I think it would be best for this to await #2434 so it can be configurable.

**Comment by joshpauline** [comment]
yea ok the configurable status line would be great.

**Pull request closed without merging**
