### PR TITLE
book: Clarify install commands for msys2 in Windows

### PR DESCRIPTION
**Pull request by Biswa96**
@podsvirov @yashpalgoyal1304 Please review.

### CODE REVIEW

**Comment by podsvirov** [comment]
Looks good, more informative.

**Comment by yashpalgoyal1304** [comment]
wow, awesome. yes, i have some input for discussion. will post in some
hours directly via website lest the bug via email-replies wil recur.

**Comment by yashpalgoyal1304** [comment]
the website is not updated?

**Comment by Biswa96** [comment]
> the website is not updated?

It's here https://docs.helix-editor.com/master/install.html

**Comment by gabydd** [comment]
It will be in the master docs, the stable docs get updated every release

**Pull request merged**
