### PR TITLE
Add dark high contrast theme refer to vscode

### PR DESCRIPTION
**Pull request by GreasySlug**
Issues: #3217 
Discussions: #3238 
I created a dark high contrast theme refer to vscode dark high contrast theme.

It is hard for me to create a light theme and I did not get a feedback for it as mentioned in the discussion.
Therefore, the it is not included in this PR.
For now, I've already created it.

### CODE REVIEW

**Comment by d4h0** [comment]
Thanks for creating this theme, @GreasySlug!

It is much better for my crappy eyes than the other themes.

One problem I see, are comments. The contrast is way too low (I almost can't read comments).

Couldn't comments be white or almost white?

To me, comments are a very important part of source code, and I don't really understand why they are almost always treated as unimportant (cursive, and hard-to-read gray color).

**Comment by GreasySlug** [comment]
You are certainly right.
No other high contrast theme used gray and italics.
I have a feeling that most of them use green, is green correct?

fixed_comment_color

**Comment by d4h0** [comment]
> I have a feeling that most of them use green, is green correct?

I'm not sure if green is often used for high-contrast themes, but there seem to be already two green shades used in the theme. And while the darker green shade from your screenshot above is certainly a bit easier to ready than the current dark gray, I believe white (or a very light gray) would be easier to read (and isn't used for anything besides punctuation characters).

**Comment by d4h0** [comment]
Thanks, @GreasySlug, this looks great!

Btw., I think italic text is more difficult to read than non-italic text, but I'm not completely against using italic for comments. 

Italic has the advantage that it adds some "visual contrast" (not sure how to call it), and non-italic text has the advantage that it is a bit easier to read.

I'm not sure which one is better.

That being said, I kind of like the non-italic comments of this theme (this is the first time that I have tried a theme with comments that are not italic).

**Comment by GreasySlug** [comment]
Thank you for your feedback, @d4h0.
The only reason Italic was used was that it was left in place when the template theme was copied.
I removed it because it is basically unused in other editors.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
cc: @jquesada2016

**Pull request merged**
