### PR TITLE
Make arrow keys and page up/down work in insert mode

### PR DESCRIPTION
**Pull request by wojciechkepka**
Closes: #303

### CODE REVIEW

**Comment by cessen** [comment]
I think @archseer had some concerns about this (IIRC, not in principle, just that it might interfere with how something else is implemented right now), so I've added him as reviewer.

But I'm all for this change.  This is actually one of the major blockers for me using Helix as my daily driver.  My muscle memory is just too used to being able to move the cursor at any time, regardless of mode.

**Comment by robinvd** [comment]
I think https://github.com/helix-editor/helix/pull/84 is the same issue

**Comment by cessen** [comment]
Discussed with @archseer, and did some testing to make sure everything works.  It all seems to work without problems.  So, approved!

**Review by cessen — APPROVED** [review]

**Comment by wojciechkepka** [comment]
I probably should have added `home` and `end` while I was at it, I'll send another PR

**Comment by itzmjauz** [comment]
> I probably should have added `home` and `end` while I was at it, I'll send another PR

Please do! :) All #84 needed was for me to close it!

**Comment by wojciechkepka** [comment]
> Please do! :) All #84 needed was for me to close it!

Submitted #314

**Pull request merged**
