### PR TITLE
fixdoc:The path to the configuration file in windows

### PR DESCRIPTION
**Pull request by jumtp**

### CODE REVIEW

**Comment by CptPotato** [comment]
This is incorrect, `%appdata%` points to `<user directory>/AppData/Roaming/`.

**Comment by jumtp** [comment]
> This is incorrect, `%appdata%` points to `<user directory>/AppData/Roaming/`.
When I'm on a company computer. Run 'choco install helix
'Installed. The configuration file path is indeed in Roaming. Because the configuration file has not been generated when I configure rust. The way I configure it is to use the ':config-open' command to save the file. I am now back to my home. I Will try again on my own computer. Will report back when I try it.

**Comment by debajyoti1990** [comment]
> > This is incorrect, `%appdata%` points to `<user directory>/AppData/Roaming/`.
> 
> When I'm on a company computer. Run 'choco install helix
> 'Installed. The configuration file path is indeed in Roaming. Because the configuration file has not been generated when I configure rust. The way I configure it is to use the ':config-open' command to save the file. I am now back to my home. I Will try again on my own computer. Will report back when I try it.
> 

Can confirm the Roaming directory. I use Scoop although.

**Comment by jumtp** [comment]
> This is incorrect, `%appdata%` points to `<user directory>/AppData/Roaming/`.

image

Using scoop also has the same effect. Whether it is win10 or win11

**Comment by CptPotato** [comment]
I don't really see what's the issue here, sorry :confused:.

`%appdata%` refers to `C:/Users/<user name>/AppData/Roaming`, so `%appdata%/helix/config.toml` correctly resolves to `C:/Users/<user name>/AppData/helix/config.toml`.

If you try to print out the config's content with the path you suggest, the file cannot be found (try `type %AppData%\Roaming\helix\config.toml` in CMD).

**Comment by CptPotato** [comment]
> oh. that's my fault .I always thought that %AppData% pointed to the AppData folder.

Yeah, that one is pretty confusing :smile:

**Pull request closed without merging**
