### PR TITLE
Expose line numbers width in config

### PR DESCRIPTION
**Pull request by tonijarjour**
Here is an image of helix running with line numbers limited to 3 digits
image

### CODE REVIEW

**Review by dead10ck — COMMENTED** [review]
What happens when the number of lines is greater than the number of configured digits? Ideally the width should just be adjusted dynamically based on the file in view.

**Comment by kirawi** [comment]
> What happens when the number of lines is greater than the number of configured digits? Ideally the width should just be adjusted dynamically based on the file in view.

https://github.com/helix-editor/helix/pull/3469

**Comment by tonijarjour** [comment]
Where can I find total number of lines in the file? And would you want the width to be on a buffer by buffer basis (might cause jarring transitions when moving between buffers)? If not there would need to be a way to look through number of lines of all open files, and then set the width based on the longest.

**Comment by kirawi** [comment]
#3469 implements that feature already. To get the number of lines in a file, you can do `doc.text().len_lines()`.

**Comment by dgkf** [comment]
Hi, author of #3469 here

This PR looks great! I think my PR would dovetail nicely. The maximum and minimum width aren’t yet configurable in that PR, but it lends itself easily to exposing those as options. I think I even mention this as a “next step”. Take a look if you’d like, I think this could extend the behaviors nicely.

**Pull request closed without merging**
