### PR TITLE
fix: avoid child area overflow on split

### LINKED ISSUE #9877: Panic in vsplit, goto_file (Tree::recalculate)
Set the terminal size, so the number of splits to cause the failure is 
consistent.
```
stty rows 24 cols 80
hx test_document.txt
```

Test Document
----
```
a
b
c
d
e
f
g
h
i
```

Steps to Reproduce
----
1. %   # select_all
1. Alt-s # split_selection_on_newline
1. Ctrl-W F # goto_file
 
Release
----
`thread 'main' panicked at 'index out of bounds: the len is 1920 but the
index is 1920', helix-tui/src/buffer.rs:517:17`

Debug
----
`thread 'main' panicked at 'attempt to subtract with overflow',
helix-view/src/tree.rs:407:50`

Description 
----
The window area height calculation goes negative (overflows) when there are more windows than will fit in the display area.

Related Bugs and PRs
----
#1084 #4642

### PR DESCRIPTION
**Pull request by l4l**
Not really sure it's a proper fix but with the patch original testcase could not be reproduced.

resolves #9877

### CODE REVIEW

**Comment by pascalkuthe** [comment]
> Not really sure it's a proper fix but with the patch original testcase could not be reproduced.

you can reproduce the original crash only if your terminal window is small enough (in the original issue description it describes a really tiny window).

In general the issue is that helix panics if the window is too small to properly render splits. For example as soon as there are atleast three vsplits and you make the window really small helix crashes. Similar problem for hsplits

Not sure if what you are doing here is sufficient but with a reproduction case it should be easy for you to test out

**Comment by l4l** [comment]
I am able to reproduce the original issue. By the pr statement I mean the patch fixes that testcase. Though apparently I've broken some other test, looking into it now.

**Comment by pascalkuthe** [comment]
ah yeah sorry I was still tired and missread that fix does look good now that I looked at the surrounding code

**Comment by pascalkuthe** [comment]
I think the changes to that test are probably fine

**Comment by l4l** [comment]
Though a little bit more about expected behavior. I would expect to the space being split in the equal parts and any roundings then added to the last child.

The first patch does not adhere to that. It actually avoid using the gap in the calculation. And the current one (just pushed) should be fine as the child width calculated from the really used space (e.g container - all the gaps). So fixed the failing test values and added one for the original issue.

**Review by pascalkuthe — APPROVED** [review]
thanks!

**Review by the-mikedavis — APPROVED** [review]

**Pull request merged**
