### PR TITLE
`search_next_impl`: don't panic on invalid regex

### LINKED ISSUE #738: Panic upon pressing `n` while search is set to an invalid regex
### Reproduction steps
1. Press `/` or `s`.
2. Enter an invalid regex, such as `invalid(`.
3. Press `n` or `N`. Helix panics with an error unwrap.

### PR DESCRIPTION
**Pull request by pppKin**
This should resolve #738

### CODE REVIEW

**Comment by archseer** [comment]
While this fixes the issue, we probably shouldn't store searches that are invalid in the register altogether. Prompt closure would need a result value so we're able to signal errors better.

**Comment by pppKin** [comment]
Ah, that makes sense, that would make it easier for everyone else using `RegexPrompt`.

**Comment by pppKin** [comment]
Or perhaps we still store the invalid regex? I know vim does this(perhaps other editors too). It could be useful to use up arrow key to retrieve search histories, modify a bit and search again.

**Comment by archseer** [comment]
Good point, let's merge this 👍🏻

**Comment by pppKin** [comment]
Since #651 will introduce a unified callback in `regex_prompt` which would make this PR a bit cleaner and tidier, let's wait till #651 is finished and merged;)

**Comment by archseer** [comment]
I think this is okay to merge, the callback change won't really affect this PR (register setting was refactored on `master` and happens inside Prompt now)

**Comment by pppKin** [comment]
Oh I see. Should be fine to merge than. If any further improvement is required we'll just open a new issue:)

**Pull request merged**
