### PR TITLE
Add command to set tab display width.

### PR DESCRIPTION
**Pull request by cessen**

### CODE REVIEW

**Comment by cessen** [comment]
Right now I have tab display width as a per-document setting (because it was a per-language setting before).  But it's not clear to me that this makes a lot of sense.  Unlike indentation style, which affects document editing, tab display width is purely a display option.  And I'm having difficulty thinking of realistic situations where we wouldn't want it to simply be an application-wide setting.

Thoughts?

**Comment by kirawi** [comment]
> Right now I have tab display width as a per-document setting (because it was a per-language setting before). But it's not clear to me that this makes a lot of sense. Unlike indentation style, which affects document editing, tab display width is purely a display option. And I'm having difficulty thinking of realistic situations where we wouldn't want it to simply be an application-wide setting.
> 
> (Specifically, I suspect it doesn't even really make sense as a per-language setting, like it was before.)
> 
> Thoughts?

I think it makes most sense for it to be application-wide since I can't think of a reason for otherwise either.

**Comment by archseer** [comment]
I think application-wide is fine, the intent here was for `tab` to expand to the right amount of spaces on "soft tabs", but indent_unit replaced this.

**Comment by cessen** [comment]
Okay, cool.  I'll work on that in this PR the next chance I get.

Thanks!

**Comment by Cons-Cat** [comment]
``.clang-format`` files are supposed to be able to control per-project tab display width in editors. When tabs are used for indentation and spaces are used for alignment, it is possible for trailing multi-line comments to be misaligned.

**Comment by Cons-Cat** [comment]
> I think it makes most sense for it to be application-wide since I can't think of a reason for otherwise either.

If tabs are used mid-line for alignment, then it matters. I'd say this is a bad practice, but people have done it. If tabs are used for leading indentation, and spaces are used for alignment, it also still matters sometimes. This is why tools like a .clang-format file try to tell editors what the visual tab-indentation should be.

**Comment by cessen** [comment]
@Cons-Cat
Below, I'm not actually specifically responding to you, just using something you said as a jump-off point for my own thoughts.  I don't mean to be argumentative. :-)

> If tabs are used mid-line for alignment, then it matters. I'd say doing that is a bad practice, but people have done it.

My general feeling around this is that *because* tabs don't have a universally accepted width, if someone depends on a specific tab width for their code to look correct, that's not just bad practice but actually incorrectly formatted code.  And the fix there isn't on the editor side, but on the code formatting side.

For example, you can imagine a world where the programming community didn't settle on monospace fonts as the norm.  In such a world, if someone depended on a *specific* proportional font for their code formatting to look right, that would be just as incorrect.  And IMO tab width is the same thing: a visual preference, just like font.

Having said all of that, I do acknowledge that there are corner cases.  For example, *semantically* Python defines tabs to be 8 spaces for purposes of parsing and determining code-block boundaries.  And I could see that as an argument for always displaying tabs as 8-wide in Python files, for example.

However, that's also a case where the widely-followed [official Python formatting standard](https://www.python.org/dev/peps/pep-0008/) uses spaces, and where mixing tabs and spaces for block indentation is considered incorrect anyway.  The 8-space tab parsing in Python basically seems to be a throw-away definition, just so the interpreter has *some* way to parse mixed space/tab files, but it's not actually intended to be relied on.  In fact, in Python 3 [it's even an error](https://stackoverflow.com/questions/36063679/python-3-allows-mixing-spaces-and-tabs) to mix tabs and spaces in ways that would make tab width matter.

So it seems to me like basically the whole industry agrees that tab width is undefined and shouldn't be relied on for anything.

**Comment by Omnikar** [comment]
What if you had two different languages, both using tab indentation, but you preferred different visual indentation amounts for either language for the purpose of readability?

**Comment by cessen** [comment]
> What if you had two different languages, both using tab indentation, but you preferred different visual indentation amounts for either language for the purpose of readability?

That seems pretty niche to me.  I mean, I'm sure there are programmers out there that would want such a feature, but I suspect they're rare.  And I don't think it serves any practical purpose.  It's like wanting different line spacing or font size on a per-language basis.

**Comment by pascalkuthe** [comment]
This pr has peen sitting stale for a long time so I am closing this out.

I think this will be valuable to have but instead of special casing I would like to solve this by making it much easier to set and overwrite all config options in #9318 (so other options can benefit similarly).

**Pull request closed without merging**
