### PR TITLE
Add new command to cycle through version control conflict markers

### PR DESCRIPTION
**Pull request by wes-adams**
Issue: #4647

### CODE REVIEW

**Comment by archseer** [comment]
Does this need to be a new keybind? We could structure it as a macro that does something like `/<<<<<<<`

**Comment by wes-adams** [comment]
> Does this need to be a new keybind? We could structure it as a macro that does something like `/<<<<<<<`

good idea. i'll explore that.

**Comment by pascalkuthe** [comment]
With  #4650 we get this sort of for free aswell (at least for git). Git refuses to perform a merge/rebase if the work tree is not clean so conflict markers will be the only change that shows up against HEAD

**Comment by wes-adams** [comment]
it sounds like this merge request might be duplicating work, but i wanted to see it through regardless to learn more about how the project works.

i've tested this feature. it seems to work well. 

https://asciinema.org/a/GXSmICT22D1OOY7VoXNQCsvAt

**Comment by pascalkuthe** [comment]
closing this as stale. Both regex search and `]g` can cover this usecase so I don't see us aadding a dedicated feature.

Thank you for contributing!

**Pull request closed without merging**
