### PR TITLE
`Helix-tutor`: https://rustpad.io/#IXSAHk

### LINKED ISSUE #506: Create something akin to `vimtutor` for Helix
This would introduce the user to modal editing, and to Helix's commands and to its multiple selections. I think it could be opened via something like `hx --tutor`, or opened from within the editor with something like `:tutor`.

### PR DESCRIPTION
**Pull request by python128**
Draft PR as requested by @Omnikar.
This will be a tutor like `vimtutor`.

Resolves #506 

Working [here](https://rustpad.io/#IXSAHk). Please don't make any changes. Suggest changes with `#`. Don't add or remove any lines.

### CODE REVIEW

**Comment by Omnikar** [comment]
> Draft PR as requested by @Omnikar.
> This will be a tutor like `vimtutor`.

Include the issue ID (#506)

**Comment by kirawi** [comment]
For convenience's sake, maybe it would be a good idea to be able to collaboratively work on the actual contents of the tutor file somewhere?

**Comment by python128** [comment]
>For convenience's sake, maybe it would be a good idea to be able to collaboratively work on the actual contents of the tutor file somewhere?
Yes.. But where?

**Comment by python128** [comment]
What about [rustpad](https://github.com/ekzhang/rustpad)
?

**Comment by pickfire** [comment]
hackmd.io is probably the best place for this kind of stuff

**Comment by python128** [comment]
Yes.. But we don't have to sign up for rustpad.. whereas we have to sign up for hackmd

**Comment by kirawi** [comment]
Google Docs could also work.

**Comment by pickfire** [comment]
Google docs is not a good idea since it does not support code blocks nicely, we need to support 80x24 terminals remember? Just use anything is fine as long as it can be easily accessed and we can know the size easily.

**Comment by Omnikar** [comment]
Yeah, I don't think Google Docs would be a good idea.

**Comment by python128** [comment]
I still support another branch..
We can make it only till 80 chars.. And, everyone can also see that.

**Comment by Omnikar** [comment]
How is this for a start? (Mostly copied from Vimtutor)
```
                  _   _                 __    __
                 | | | |         _      \ \  / /
                 | |_| |   ___  | | (_)  \ \/ /
                 |  _  |  / _ \ | |  _    )  (
                 | | | | |  __/ | | | |  / /\ \
                 |_| |_|  \___| |_| |_| /_/  \_\
_________________________________________________________________

 Welcome to the Helix editor! Helix is different from editors
 you might be used to in that it is modal, meaning that it has
 different modes for editing text. The primary modes you will
 use are Normal mode and Insert mode. While in Normal mode, the
 keys you press won't actually type text. Instead, they will
 perform various actions with the text. This allows for more
 efficient editing. This tutor will teach you how you can make
 use of Helix's modal editing features. To begin, hold the j key
 until you reach the first lesson.






=================================================================
=                     BASIC CURSOR MOVEMENT                     =
=================================================================

          ↑
          k       * h is on the left
      ← h   l →   * l is on the right
          j       * j looks like a down arrow
          ↓

 The cursor can be moved using the h, j, k, l keys, as shown
 above. The cursor/arrow keys will also work, but it is faster
 to use the hjkl keys as they are closer to the other keys you
 will be using. Try moving around to get a feel for hjkl.
 Once you're ready, hold j to continue to the next lesson.
```

**Comment by python128** [comment]
Cool. I had this for a plan, but yours seem better..
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  |         _   _      _ _                |
                  |        | | | | ___| (_)_  __          |
                  |        | |_| |/ _ \ | \ \/ /          |
                  |        |  _  |  __/ | |>  <           |
                  |        |_| |_|\___|_|_/_/\_\          |
                  |                                       |
                  |    A post-modern modal text editor.   |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is a tutorial of how to use the Helix editor.
You will need modify the contents of this file as it is interactive.
So, make a copy of this file.

Make sure your Caps Lock key is NOT pressed.
Press `j` enough times so that Lesson 1.1 completely fills your screen(80x24)

================================================================================
                            Lesson 1.1: MOVEMENT

    .---,     You can move around using the arrow keys, which will move the
    | ↑ |     cursor a column/row into the given direction.
.---'---'---,
| ← | ↓ | → | You can try moving around this buffer(file),
`---'---'---`

.---,---,---,---,  As Helix is a Modal(mode-based) editor, we follow its
| h | j | k | l |  tradition of using the h,j,k,l keys to move around.
`---'---'---'---`
  |   |   |   |    This is recommended because it is faster than moving all the
.---,---,---,---,  way till the arrow keys, thus faster.
| ← | ↓ | ↑ | → |
`---'---'---'---`  The mapping is shown in the figure.
                   Easiest way to remember is `h` is on the left, `l` is on the
                   right, `j` looks like a down arrow. From this, you can gather
                   that `k` is up. It takes some time to get used to, but is
                   faster.
Ex 1.1: Try moving around the screen. make sure not to press any other key!
================================================================================
                            Lesson 1.2: MODES

Helix has several modes. But 3 main ones are Normal, Insert and Visual.

    .---,    Normal mode is when all keys are given a certain command. This is
    | i |    the mode which Helix puts you in when you open any file.
    `---'
             You can change to Insert mode by pressing `i`. After you click on
    .---,    `i`, whatever keys you type will be printed on your cursor.
    |esc|    You can use the arrow keys to move around now.
    `---'    To exit from Insert mode(or any mode), press `<esc>` key at the top
             left corner of your keyboard.

    .---,    Visual mode allows you to select certain areas of your text to do
    | v |    some actions on the selected text.
    `---'
             This can be achieved by pressing `v`. This puts you into Visual
             Mode. Now, you can use the arrow keys, or `hjkl` to move around,
             and everything gets selected. Press `<esc>` to return to Normal
             Mode.

Other than these, there are several other modes, or sub-modes of the Normal
Mode.
```

I finished till here.. Need to continue..

**Comment by python128** [comment]
> For convenience's sake, maybe it would be a good idea to be able to collaboratively work on the actual contents of the tutor file somewhere?

How about another room in Element? I suppose all of the people who would like to collaborate on this is available on element. So.. How about it?

**Comment by Omnikar** [comment]
I don't think the line saying to make a copy of the file will be necessary with what I had in mind. The text file would be embedded in the binary, and you could run `hx --tutor` in order to start Helix with the file in a buffer, or perhaps create a copy of the file in the filesystem and open it in Helix, so that it is easier to teach the user `:w`.

**Comment by Omnikar** [comment]
> Cool. I had this for a plan,
I think this tries to introduce concepts to the user too quickly. Also note that because of the line number margin, this doesn't actually fit in an 80 column terminal screen running Helix.

**Pull request closed without merging**
