### PR TITLE
Add instructions for gnome desktop support using the `.desktop` file

### PR DESCRIPTION
**Pull request by David-Else**
This should address: https://github.com/helix-editor/helix/issues/4159

### CODE REVIEW

**Comment by A-Walrus** [comment]
Quick fix, `.desktop` files are not specific to Gnome, they are used by any desktop environment that implements `XDG desktop menu` including Gnome, KDE, and many others.

**Comment by David-Else** [comment]
@A-Walrus Thanks! I did not know that, I have updated the text, does it sound good to you now?

**Review by A-Walrus — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Could you add this note to the `book/src/install.md` page too?

**Comment by David-Else** [comment]
@the-mikedavis I have done as you said, I went for just adding it to the install from source section and missed out the heading as I thought it fitted better there.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks!

**Pull request merged**
