### PR TITLE
Rosé Pine Moon Theme

### PR DESCRIPTION
**Pull request by atahabaki**
This is based on [Rosé Pine theme](https://github.com/helix-editor/helix/blob/master/runtime/themes/rose_pine.toml)...

[Rose Pine Moon palette.](https://rosepinetheme.com/palette)

There's 3 reasons why i've opened this pr:

1) I don't like Rose Pine theme, the Moon version is much more enjoyable
2) I don't know any possible way to configure the theme in user config file...
3) I don't want to modify `/var/lib/helix/runtime/themes/` folder...

And I must say, helix is great. I liked it very much... Thanks

### CODE REVIEW

**Comment by A-Walrus** [comment]
About point 2, in order to add a theme for yourself  add the `rose_pine_moon.toml` to your user theme folder (`~/.config/helix/themes` on linux). You can select it in the config file with `theme = "rose_pine_moon"`

**Comment by erasin** [comment]
theme document : <https://docs.helix-editor.com/themes.html>

**Comment by atahabaki** [comment]
I don't wanna speak so confident, but most of the users are gonna change the theme the way they want to see it. More eye-catching theming docs mean more user, at least i think it is.

**Comment by the-mikedavis** [comment]
The `docs.helix-editor.com` docs code is here: https://github.com/helix-editor/helix/tree/master/book and the website code is here: https://github.com/helix-editor/website if you're interested in expanding them. I don't myself have any ideas for how to make them more noticeable though - we already link to the docs pretty prevasively throughout the project and IMO the theme docs are not very hard to find.

**Comment by atahabaki** [comment]
I've just added that to [wiki](https://github.com/helix-editor/helix/wiki/Themes), so others could find it more easily. I usually choose to look at the wiki if there's one, then the docs. That's my problem, I suppose... Anyway, back to the topic, I think, that the website could show a few photos about themes/theming etc. I'm not a good designer so, I think it would be better if I don't touch the website. Thanks, and I'm really sorry if I've just wasted your time.

**Review by the-mikedavis — APPROVED** [review]
Looks good! I like the mix of purple compared to regular rose_pine 🎨

Could you add a screenshot to the themes wiki?

**Comment by the-mikedavis** [comment]
Ah good call with the theme wiki link to the theme docs! I think it's definitely not unreasonable to visit the wiki first in a project :)

**Pull request merged**
