### PR TITLE
Adds a run-shell-command-no-output command

### PR DESCRIPTION
**Pull request by dariooddenino**
Hi!
This PR adds an additional command to run a shell command ignoring the output.

The command is `:run-shell-command-no-output` (alias `:sh!`).

I'm a bit uncertain about the usage of `ShellBehavior::Ignore` and `Append`, but I didn't want to use a boolean.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Two things:

* I don't think this is an appropriate use of `!` in the alias name. Elsewhere `!` always signals "force" behavior like `:q!`. Here I'm kinda confused by its meaning.
* This should be async - `:run-shell-command-no-output sleep 5` for example blocks the whole editor for a while. Without output I can't think of any reason to block. We should probably not be blocking in `:sh` either.

**Comment by dariooddenino** [comment]
I agree completely! What would a more appropriate name be?
`:sh-no-output` is not that much of a shorter alias.
I think the corresponding bash ways to do so don't translate that well to a short name.

**Comment by the-mikedavis** [comment]
I think it should be `:shush` :P

**Comment by the-mikedavis** [comment]
Looks like this needs a run of `cargo fmt` but otherwise this looks good

**Comment by pascalkuthe** [comment]
Closing because this has gone pretty stale. We would still like to see this but as a flag for sh instead of a new command once we have a command flag parswe

**Pull request closed without merging**
