### PR TITLE
Fix ayu theme cursor issue

### PR DESCRIPTION
**Pull request by enkodr**
Fix issue with with selection where the cursor is in an on a position with no content reported on issue #4754.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Using orange for whitespace ends up being fairly noisy if you `:set whitespace.render all`. In general I think it is not advisable to use the reversed modifier for the cursor because of its interaction with the whitespace scope. Maybe we can avoid this problem by not using the `ui.virtual.whitspace` scope when visible whitespace is disabled?

**Comment by the-mikedavis** [comment]
\cc @philipgiuliani does this look good to you?

**Comment by philipgiuliani** [comment]
As you've mentioned, it doesn't look good with White spaces enabled (which I actually have). Also the documentation has changed from gray to blue, not sure if that in line with the ayu color scheme.

Before:
image

After:
Screenshot 2022-11-16 at 09 15 59

**Comment by enkodr** [comment]
@philipgiuliani I don't know what might be different from my system to yours but it's rendering fine for me.
helix

**Comment by enkodr** [comment]
@philipgiuliani can you check again, please?

**Comment by philipgiuliani** [comment]
Hey @enkodr! It's a little visible now. Personally, I do not like the inverted cursor and the blue documentation. I've just checked out the theme on VIM and VSCode, they are also quite different one from another. All of them use gray documentation and an always-orange cursor.

### This branch
Screenshot 2022-11-18 at 09 28 48

### Helix 22.08.1
Screenshot 2022-11-18 at 09 30 35

### VSCode Ayu Dark
vscode

### VIM Ayu Dark
vim

**Comment by enkodr** [comment]
To be honest, I really liked the inverted color but as there are other preferences from other people I switched back to the orange cursor and will use the inverted colors only to myself.
Regarding the blue color in selection, I also prefer the previous gray but the blue is the standard oficial suggestion as you can see in VS Code.

**Comment by the-mikedavis** [comment]
What about the blue documentation? From the screenshots it looks like that uses dark gray in VSCode

**Comment by enkodr** [comment]
@the-mikedavis I've reverted to the previous colors for both cursor and selection.

**Comment by philipgiuliani** [comment]
In the commit https://github.com/helix-editor/helix/commit/d7136d691a32cb327c358ab9e19bd9d25d61a457 the key `comment.block.documentation` was introduced with the `fg` set to `blue`.

Looking at the vim and VSCode implementations, the documentation style should be set to match the comments.

Not sure if we should change the color to `gray` or remove this key completely, as it seemed to use the `comment` as a default.

```
"comment.block.documentation" = { fg = "gray", modifiers = ["italic"] }
```

**Comment by enkodr** [comment]
You were right @philipgiuliani, I forgot that one. Should be OK now!

**Review by the-mikedavis — APPROVED** [review]

**Pull request merged**
