### PR TITLE
Solarized dark theme

### LINKED ISSUE #759: Feature request: Please add a solarized dark theme
#### Describe your feature request

Please add [solarized dark](https://en.wikipedia.org/wiki/Solarized) theme for helix.

### PR DESCRIPTION
**Pull request by kirawi**
Resolves #759 
Capture

### CODE REVIEW

**Comment by archseer** [comment]
It looks overly highlighted. Were you basing this on another theme file or did you just take the solarized colors?

Look at the examples here, none of the types are brown: https://ethanschoonover.com/solarized/

**Comment by kirawi** [comment]
I based it on a combo of VSCode's and Vim's. The types should be orange, must've made a mistake there.

**Comment by kirawi** [comment]
I'll make it follow Vim's style once I have time.

**Comment by archseer** [comment]
You might be able to use #1010 and simply flip the background color. I think that was one of Solarized features

**Comment by kirawi** [comment]
Done

**Pull request merged**
