### PR TITLE
Add ability to match in next and previous char pairs

### PR DESCRIPTION
**Pull request by thomasschafer**
Adds the ability to match inside/around the next or previous matching character pair: for instance, with the cursor as `█` below:

```rust
█ let x = "bar";
```

typing `]"` would select the contents of the string (i.e. `bar`).

https://github.com/user-attachments/assets/48b38ce5-6e8a-4b8c-8f50-a554f1386b73

This is a modified version of [this PR](https://github.com/helix-editor/helix/pull/11124), based on the discussion there.

Partially resolves:
- https://github.com/helix-editor/helix/issues/1974
- https://github.com/helix-editor/helix/discussions/9895
- https://github.com/helix-editor/helix/discussions/10567

### CODE REVIEW

**Comment by thomasschafer** [comment]
I've realised that I haven't taken into account [this comment](https://github.com/helix-editor/helix/pull/11124/#issuecomment-2223734757) about using a fallback command rather than an on-next-key callback - I'm happy to rewrite this PR using that idea instead if desired

**Comment by the-mikedavis** [comment]
For this PR I was imagining we could start with adding a goto next "any pair" command since that wouldn't need changes to the keymap code or an on-next-key. I'll try to clean up my fallback command changes and submit a PR for that so we can add the versions where you jump to a specified pair too

**Comment by thomasschafer** [comment]
> For this PR I was imagining we could start with adding a goto next "any pair" command since that wouldn't need changes to the keymap code or an on-next-key. I'll try to clean up my fallback command changes and submit a PR for that so we can add the versions where you jump to a specified pair too

Sounds good - I'll update my PR when that's in. Thank you both!

**Comment by thomasschafer** [comment]
Closing in favour of https://github.com/helix-editor/helix/pull/11695

**Pull request closed without merging**
