### PR TITLE
Improve flatwhite theme

### PR DESCRIPTION
**Pull request by krfl**
@AlexanderBrevig 

- Removal of several background colors makes the theme more consistent. 
- Adjusted the readability of a few items.
- Primary selection highlight should be more readable now (#3842).

Screenshot 2022-09-15 at 01 34 22

### CODE REVIEW

**Review by AlexanderBrevig — APPROVED** [review]
Very nice!

**Comment by eulerdisk** [comment]
Whitespaces don't get "selected" when in a selection. Is that normal?
I find it very annoying when you select multiple indented lines you don't see where the selection starts.

**Comment by AlexanderBrevig** [comment]
> Whitespaces don't get "selected" when in a selection. Is that normal? I find it very annoying when you select multiple indented lines you don't see where the selection starts.

Fixed in this version 👍🏻 
image

**Comment by krfl** [comment]
> Whitespaces don't get "selected" when in a selection. Is that normal?
> I find it very annoying when you select multiple indented lines you don't see where the selection starts.

I believe this version of the theme corrects that issue. Here are two screenshots: One showing full lines and one showing selection of whitespace within those lines. The last one also shows the corrected **ui.selection.primary highlighting**. 

Full lines: 
Screenshot 2022-09-15 at 21 28 45

Selecting whitespace within said lines:
Screenshot 2022-09-15 at 21 28 53

**Pull request merged**
