### PR TITLE
Add check for a non-zero value for tab width

### LINKED ISSUE #7094: Add not zero check on tab-width.
If set tab-width to zero, helix will crash (divided by zero). The error might occured from the helix-core/grapheme.rs.
Although it's a bit weird to set tab-width to zero (or even negative numbers), presenting the tab-width as 1 and alerting instead of panic would be better, IMO.

### PR DESCRIPTION
**Pull request by bo1led-owl**
Closes #7094. I think it is weird to set tab width to zero, so I added a custom deserialization function (a small wrapper that checks if the tab width value is zero).

### CODE REVIEW

**Comment by kirawi** [comment]
I think you can use `NonZeroUsize` instead.

**Comment by bo1led-owl** [comment]
Thank you for the advice, I didn't know about this feature. I'll take some time to rewrite it

**Comment by bo1led-owl** [comment]
I've changed it, now it's more clear and also fixes the original issue

**Review by pascalkuthe — COMMENTED** [review]
While you are at it could you limit the value to something reasonable like 16 at most?I am pretty sure the code doesn't correctly account for tab-width larger than 8 and I can't think of any usecase

**Review by pascalkuthe — APPROVED** [review]
Yeah deserialization errors is how we usually handle invalid config. LGTM 👍

**Review by kirawi — APPROVED** [review]

**Pull request merged**
