### PR TITLE
Add statusline element 'file-indexer'

### PR DESCRIPTION
**Pull request by mejo13**
Shows number of open files and index of the one currently viewed.

### CODE REVIEW

**Review by CBenoit — COMMENTED** [review]
Thank you! I think you need to update the documentation as well:
https://github.com/helix-editor/helix/blob/051cd786a43a84912413b526782adffa9698fcd9/book/src/configuration.md?plain=1#L93

**Comment by archseer** [comment]
Hmm I think we could come up with a better name for it. Indexer sounds like a background service that indexes files

**Comment by mejo13** [comment]
Maybe file_counter would be more fitting or do you have an idea?

**Comment by the-mikedavis** [comment]
FileNumber or FileCount would make sense to me. I think we should avoid naming things with [agent noun](https://en.wikipedia.org/wiki/Agent_noun)s (index<i>er</i>, count<i>er</i>) except where there's a lot of precedent for it (picker, receiver, server)

**Comment by mejo13** [comment]
I'd go with FileCount then, if that's ok!?

**Comment by mejo13** [comment]
What is the preferred way to do this? Change the existing pr, which would make the discussion about the name kinda pointless, or make a new one? I'm pretty new to git and github so i'm realy not sure.

**Comment by CBenoit** [comment]
> What is the preferred way to do this? Change the existing pr, which would make the discussion about the name kinda pointless, or make a new one? I'm pretty new to git and github so i'm realy not sure.

Feel free to commit and push additional commits to apply the suggestions. Unless you push force, original commit history will stay available from this PR. That being said, it’s generally okay to just push force if you wish to get the commits merged as it. Maintainers will just squash and merge if necessary, so feel free to proceed as you prefer in this case.

**Comment by mejo13** [comment]
Hey, I was wondering if I have to change something else, request a review or is this better suited as a plugin once the system is in place maybe?

**Comment by pascalkuthe** [comment]
I am going to close this one out as stale since the statusline has been refactored. I think this one is a bit niche and better suited for a plugin. Sorry we didn't give you that feedback sooner and thank you for contributing!

**Pull request closed without merging**
