### PR TITLE
add flexoki theme

### PR DESCRIPTION
**Pull request by ftqo**
Based on [Flexoki](https://stephango.com/flexoki)
CleanShot 2024-03-25 at 12 51 25@2x

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]

**Comment by gj1118** [comment]
@ftqo  it seems that the rulers are not styled with appropriate colors. Should they be styled ?  
I added the `rulers= [80]` in my config, and saw that they were being rendered in black.

**Comment by ftqo** [comment]
@gj1118 Good catch! I'm not a user of rulers, so I didn't notice that. How does it look now?

**Comment by gj1118** [comment]
@ftqo  looks good. Please see the screenshot below 
image


But I am facing another issue. The cursor color is "white" and it is painfully hard to figure out where it is . Are you also seeing the same issue ?

Thanks
Gagan

**Comment by ftqo** [comment]
@gj1118 I'm not seeing what's wrong in the image, could you modify the theme and show me what you would expect instead?

**Comment by ftqo** [comment]
I am unable to replicate this. Could it be related to your terminal or terminal multiplexer? 
CleanShot 2024-03-27 at 13 39 13@2x

**Comment by gj1118** [comment]
> I am unable to replicate this. Could it be related to your terminal or terminal multiplexer? CleanShot 2024-03-27 at 13 39 13@2x

Could be. I am not sure.I will look into it more from my side. Thanks for looking into it. Much appreciated. 

Thanks once again.

**Review by the-mikedavis — APPROVED** [review]

**Comment by atahrijouti** [comment]
off topic, but what WM are you using on macOS?

**Comment by ftqo** [comment]
@atahrijouti yabai

**Review by pascalkuthe — APPROVED** [review]

**Comment by MaxVerevkin** [comment]
The current buffer in the bufferline is not highlighted.

**Pull request merged**
