### PR TITLE
feat(themes): add modus vivendi theme(s)

### PR DESCRIPTION
**Pull request by matoous**
Add themes based on the **dark** variants of the [modus](https://protesilaos.com/emacs/modus-themes) themes (built-in with Emacs). This PR goes in line with https://github.com/helix-editor/helix/pull/8728 and implements modus vivendi (dark) theme; reusing the original color palette.

## [modus_vivendi](https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-theme.el)

Screenshot 2023-11-23 at 18 47 12

## [modus_vivendi_tritanopia](https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-tritanopia-theme.el)

Screenshot 2023-11-23 at 18 48 31

## [modus_vivendi_deuteranopia](https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-deuteranopia-theme.el)

Screenshot 2023-11-23 at 18 47 45

## [modus_vivendi_tinted](https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-tinted-theme.el)

Screenshot 2023-11-23 at 18 48 10

---

See [Modus Themes Pictures](https://protesilaos.com/emacs/modus-themes-pictures) for original.

Potentially more themes could be added in the future: https://protesilaos.com/emacs/ef-themes

### CODE REVIEW

**Comment by atahrijouti** [comment]
Thank you for Prot's great themes. I've been craving Ef-themes and was looking into implementing them, would you happen to know if the structure is the same as modus operandi and vivendi?

**Comment by atahrijouti** [comment]
Thank you for Prot's great themes. I've been craving Ef-themes and was looking into implementing them, would you happen to know if the structure is the same as modus operandi and vivendi?

**Comment by matoous** [comment]
@atahrijouti looking at https://github.com/protesilaos/ef-themes/blob/main/ef-dark-theme.el they should have the same structure. I tried it out here: https://github.com/matoous/helix/tree/md/ef-themes. Result:

Screenshot 2023-11-24 at 09 49 54

It might need some more adjustments. For example `bg-paren-match` highlight is missing but used by the _modus_ themes.

**Comment by atahrijouti** [comment]
That's really cool. Thanks :-)

**Comment by the-mikedavis** [comment]
Could you add the license for these (https://protesilaos.com/emacs/modus-themes#h:b14c3fcb-13dd-4144-9d92-2c58b3ed16d3) following the new notes from https://github.com/helix-editor/helix/pull/8861? That should make it easier to package downstream (fedora for example)

**Comment by matoous** [comment]
@the-mikedavis added, thanks! I missed that.

**Review by the-mikedavis — COMMENTED** [review]
Is it possible to cut down on the duplication by using theme inheritance? It looks like most of the color names are the same so the variants could inherit the base theme and change the palette. See the gruvbox themes for an example

**Comment by matoous** [comment]
@the-mikedavis done, thanks.

**Review by the-mikedavis — DISMISSED** [review]

**Comment by saccarosium** [comment]
I would advocate to define also the highlights for the bufferline:

```diff
"ui.bufferline" = { bg = "bg-tab-bar" }
"ui.bufferline.active" = { bg = "bg-tab-current", fg = "fg-mode-line-active" }
```

**Comment by matoous** [comment]
@saccarosium updated, thanks!

**Review by the-mikedavis — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]

**Pull request merged**
