### PR TITLE
add Vintage theme

### PR DESCRIPTION
**Pull request by rojebd**
Add vintage theme

Screenshots:
**Rust**:
image

**Python**:
image

**C**:
image

### CODE REVIEW

**Comment by the-mikedavis** [comment]
It looks like this and https://github.com/helix-editor/helix/pull/9328 have conflicts since they have the commits that added voxed. You'll need to merge with master and resolve the conflicts

**Comment by zoedsoupe** [comment]
hey there! i really like the vintage theme and also did a manual port to helix some time ago! 

very cool to see it being "officially" ported by the author! any updates here?

**Comment by rojebd** [comment]
Sorry for the inactivity, anyway I passed all CI tests and resolved the merge conflicts on both this and #9328 .

**Comment by zoedsoupe** [comment]
yay! thanks

**Comment by mhsdef** [comment]
@the-mikedavis any chance we can get this merged? I'm interested in this one too

**Review by the-mikedavis — APPROVED** [review]

**Comment by mhsdef** [comment]
Thanks! 🙌

**Comment by zoedsoupe** [comment]
yay!

**Pull request merged**
