### PR TITLE
Use "rosewater" for the jump label color in catppuccin themes

### PR DESCRIPTION
**Pull request by mandx**
Preview of `catppuccin_mocha` displaying `helix-term/src/main.rs`:

image

### CODE REVIEW

**Review by pascalkuthe — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Looks like this conflicts with https://github.com/helix-editor/helix/pull/9980

**Comment by archseer** [comment]
This version looks better, can you rebase and we'll merge? Also, this should probably be propagated to the upstream catppucin repository

**Comment by mandx** [comment]
Rebased and changed the PR title

**Comment by mandx** [comment]
@archseer I added a PR in the upstream catppuccin repo https://github.com/catppuccin/helix/pull/38

**Review by the-mikedavis — APPROVED** [review]

**Review by archseer — APPROVED** [review]

**Pull request merged**
