### PR TITLE
Replace shell_pipe_to with shell_pipe_popup

### PR DESCRIPTION
**Pull request by gustafla**
The new shell_pipe_popup performs a similar function but also allows the user to see the output in an automatically closing popup.

I know this #1682 is similar, but I want selection piping and quick output feedback for running word counts.

### CODE REVIEW

**Comment by gustafla** [comment]
I would otherwise maybe keep the output-ignoring variant of shell_pipe, but I couldn't find a reasonable working key mapping.

**Comment by the-mikedavis** [comment]
I think it'd be good to keep `shell_pipe_to` around. It doesn't necessarily need a default keybinding, but having the command available lets people remap to it if they want, like

```toml
[keys.normal]
"|" = "shell_pipe_to"
```

**Comment by gustafla** [comment]
I agree, my bad, didn't think about that I can just keep it there. Fixed.

**Comment by gustafla** [comment]
Actually, I'd personally find this feature more useful _if_ it _joined_ all selections with spaces or newlines before piping to a single shell command. The current implementation runs n commands for n selections and shows n results in a popup.

**Comment by archseer** [comment]
I'd personally prefer the default keybinding and offer this as an alternative

**Comment by pascalkuthe** [comment]
closing this one out as stale. Thank you for contributing!

**Pull request closed without merging**
