### PR TITLE
Render tab with indent-guides

### LINKED ISSUE #6051: indent-guides double character dilemma
### Steps
Assume: `:set whitespace.render all` or `editor.whitespace.render = "all"`

- open hx
- enter a new line
- press 4 spaces and write some word
- press enter to go to next line (this inserts the indent with "tab" lol)
- enable indent-guides by `:set indent-guides.render true`

**See that:**
- the indent guide vertical line is drawn
- but that seems to be drawn _in place of_ the whitespace character
- so, only 3 (not 4) spaces are now shown in first line
- and the tab indentation character is effectively eaten up entirely

### Screenrecord

https://user-images.githubusercontent.com/19423063/219942649-89e6ce5c-3cfb-42ca-bcb8-5477f0168c8f.mp4

### External References

From VSCodium:
It shows both the indentation guide, and whitespace character.

image

### Versions
- hx: 22.12 (96ff64a8)
- os: win 10 20h2

### PR DESCRIPTION
**Pull request by erasin**
- fix #6051
- fix when set `tab-width=0` ,will get panic `thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', helix-core/src/graphemes.rs:20:26`

set indent guides render false

before:

after:

> this has set `tabpad = "·"`

### CODE REVIEW

**Comment by pascalkuthe** [comment]
This needs a smarter implementation. While tabs are most commonly used for indentation they can be used randomly in the document and with the implementation here tabs would look off in that case. Furthermore, helix allows mixing tabs and spaces for indentation (or setting a different indentation setting). In that case indent guides can dynamically appear *anywhere* inside the tab.

**Comment by erasin** [comment]
Thanks for the review

I am modifying it to only handle indent guides when rendering，This will does not affect other render.

**Comment by pascalkuthe** [comment]
Ah I see I missed that I guess I was tired. This should cover most things but I am kind  of concerned about just comparing the symbol here. The tab whitespace symbol is not necessarily unique. Consider the following: tabs are marked with .... And spaces with . but nbso with ,

Now if you have
`.,,,` (so a space followed by nbsp) then your implementation would do
`|.,,`.  

Also querying the buffer like this has some overhead we should add a check whether we are even rendering tabs around this so this doesn't affect people that don't use whitespace chars. It should also only work if there is a  distinct pad tab character as this workaround isn't needed otherwise. This can still lead to visual artifacts but I guess those are unlikely enough to ignore

**Comment by erasin** [comment]
Sorry, I shouldn't be querying characters.

In this commit, I append `indent_tab` , when grapheme is in `indent_area`, it will be replace tab  like `virtual_tab`.

**Comment by erasin** [comment]
I have tried several ways, indent_area processing does not satisfy the condition, must recalculate the rendered line content.

**Pull request closed without merging**
