### PR TITLE
add symbol picker

### PR DESCRIPTION
**Pull request by robinvd**
use the lsp document_symbol request

### CODE REVIEW

**Comment by pickfire** [comment]
Can you update the book for this?

**Comment by pickfire** [comment]
Ah, interesting but this isn't what I thought of, it only uses symbol from the current document. I thought I can jump to symbols in other files as well. I think we should do another submode for this later like `space c J`.

**Comment by robinvd** [comment]
Ah for workspace symbol there is a separate lsp command, but for that you give a search query and it only returns relevant results.
I wanted to try that too. But thats not how the current picker works

**Review by archseer — APPROVED** [review]
This looks good! There's some client capabilities in initialize as well but it looks like we can skip them for the most part. Are you looking at adding work symbols too? If so, we can probably use what kak-lsp is using: https://github.com/kak-lsp/kak-lsp/blob/23c5f3c450c1e42856c7ff15af4234d566ee5b11/src/general.rs#L47

**Comment by robinvd** [comment]
adding workspace symbols looks like a nice challenge. But im currently not looking into it.

**Comment by archseer** [comment]
No worries, I'll tackle it :)

**Comment by robinvd** [comment]
I just saw that the query string is optional, so i could simply use the existing logic for now.

**Comment by archseer** [comment]
I have an implementation locally, the issue is that most LSPs will return a subset because it would be quite a lot of data. We'd need to support the `partial_result`s and also re-query as the search term is entered (perhaps even easier is a `:workspace-symbols <query>` command.

**Pull request merged**
