### PR TITLE
Solarized theme: fix popup colors, adjust menu

### PR DESCRIPTION
**Pull request by dead10ck**
Add mentioned by @rypervenche in [this comment](https://github.com/helix-editor/helix/pull/1105#issuecomment-971723023), the pop-up colors don't work well in the dark theme, and aren't great in the light theme either. I fixed the dark theme here. Apologies for the screenshots, I did this on my phone because I don't have my laptop with me at the moment.

Screenshot_20211117-224820

And I also changed the foreground color in the menu to the base color.

Screenshot_20211117-224839

I tried using the same colors in the light theme, but that did not work very well, as most of the text is violet or white, which doesn't contrast enough with the light background.

Screenshot_20211117-225512

I wasn't able to find a good background color at all that worked with the theme of the docs content, and I'm not even sure what that theme is, whether it's markdown or something special. So instead, I opted to just use a dark background for popups. If anyone can find a better combo here, feel free to suggest it.

Screenshot_20211117-224726

Screenshot_20211117-224901

### CODE REVIEW

**Comment by archseer** [comment]
> I did this on my phone

I think it's really cool to see helix running on a phone :) 


> what that theme is, whether it's markdown or something special.

Yeah, it's rendered as markdown and I actually didn't realize this, but the colors were hardcoded. https://github.com/helix-editor/helix/blob/27ceeb83bb055c90670cb9a4d8fdab7d5c742b2f/helix-term/src/ui/markdown.rs#L64-L66

I'll patch this and report back with the new scope names

**Comment by archseer** [comment]
I made a quick patch that uses theme colors: https://github.com/helix-editor/helix/commit/9dcccb45bbee30011a44fcabaae94a5f6589ff7b

In the future I'll also introduce `markup.heading`, `markup.raw.block` etc.

**Comment by dead10ck** [comment]
> I made a quick patch that uses theme colors: [9dcccb4](https://github.com/helix-editor/helix/commit/9dcccb45bbee30011a44fcabaae94a5f6589ff7b)
> 
> In the future I'll also introduce `markup.heading`, `markup.raw.block` etc.

Ahh, that makes sense. I'll try it out again and report back later tonight.

**Comment by dead10ck** [comment]
@archseer that patch fixed the problem. It looks much better on both light and dark palettes!

Screenshot_20211118-232729

Screenshot_20211118-232910

One tiny thing I'm noticing is it looks like the horizontal break near the top still looks like it may be hard coded. This is a huge improvement though.

**Comment by dead10ck** [comment]
I added another change that fixes the hardcoded color of the horizontal rule. Screenshots of the fix:

Screenshot_20211119-003516

Screenshot_20211119-003458

**Comment by pickfire** [comment]
Wow, I can't imagine you changing the code from the phone.

Also, cc @cossonleo who previously worked on this. I am surprised there are chinese comments in the theme.

**Comment by kirawi** [comment]
Added it to the wiki.

**Pull request merged**
