### PR TITLE
Remove apply_transaction helper

### PR DESCRIPTION
**Pull request by pickfire**
Not sure why there is this TODO, so I cleaned it up.

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
Ah I forgot about this TODO: we removed the need for the `apply_transaction` helper a while ago but didn't want to complicate the diff. I think we're safe to remove it now 👍

There's one more reference of it in the integration test suite helpers to be removed

**Comment by pickfire** [comment]
> There's one more reference of it in the integration test suite helpers to be removed

I can't seemed to find it with `rg apply_transaction`.

**Comment by the-mikedavis** [comment]
Ah actually looks like there's two of them

https://github.com/helix-editor/helix/blob/edd0ba7f19c662555128c4b112faed0120d91197/helix-term/tests/test/helpers.rs#L133 and https://github.com/helix-editor/helix/blob/edd0ba7f19c662555128c4b112faed0120d91197/helix-term/tests/test/helpers.rs#L318

**Comment by pickfire** [comment]
Oh, looks like I accidentally added `test/` to my git ignore, no wonder.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks for cleaning this up!

**Pull request merged**
