### PR TITLE
[WIP] feat: notifications

### PR DESCRIPTION
**Pull request by matoous**
Adds support for notifications in similar vein as https://github.com/rcarriga/nvim-notify.

- [x] display notifications
- [x] hide old notifications
- [ ] add command to show picker with all notifications
- [ ] hook into the event loop to hide the notification when the time comes instead of when the ui is re-rendered
- [ ] allow notifications to be disabled

### CODE REVIEW

**Comment by matoous** [comment]
@archseer one design question please: I need to re-render the editor when the notification times out, how you you approach this? Ideally, I would like to be able to do this from within `Notifications.add()` method so the caller doesn't have to care, would that somehow be possible?

**Comment by archseer** [comment]
Yeah this type of UI complexity was purposely left out for now 😅

You could expand the idle timer implementation to support more timers that emit events. Another option would be to spawn a new job that sleeps for N ms then looks up the component via the compositor and does something.

**Comment by archseer** [comment]
What's the usecase for these though?

**Comment by matoous** [comment]
> What's the usecase for these though?

The usecase would be to hide the notification after for example 5s. Right now it stays visible until you do something that forces that editor to re-render. I don't think is blocker per-se but would be nice to eventually have this functionality. What do you think? Maybe I can fix the rest and we can leave this for future.

**Comment by archseer** [comment]
Oh, I mean what would you use notifications for? For build failures etc I think it's best to open a dismissable popup (nothing worse than an error that disappears before you manage to read it)

I also think it's unlikely you'd have so many notifications open that it would require a picker

**Comment by matoous** [comment]
The main idea were LSP messages and lsp status but it can also be kept as it is and we can put those into the command entry line, in which case I don't think I have a use case for this as of now.

**Comment by matoous** [comment]
No time to work on this one and also there isn't clear use case, closing.

**Pull request closed without merging**
