### PR TITLE
languages: add protobuf language servers

### PR DESCRIPTION
**Pull request by jzelinskie**

### CODE REVIEW

**Review by gabydd — CHANGES_REQUESTED** [review]
Please run `cargo xtask docgen` to add the changes to the language support docs

**Comment by gabydd** [comment]
The language server here https://github.com/pbkit/pbkit/ apparently also supports completion haven't tested it out though so the other language server might be better

**Comment by jzelinskie** [comment]
I added pbkit -- neither projects are extremely mature, but i'll take limited functionality over none!
bufls is an experiment, but backed by a company that sells protobuf tool.  If I had to place my bet somewhere, it'd be there.

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Comment by softkot** [comment]
https://github.com/hudbrog/protobuf-lsp is more usable 

```
go install github.com/hudbrog/protobuf-lsp@latest && ln -s protobuf-lsp bufls 
```

gives better UX

**Pull request merged**
