### PR TITLE
Ruby TextObjects and more file extensions

### PR DESCRIPTION
**Pull request by danillos**
It includes Ruby TextObjects and more Ruby file extensions

_It is my first time working with Tree-Sitter, improvements are welcome._

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
This is a bit of a nit but lines 3 and 24 are indented by one space. Can we use two for the sake of consistency?

**Comment by the-mikedavis** [comment]
What do you think about a class selector for singleton classes? (I'm not sure if I have the right terminology here.)

https://github.com/appsignal/appsignal-ruby/blob/f97cc5a7b3c8713929faf705cdf2266a7583c8d4/lib/appsignal.rb#L18

```ruby
module Foo
  class << self
    # ..
  end
end
```

I think a query like

```scm
(singleton_class
  value: (_)
  (_)+ @class.inside) @class.around
```

might cover it.

**Comment by danillos** [comment]
> What do you think about a class selector for singleton classes? (I'm not sure if I have the right terminology here.)
> 
> [appsignal/appsignal-ruby@`f97cc5a`/lib/appsignal.rb#L18](https://github.com/appsignal/appsignal-ruby/blob/f97cc5a7b3c8713929faf705cdf2266a7583c8d4/lib/appsignal.rb#L18)
> 
> ```ruby
> module Foo
>   class << self
>     # ..
>   end
> end
> ```
> 
> I think a query like
> 
> ```scheme
> (singleton_class
>   value: (_)
>   (_)+ @class.inside) @class.around
> ```
> 
> might cover it.

Nice, I added it too.

**Comment by danillos** [comment]
I did tests for Classes using these variations:

```ruby
class Bar
  # ...
end

class Bar < Foo
  # ...
end

class Bar < Foo::Test
  # ...
end

class Bar::Foo
  # ...
end

class Bar::Foo < Foo
  # ...
end

class Bar::Foo < Foo::Test
  # ...
end

module Bar
  class Foo
    # ...
  end
end

module Bar
  class Foo < Bar
    # ...
  end
end

class Bar
  class Foo
    # ...
  end
  
  def test
    # ...
  end
end

module Foo
  class << self
    # ...
  end
end

Class.new do
  # ...
end
```


But I had to do this test manually. @the-mikedavis do you know if we have Unit Tests for it? I pretty sure that a future update on https://github.com/tree-sitter/tree-sitter-ruby could break it.

**Comment by the-mikedavis** [comment]
There isn't currently test infrastructure for queries although I think it's a good idea.

Highlights queries could use the existing tree-sitter testing syntax and textobjects might be able to use some recent testing utilities around selections within Helix.

We pin the grammar repository versions in `languages.toml` so if the repo updates it won't break queries here until we update the version. Updating the grammars (manually) can be a bit error prone (e.g. #2153) but generally Helix fails loudly if the queries are invalid so it's somewhat easy to detect. But a testing framework would make that a lot easier to be confident about.

**Review by the-mikedavis — APPROVED** [review]
Thanks for working on this, these look great!

**Comment by stuarth** [comment]
thanks for this @danillos!

**Pull request merged**
