### PR TITLE
Read file

### PR DESCRIPTION
**Pull request by zephaniahong**
#3796 

Implemented a read command that emulates the vim feature of reading the contents of a file and pasting after the cursor

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/pull/3966

**Comment by Omnikar** [comment]
That makes three separate PRs all trying to close #3796…

**Comment by zephaniahong** [comment]
My bad! I only realized there were 2 existing PRs after submitting a PR myself. Should I close this PR?

**Comment by the-mikedavis** [comment]
Yeah let's focus on the others

**Pull request closed without merging**
