### PR TITLE
Add GitHub themes

### PR DESCRIPTION
**Pull request by OwOSwordsman**
A GitHub color theme based on the VSCode GitHub theme. The variants are based on the Primer Primitive Colors. Templates were created for the Light and Dark variants to closely match the VSCode ones. The others were generated based on the two templates.
Screen Shot 2022-12-31 at 5 33 15 PM
Screen Shot 2022-12-31 at 5 31 57 PM

### CODE REVIEW

**Comment by archseer** [comment]
Are just the palettes different? If so you could use inherits to only override the palette, and declare the scopes once

**Comment by archseer** [comment]
Great work on this by the way! I really wanted these themes included :)

**Comment by OwOSwordsman** [comment]
> Are just the palettes different? If so you could use inherits to only override the palette, and declare the scopes once

Oh right, theme inheritance was just added. I am not sure if the built-in themes should be using the inherit feature or not tho.

**Comment by pascalkuthe** [comment]
> > Are just the palettes different? If so you could use inherits to only override the palette, and declare the scopes once
> 
> Oh right, theme inheritance was just added. I am not sure if the built-in themes should be using the inherit feature or not though.

Other builtin themes (like `tokio`, `autumn` and `hex`) already do and it's usually preferable to duplication

**Review by archseer — APPROVED** [review]
Thanks!

**Pull request merged**
