### PR TITLE
Added 2 new themes

### PR DESCRIPTION
**Pull request by PORTALSURFER**

### CODE REVIEW

**Comment by s0LA1337** [comment]
some screenshots would be nice

**Comment by PORTALSURFER** [comment]
> some screenshots would be nice

hex_steel
image

hex_toxic
image

**Comment by PORTALSURFER** [comment]
> some screenshots would be nice

hex_steel 
image

hex_toxic
image

**Comment by the-mikedavis** [comment]
Are these two only different in their palettes? It might be a good opportunity to use the new theme inheritance feature from #3067 (https://docs.helix-editor.com/master/themes.html#inheritance)

**Comment by PORTALSURFER** [comment]
> Are these two only different in their palettes? It might be a good opportunity to use the new theme inheritance feature from #3067 (https://docs.helix-editor.com/master/themes.html#inheritance)

https://github.com/helix-editor/helix/pull/4367/commits/d70b743c7da58eae38cd17e765d0645bfef1e47b

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks!

Could you add these screenshots to the themes wiki? https://github.com/helix-editor/helix/wiki/Themes

**Pull request merged**
