### PR TITLE
adds: rose_pine_dawn.toml colorscheme

### PR DESCRIPTION
**Pull request by chunghha**
To add rose_pine_dawn color scheme based from rose_pine.toml in the repo.  So I give credits to @raygervais for his effort.

### CODE REVIEW

**Comment by chunghha** [comment]
Also, in the other commit, added ui.statusline.inactive colors for the rose_pine.

**Comment by chunghha** [comment]
Even though I don't think the lint error is related to my commits, @archseer would you check and review for merging?

**Comment by WindSoilder** [comment]
The linter error is fixed this morning, you can try to rebase or merge.

**Comment by chunghha** [comment]
rebased master and pushed. Please trigger the workflow.

**Comment by archseer** [comment]
Looks good, thanks!

**Pull request merged**
