### PR TITLE
add Chinese documentation link

### PR DESCRIPTION
**Pull request by zjp-CN**

### CODE REVIEW

**Comment by the-mikedavis** [comment]
I'm hesitant to link to non-official documentation from the official docs

**Comment by A-Walrus** [comment]
> I'm hesitant to link to non-official documentation from the official docs

IMO it's fine as long as it as **clearly labeled as unofficial.**

**Comment by zjp-CN** [comment]
We can put it in the wiki.

**Comment by the-mikedavis** [comment]
I think adding it to the main wiki page would be good 👍 https://github.com/helix-editor/helix/wiki

**Comment by kirawi** [comment]
We could also host the docs in the repo.

**Comment by zjp-CN** [comment]
> We could also host the docs in the repo.

Thanks for the idea. But I think it will bring drawbacks more then benefits.

I've updated the Wiki. So I'm gonna close this PR. Thanks all.

**Pull request closed without merging**
