### PR TITLE
allow disabling menu update

### PR DESCRIPTION
**Pull request by oberblastmeister**
Allow configuring menu_updating of `c-n` and `c-p`.

### CODE REVIEW

**Comment by archseer** [comment]
What's the rationale for this? I think those are the built-in default keys for both kakoune and vim.

**Comment by archseer** [comment]
Ah, I didn't read fully, this is so that text doesn't auto insert when you select it?

**Comment by oberblastmeister** [comment]
Yeah this is so you don't autoinsert when selecting

**Comment by pickfire** [comment]
Can you please give an example why this fix is needed? What use case do you have?

**Comment by oberblastmeister** [comment]
It is just nicer to me visually and inserting text causes the menu to move unnecessarily. Editors like vscode also don't insert text by default. If we also support snippet at some point the text inserted might not be correct as it hasn't been applied by the sinppet. It makes sense to me to have this option for configuration.

**Comment by archseer** [comment]
VSCode doesn't, but this is common behavior in terminal editors (vim, kakoune). I think we can make it configurable but it needs a better name than `menu-update = false`.

(I fixed the moving completion window in https://github.com/helix-editor/helix/commit/12ea3888c59aec8e6d0b4dcf6a3ad92a84edaca7)

**Comment by archseer** [comment]
Dropping this for now, but might add support for this in the future

**Pull request closed without merging**
