### PR TITLE
chore: update scala tree-sitter grammar

### PR DESCRIPTION
**Pull request by zetashift**
Update to a new Scala tree-sitter grammar revision, because the current one lags behind by quite a bit:

https://github.com/tree-sitter/tree-sitter-scala/commits/master

### CODE REVIEW

**Comment by archseer** [comment]
Is there also any highlight query changes? It's usually not enough to just bump the grammar

**Comment by the-mikedavis** [comment]
It's a little hard to tell looking at the diff ([compare](https://github.com/tree-sitter/tree-sitter-scala/compare/f6bbf35de41653b409ca9a3537a154f2b095ef64...23d21310fe4ab4b3273e7a6810e781224a3e7fe1)) but it looks like all of the changes are structural or to unnamed rules so we may not need to update the highlights queries.

We could add the new locals queries though for better highlighting: https://github.com/tree-sitter/tree-sitter-scala/commits/e37d21701bd03d5bb27f5e2e8339ce6afc419784

**Comment by zetashift** [comment]
> We could add the new locals queries though for better highlighting: https://github.com/tree-sitter/tree-sitter-scala/commits/e37d21701bd03d5bb27f5e2e8339ce6afc419784

What are local queries (sorry not a tree-sitter expert).

**Comment by the-mikedavis** [comment]
Ah sorry, I mixed up the permalink. I think we should be able to use these out-of-the-box https://github.com/tree-sitter/tree-sitter-scala/blob/798ec789401de159e0c07ae170c8ae6dfbbfd94c/queries/scala/locals.scm

copying them to runtime/queries/scala/locals.scm. (Also see https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables)

**Comment by zetashift** [comment]
> Ah sorry, I mixed up the permalink. I think we should be able to use these out-of-the-box https://github.com/tree-sitter/tree-sitter-scala/blob/798ec789401de159e0c07ae170c8ae6dfbbfd94c/queries/scala/locals.scm
> 
> copying them to runtime/queries/scala/locals.scm. (Also see https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables)

Oooh, I see, thank you!

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Pull request merged**
