### PR TITLE
chore: add "ui.virtual.jump-label" to serika-dark theme

### PR DESCRIPTION
**Pull request by nihil2501**
Screenshot 2024-10-17 at 3 20 44 PM

### CODE REVIEW

**Comment by the-mikedavis** [comment]
\cc @VuiMuich what do you think?

**Comment by the-mikedavis** [comment]
This should probably be added to `serika-light.toml` as well

**Comment by VuiMuich** [comment]
Agree to both, 👍🏼

_Also reminds me, that I wanted to do a slight overhaul and optimize a few small things in both serika themes. _

**Comment by VuiMuich** [comment]
@the-mikedavis lets merge this and I give my best to open a pr for the general overhaul in the next two weeks and add this feature also to the light theme.

**Review by the-mikedavis — APPROVED** [review]

**Pull request merged**
