### PR TITLE
Improve Ruby TextObjects

### PR DESCRIPTION
**Pull request by danillos**
This PR Refactor current TextObjects and improves it adding:

- Adds Singleton Methods
- Adds Module
- Adds `@parameter.around`

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
It looks like most of these nodes have `body` fields which can be used to capture the `@textobject.inside` parts more accurately. For example:

```scm
(singleton_method
  body: (_)? @function.inside) @function.around
```

should cover the new `singleton_method` patterns.

(`:tree-sitter-subtree` currently misrepresents these body fields for some nodes, https://github.com/helix-editor/helix/pull/4606)

**Comment by danillos** [comment]
Hi @the-mikedavis, I was testing using the Tree from https://tree-sitter.github.io/tree-sitter/playground that prints:

```
program [0, 0] - [3, 0]
  singleton_method [0, 0] - [2, 3]
    object: self [0, 4] - [0, 8]
    name: identifier [0, 9] - [0, 13]
    identifier [1, 2] - [1, 6]
```

for the code

```ruby
def self.test
  test
end
```

Do we have a better way to see the Tree?

**Comment by the-mikedavis** [comment]
The ruby parser on the tree-sitter website is out of date. You can use tree-sitter-cli and to get the exact results that helix sees you can clone tree-sitter-ruby and check out the revision listed in `languages.toml` and run `tree-sitter parse` against that. I see:

```
(program [2, 0] - [8, 0]
  (singleton_method [2, 0] - [4, 3]
    object: (self [2, 4] - [2, 8])
    name: (identifier [2, 9] - [2, 20])
    body: (body_statement [3, 2] - [3, 6]
      (true [3, 2] - [3, 6]))))
```

**Comment by danillos** [comment]
@the-mikedavis thank you. I did a small refactor on the current TextObjects based on the Tree printed by `tree-sitter parse` and improved it adding some missing cases.

**Pull request merged**
