### PR TITLE
AWK support

### PR DESCRIPTION
**Pull request by ath3**
awk_example

### CODE REVIEW

**Comment by ath3** [comment]
Good idea, should we also support shell scripts calling nawk and gawk specifically?

```scm
; runtime/queries/bash/injections.scm
(command
  name: (command_name (word) @_command)
  argument: (raw_string) @injection.content
 (#match? @_command "^[gn]?awk$")
 (#set! injection.language "awk"))
```

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thank you!

**Comment by David-Else** [comment]
@ath3 could you add install instructions to https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers ?

**Comment by ath3** [comment]
> @ath3 could you add install instructions to https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers ?

done!

**Comment by David-Else** [comment]
@ath3 Nice one :)

**Pull request merged**
