### PR TITLE
Update Typescript, TSX and Svelte grammar, to latest tag

### PR DESCRIPTION
**Pull request by jeppech**
Support for the `satisfies`-keyword in Typescript
Support for the `@const`-expression in Svelte templates

### CODE REVIEW

**Comment by jeppech** [comment]
I just saw that the `tsx`-grammar, uses the typescript tree sitter repo too. So I've updated that as well.

**Comment by archseer** [comment]
Did you also check for any query differences or new nodes we can now highlight? It's usually not enough to just bump the grammar

**Comment by jeppech** [comment]
@archseer Oh sorry, I did not know, I'll take a closer look at the changes, to the different repos.

**Comment by jeppech** [comment]
I've added the `satisfies`-keyword in highlights.scm for typescript, and an alternative css injection, for svelte templates, that the svelte tree-sitter repo mentioned.

I'm unsure, where I can find any new node that the repos may have added.

**Review by the-mikedavis — APPROVED** [review]

**Comment by erasin** [comment]
@jeppech need append file [indents.scm](https://github.com/Himujjal/tree-sitter-svelte/blob/master/queries/indents.scm) for svelte.

```
[
  (element)
  (if_statement)
  (each_statement)
  (await_statement)
  (script_element)
  (style_element)
] @indent

[
  (end_tag)
  (else_statement)
  (if_end_expr)
  (each_end_expr)
  (await_end_expr)
  ">"
  "/>"
] @outdent
```

**Pull request merged**
