### PR TITLE
add tree-sitter-comment

### LINKED ISSUE #1164: highlight TODO, FIXME and XXX in comments
`(n)vim` highlights these keywords in comments: TODO, FIXME and XXX. It's quite useful for spotting places to work on in source code.
image

### PR DESCRIPTION
**Pull request by the-mikedavis**
closes #1164 
builds on #1170

### CODE REVIEW

**Comment by sudormrfbin** [comment]
Is there any way to inject this without manually specifying it in the corresponding `injections.scm` for every language ?

**Comment by the-mikedavis** [comment]
I think you have to do it manually for all :/

We could try enabling a 'hidden' `injections.scm` like

```scm
((comment) @injection.content
 (#set! injection.language "comment"))
```

but that might break or not work on languages that have different names for comment nodes (like languages that have different block and line comments)

**Comment by sudormrfbin** [comment]
Seems like `nvim-treesitter` also manually specifies it for every single file :/

**Comment by pickfire** [comment]
Oh, I thought modification to the code base is required.

**Comment by archseer** [comment]
Thanks! 🎉

**Comment by bestouff** [comment]
Hi,  
I just updated `hx` and tried to edit a rust file with a `// TODO comment` but it's not highlighted. Is there something I need to do ?

**Comment by pickfire** [comment]
@bestouff Which language did you use? The TODO support needs to be added to the language.

**Comment by archseer** [comment]
Make sure you `cargo clean` and `rm runtime/grammars/*` to ensure the new grammars are built.

**Comment by bestouff** [comment]
> Make sure you `cargo clean` and `rm runtime/grammars/*` to ensure the new grammars are built.

That was it. Thanks to all of you !

**Pull request merged**
