### PR TITLE
Add `no_op` command

### PR DESCRIPTION
**Pull request by Omnikar**

### CODE REVIEW

**Comment by pickfire** [comment]
What is your use case for this?

Looks like a code only change but not sure if the user is able to find this out, does not seem discoverable to me.

**Comment by sudormrfbin** [comment]
> Looks like a code only change but not sure if the user is able to find this out, does not seem discoverable to me.

Maybe a mention in https://docs.helix-editor.com/remapping.html ?

**Comment by Omnikar** [comment]
> What is your use case for this?

It's for if a user wanted to explicitly make a key do nothing.

> Maybe a mention in https://docs.helix-editor.com/remapping.html ?

Right, I should do that.

**Comment by Omnikar** [comment]
Something we'd probably want to do is hide keys bound to `no_op` from these windows.

image

**Review by archseer — APPROVED** [review]

**Pull request merged**
