### PR TITLE
Sonokai

### PR DESCRIPTION
**Pull request by p4ymak**
Added Sublime Text theme Sonokai.

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
Hi! Looking good! 
Can you please add 
```toml
"ui.cursorline.primary" = { bg = "something" }
```
To the theme so that https://github.com/helix-editor/helix/pull/3234 lints OK and that I can see the cursorline I expect to see when using the theme?

Of course, replace `something` to whatever you think is nice (I liked `bg1` and `bg2`).

image

**Review by AlexanderBrevig — CHANGES_REQUESTED** [review]
Please add key; `"ui.cursorline.primary"` ref comment.

**Review by AlexanderBrevig — APPROVED** [review]
Thanks!

**Comment by p4ymak** [comment]
added "ui.cursorline.primary"

**Review by the-mikedavis — APPROVED** [review]

**Comment by p4ymak** [comment]
> Could you add a screenshot of this to the themes wiki? https://github.com/helix-editor/helix/wiki/Themes

Done!

**Pull request merged**
