### PR TITLE
Resume last picker

### PR DESCRIPTION
**Pull request by pickfire**
Inspired by space ' in doom emacs.

### CODE REVIEW

**Comment by cessen** [comment]
I'm a little confused.  What does this PR do?  It's not clear to me from the description what the intended behavior/feature is.

**Comment by pickfire** [comment]
output-opt

**Comment by cessen** [comment]
Ah, thanks!  Interesting.  Seems like it could be useful when browsing through multiple files with a shared prefix/postfix, looking for something.  Is that the main intended use-case?  Or is there something else as well?

**Comment by sudormrfbin** [comment]
It would be easy to navigate between list of references, implementations, etc from the lsp (something of an ad hoc quickfix list)

**Comment by pickfire** [comment]
> It would be easy to navigate between list of references, implementations, etc from the lsp (something of an ad hoc quickfix list)

Yup.

> Ah, thanks! Interesting. Seems like it could be useful when browsing through multiple files with a shared prefix/postfix, looking for something. Is that the main intended use-case? Or is there something else as well?

Besides that, this will be very useful when you are browsing a codebase that is not familiar and you want to ripgrep stuff stuff but you don't want to keep typing the same keyword in the picker (we don't have this text search picker yet).

Last time I use to keep `space / keyword down` `space / keyword down down` `space / keyword down down down` many times, then after I found this I just `space ' down` without having to keep typing the keyword.

**Review by archseer — APPROVED** [review]

**Pull request merged**
