### PR TITLE
feat(helix-view): view debug output on windows

### PR DESCRIPTION
**Pull request by axdank**
`Tmux` is not available on windows, so it raises an error and closes the helix editor with a warning pointing to handlers/dap.

debug_panic

Therefore I decided to add a piece of code so that a new terminal can be opened, either with Windows Terminal or Conhost ( both running `cmd.exe` inside ).

In case of having windows terminal ( `wt.exe` ), it is executed in it.

In case of not having it, it is executed in ( `conhost.exe` ).

Example ( `conhost.exe` ):

image

image

Example ( `wt.exe` ):

image

### CODE REVIEW

**Review by mmdbalkhi — APPROVED** [review]

**Comment by axdank** [comment]
@the-mikedavis Sorry, I wanted to check if this code can be applied. Previously I created a pull request (of the same thing) but I didn't realize that the code was formatted and generated unnecessary changes in git (+311, -311), so I closed it and recreated it correctly.

**Comment by the-mikedavis** [comment]
This looks good to me but let's wait for a maintainer with more rust experience to review 👍

**Comment by archseer** [comment]
The idea is to have this configurable via an `editor.terminal = { cmd = "foo", args = ["bar"] }` type setting with some reasonable defaults similar to how the clipboard works. Would you be prepared to work on that in this PR? If not I can merge this as is for now and open a separate tracking issue

**Comment by axdank** [comment]
@archseer If there is a possibility to merge this momentarily, it would be the best, because my knowledge in rust is still very basic 😞.

**Pull request merged**
