### PR TITLE
feat(editor): add config for search wrap_around 

### PR DESCRIPTION
**Pull request by matoous**
Adds configuration for search wrap around and moves search config into separate config struct.

Fixes: https://github.com/helix-editor/helix/issues/1489

### CODE REVIEW

**Comment by archseer** [comment]
You can probably just disable the lint on that specific method

**Review by dead10ck — APPROVED** [review]
Looks good to me 👍

**Review by pickfire — APPROVED** [review]
I think it should be good but it might break existing users using the same config. I think maybe we want to release this as another minor update rather than patch update, otherwise we risk breaking users config, or maybe we need to have some kind of deprecation mechanism. But now I guess still too new for that.

**Comment by matoous** [comment]
> You can probably just disable the lint on that specific method

Disabled for `search_impl`.

**Comment by archseer** [comment]
Thanks for working on this! 🎉

**Pull request merged**
