### PR TITLE
Add shift-backspace keybind alias for backspace

### PR DESCRIPTION
**Pull request by lesleyrs**
Not sure if this PR works but would be nice to have, no real reason not to I guess?

### CODE REVIEW

**Comment by the-mikedavis** [comment]
By default the terminal can't tell the difference between backspace and S-backspace: all of these commands already work with S-backspace. Terminals that implement the progressive keyboard enhancement protocol can tell the difference but we need to detect and enable that from within Helix. See the [`enable-keycode-disambiguation` branch](https://github.com/helix-editor/helix/tree/enable-keycode-disambiguation). We could merge this change into that branch.

**Comment by lesleyrs** [comment]
Ok sounds good, I'm not sure how to have 2 separate helix installs work so I can't test if I did it correctly. And I don't wanna mess with my current install.

**Comment by gabydd** [comment]
Just FYI enable key code disambiguation was just merged also you can do ``cargo build`` or ``cargo run`` to test it out

**Comment by the-mikedavis** [comment]
#4887 handles the new keys but doesn't enable the disambiguation flags. See https://github.com/helix-editor/helix/pull/4887#issuecomment-1328093166

**Comment by kirawi** [comment]
Misclick.

**Comment by lesleyrs** [comment]
Ok I just did a cargo run and it seems to work as intended in both editor and prompt 👍. Thx for the help guys!

**Pull request merged**
