### PR TITLE
Add .svn as workspace root marker

### LINKED ISSUE #11403: SVN workspace support
I'm working on Fortran projects under SVN (I know, right?). The fortls server works a charm, however, with Helix I run in to the issue of workspace root detection. Helix doesn't seem to treat `.svn` folders as workspace-root markers and so by default it uses my home directory (which in turn causes fortls to time out because it's too much stuff).

After a lot of tinkering and looking at verbose logs, I was able to get it to work as desired in one of two ways:
1. Adding an empty `.helix` or `.git` directory to the workspace root. I seem to recall reading about this in the documentation a while ago, but I can't seem to find it any more. Is there a docs page that states exactly how the workspace root is determined by Helix? It would be helpful for this sort of debugging.
2. Using the `roots` option in the Fortran language in `languages.toml`: `roots = [".fortls.json", ".svn"]`. Works, but is limited to the Fortran language.

Neither of these solutions is ideal. It requires extra configuration steps either per language or per repository. As far as I can tell, this is not configurable in a generic way at the moment. Personally, the real strength of Helix over, eg, nvim, is that it "just works" most of the time.

I propose adding `.svn` as a criterion for workspace root detection. I would also be willing to provide a MR if given some pointers as to where in the codebase this happens.

### PR DESCRIPTION
**Pull request by oworope**
Fixes #11403

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]

**Comment by oworope** [comment]
How do i pass lint check? do i need to `cargo fmt`?

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Yep see here: https://github.com/helix-editor/helix/blob/518425e0552483fa40c6e6ab4d0ea7358e0101be/.github/workflows/build.yml#L81-L90

formatting, clippy and a docs check need to pass

**Comment by oworope** [comment]
Thanks!

**Comment by seanbone** [comment]
This makes me happy. Thanks @oworope!

**Pull request merged**
