### PR TITLE
Update languages.toml - add nixd

### LINKED ISSUE #10734: lsp: support nixd
[`nixd`](https://github.com/nix-community/nixd) is a Nix LSP that appears better maintained than the presently included `nil`.
it would be nice if support for this were added to helix.

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
Closes #10734

### CODE REVIEW

**Comment by the-mikedavis** [comment]
To fix the docs CI you can run `cargo xtask docgen` and commit the changes

**Comment by KiaraGrouwstra** [comment]
@the-mikedavis thanks, i pushed an update now :)

**Review by the-mikedavis — DISMISSED** [review]

**Comment by KiaraGrouwstra** [comment]
i've pushed an edit prioritizing `nil`.

**Comment by inclyc** [comment]
> nil seems to require less configuration, see https://github.com/oxalica/nil/issues/111

That's outdated somehow, there are some massive rewriting landed in nixd just a few months ago, features should work out of box.

**Comment by KiaraGrouwstra** [comment]
should i put nixd on top again?

**Comment by inclyc** [comment]
> should i put nixd on top again?

Disclaimer: I'm author of nixd.

I would like to recommend you put it on the top, but I think the should be decided by users.

**Comment by cgahr** [comment]
> > should i put nixd on top again?
> 
> Disclaimer: I'm author of nixd.
> 
> I would like to recommend you put it on the top, but I think the should be decided by users.

Could you elaborate on the difference between nixd and nil?

**Comment by darinkishore** [comment]
I've found nixd catches more errors when working on my nix config, i tried nil for a week, switched to nixd and haven't looked back. anecdotal ofc, but that + more recent commits on nixd has caused me to use it as my default nix LSP.

**Review by the-mikedavis — APPROVED** [review]

**Comment by keinsell** [comment]
It would not be better to add `--inlay-hints` argument as default? Default configuraiton of `typescript-language-server` inclues inlay hints for example.

**Comment by KiaraGrouwstra** [comment]
@keinsell aren't those enabled [by default](https://github.com/nix-community/nixd/commit/e1f6f717af7b14ff826f268646375f7964f477a6#diff-d6d22da07a28fb14232d0605d9b1fa98b03c3bc166686072bf379b20e11f2d8dR23)?

**Comment by VuiMuich** [comment]
Sorry to come with this, last minute, but wouldn't it make sense to also add `formatter = { command = "nixfmt" }` as well, while at it?

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/11001

**Comment by keinsell** [comment]
> @keinsell aren't those enabled [by default](https://github.com/nix-community/nixd/commit/e1f6f717af7b14ff826f268646375f7964f477a6#diff-d6d22da07a28fb14232d0605d9b1fa98b03c3bc166686072bf379b20e11f2d8dR23)?

Just checked in editor, yeah they seem to be provided by default - my bad.

**Pull request merged**
