### PR TITLE
prepare for window resizing

### PR DESCRIPTION
**Pull request by QiBaobin**

### CODE REVIEW

**Comment by pickfire** [comment]
What are you trying to achieve for this pull request?

**Comment by QiBaobin** [comment]
I am thinking of supporting window resizing,  #1176 

But want to confirm if this kind of  change is on correct direction?

**Comment by archseer** [comment]
I would avoid floats and use usizes, maybe something similar to flexbox flex property?

flex:1
flex:2

^ the total space gets divided into 3 units and the second one gets 2/3rds

**Comment by SuperKenVery** [comment]
Hi, why is this closed? I'm actually longing for the resize feature and I think this is a very good implementation...

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/pull/2704 ?

**Pull request closed without merging**
