### PR TITLE
Changed Selection Yank Message

### PR DESCRIPTION
**Pull request by ngraham20**
Per #2615, the message for yanking to the secondary clipboard when selecting text is clarified.

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks!

**Comment by ngraham20** [comment]
> Thanks!

Of course! Happy to make the change, I had to dig a bit to figure out why the clipboard wasn't working myself, so it was personal haha

**Comment by ngraham20** [comment]
As a side thing, would it be possible to label this PR "hacktoberfest-accepted" so I can get event credit for it as well?

**Comment by the-mikedavis** [comment]
Can do 👍

**Comment by ngraham20** [comment]
Beautiful, thank you!!

**Pull request merged**
