### PR TITLE
Implement window/showMessageRequest [applies PR 5492 to latest]

### PR DESCRIPTION
**Pull request by smortime**
Applies @ayoub-benali's changes from https://github.com/helix-editor/helix/pull/5492 onto the latest master. 

Tried and failed miserably to rebase their branch since it's 1+ year stale. Can try rebasing it again later. This unblocked me with using Metals LSP so opening this incase helps others in same situation. 

All credit to Ayoub for actually implementing this and making Metals usable!

https://github.com/helix-editor/helix/issues/4699

### CODE REVIEW

**Comment by smortime** [comment]
I can't sanely rebase https://github.com/helix-editor/helix/pull/5492 :/

**Comment by kirawi** [comment]
@the-mikedavis What's the reason this is marked as "needs discussion"?

**Comment by the-mikedavis** [comment]
#5492's issue (and this PR by extension) is just UI. I don't think Menu or Picker properly fit the bill and I've been meaning to experiment with a new Component that is more central (i.e. captures the center of the screen like a picker) but can fit all of the info we need for an element like showMessageRequest. The information I feel is missing is context on the message - the screenshot from #5492 is a good example: it's hard to tell why the picker has suddenly appeared on the screen and what the options mean. From TUI programs I'm familiar with I think there is inspiration to be gleaned from `lazygit` which also has situation-specific pop-ups that need some user interaction to resolve. Maybe all we need is a textbox above a menu or picker-like component with context.

This PR in particular can probably be closed though as it's had unresolved conflicts for quite some time - a new implementation can most likely reuse the LSP parts from #5492 directly but will need new work on the UI part.

I definitely want to see showMessageRequest added, I'm just not totally satisfied on the UI part yet. It's not a widely used feature on the language server side but it has been an outstanding incompatibility for quite some time so I'd love to see it added sooner rather than later.

**Comment by abrassel** [comment]
Just found this while trying to get metals working. Any chance I can contribute? :)

**Pull request closed without merging**
