### PR TITLE
Support Typst 0.11

### PR DESCRIPTION
**Pull request by Idobenhamo**
Update the tree sitter to support Typst 0.11 and changed the lsp to [Tinymist](https://github.com/Myriad-Dreamin/tinymist)

### CODE REVIEW

**Comment by keirlawson** [comment]
Why switch language server?

**Comment by Idobenhamo** [comment]
It has more active development and more features...

**Comment by keirlawson** [comment]
Tinymist looks to have existed for about a month, it might be a good idea to "wait and see" for a little while longer before concluding it is better maintained

**Comment by Idobenhamo** [comment]
So what about adding them both?

**Comment by Idobenhamo** [comment]
@the-mikedavis Is that ok? Just added both of the lsp's.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Yep having both should be fine, whichever one you have installed will be used

**Pull request merged**
