### PR TITLE
Dead code

### PR DESCRIPTION
**Pull request by Borwe**
The for loop is unecassry, as the condition is already taken care of in the while loop.

### CODE REVIEW

**Comment by archseer** [comment]
Needs a rebase with master

**Comment by Borwe** [comment]
Okay, rebased.

**Review by the-mikedavis — CHANGES_REQUESTED** [review]
This block isn't dead: it handles any files after the "--" in the argv: https://github.com/helix-editor/helix/blob/f4d96b2ca335977ea9b9031e35994b7f15f05c25/helix-term/src/args.rs#L31

**Comment by Borwe** [comment]
> This block isn't dead: it handles any files after the "--" in the argv:
> 
> https://github.com/helix-editor/helix/blob/f4d96b2ca335977ea9b9031e35994b7f15f05c25/helix-term/src/args.rs#L31

Ooh, didn't know that, when is it used though? I think we can remove it too?

**Comment by Borwe** [comment]
Nevermind, I see my error in logic. Closing.

**Pull request closed without merging**
