### PR TITLE
Appen\Paste-After\Shell-Pile-After EOL special case

### PR DESCRIPTION
**Pull request by andreytkachenko**
In normal mode when cursor on the new line symbol (\n) actions like append or paste after inserts data after new line to the next line. But it is annoying, you have to remember to get cursor back by 1 char and then paste. The PR fixes that behavior by checking if there is '\n' on the end of the range, if it is just subtract 1.

### CODE REVIEW

**Review by the-mikedavis — CHANGES_REQUESTED** [review]
The current behavior is deliberate. Vim treats newlines with special handling like this but kakoune and helix do not - newlines are treated like any other character.

**Comment by andreytkachenko** [comment]
I understand that this behavior is deliberate, I am not suggesting completely exclude newline symbol from the line, I am just suggesting to add some special cases for paste, append and shell-pipe append.

**Comment by andreytkachenko** [comment]
@archseer @sudormrfbin @pickfire you opinions guys? Should we just close PR in favor `newline = "all"` config option as solution?

**Comment by pickfire** [comment]
I don't have opinion on this but @cessen would probably have opinion, but I think the current approach should be correct.

**Comment by sudormrfbin** [comment]
I agree with @the-mikedavis here; since we handle newline like any other character the current behavior makes sense. Also setting `editor.whitespace.render.newline = "all"` should help with any confusion regarding whether the cursor is on a newline. On a tangent, you don't have to move the cursor back one character either if you want to paste on the current line (when cursor is on newline), pressing `P` instead of `p` should do the trick.

**Comment by pickfire** [comment]
> pressing P instead of p should do the trick

The issue with that is that both methods requires you to delete an empty newline. It's either one of

- `Pjd`
- `pggd`

**Pull request closed without merging**
