### PR TITLE
Add jump-label style for dark high contrast

### PR DESCRIPTION
**Pull request by GreasySlug**
- ~~base16_transparent~~

~~[gw_transparent](https://github.com/helix-editor/helix/assets/106496265/6abf10a3-b085-415f-be87-1855f2b9874b)~~

- dark_high_contrast

gw_dhc

### CODE REVIEW

**Comment by pascalkuthe** [comment]
Pretty sure these were already added (for base16 themes in  #10076, not sure about dark high contrast).

I prefer the fg color + bold coloring. Setting the bg color for highlights is not ideal in general

**Comment by GreasySlug** [comment]
Sorry for my late reply

> I prefer the fg color + bold coloring. Setting the bg color for highlights is not ideal in general

That is make sence

I'll think about it some more

**Comment by GreasySlug** [comment]
- base16_transparent
gw_transparent
- dark_high_contrast
gw_dhc

**Comment by GreasySlug** [comment]
base16_transparent already has a jump_label added

**Pull request merged**
