### PR TITLE
Add MacPorts as installation option for MacOS

### PR DESCRIPTION
**Pull request by jgelens**

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
Could you add macports to the table of contents at the top of the page as well?

**Comment by Agilan989** [comment]
Yup
***@***.***

**Review by the-mikedavis — APPROVED** [review]

**Comment by jgelens** [comment]
It needs to be added to Repology as well later.

**Review by pascalkuthe — APPROVED** [review]
It already shows up in repology, that's automatic

**Pull request merged**
