### PR TITLE
lint: autumn

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
passes linter from https://github.com/helix-editor/helix/pull/3234
image
image

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
@getreu please sanity check my choices :)

**Comment by AlexanderBrevig** [comment]
@crodjer @jbaa please sanity check my choices :)

**Review by getreu — CHANGES_REQUESTED** [review]
I do not understand what your PR actually visually changes. Or, is it for completeness?
Anyway, shouldn't be both files changed the same way?

**Comment by AlexanderBrevig** [comment]
> I do not understand what your PR actually visually changes. Or, is it for completeness?
> Anyway, shouldn't be both files changed the same way?

Cursorline is an upcoming feature, it's for completeness. The extra fg for the one theme is an oversight. I'll remove it later today 👍 thanks

**Comment by AlexanderBrevig** [comment]
Moved to bulk PR https://github.com/helix-editor/helix/pull/3587

**Comment by AlexanderBrevig** [comment]
Moved to bulk PR https://github.com/helix-editor/helix/pull/3587

**Comment by getreu** [comment]
Thank you for explaining. Changes are OK for me.

**Pull request closed without merging**
