### PR TITLE
Add an editor option for keeping completion placeholders.

### PR DESCRIPTION
**Pull request by gibbz00**
I keep finding myself having to retype them again.

Possibly relevant commit: https://github.com/helix-editor/helix/commit/ba24cfe9125eda97346e3ceee42686fb9f46046f

### CODE REVIEW

**Comment by pascalkuthe** [comment]
see https://github.com/helix-editor/helix/issues/7045

**Comment by gibbz00** [comment]
I did see some PR/issues regarding completion handling, and I do understand that support isn't entirely there yet. Ideally, I would love to be able to have a keybinding that it inserts the virtual placeholder text before "tabbing" to the next placeholder.

Right now, however; all placeholders are removed as soon as the first argument is being filled in, which kind of defeats the purpose of having them in the first place.

It is also a lot more efficient for me to retype the arguments that don't have variables of the same name already in scope, than to retype those that do. This was the primary motivation for this PR.

https://github.com/helix-editor/helix/assets/31696304/a9e3b21f-68aa-4b22-9bf3-eae0e05f73df

Now, I don't want to say that one way is better than the other, tut this gives users at the very least a choice until the underlying completion system is fledged out.

**Comment by AloeareV** [comment]
I am enthusiastically in favor if this feature!

**Comment by So1aric** [comment]
Yep, this is also helpful when writing C code. For example, when you define a prototype in a header file and go to a C file to implement it, Clang will give a snippet which is pretty helpful. However, Helix will then delete it 😢

**Comment by gibbz00** [comment]
@pascalkuthe what's the status on this PR?

**Comment by the-mikedavis** [comment]
#9801 is the proper fix for this

**Pull request closed without merging**
