### PR TITLE
Increment string

### PR DESCRIPTION
**Pull request by flinguenheld**
Hello,
I firstly just wanted to be able to use Ctrl-a / Ctrl-x on true/false however it should be cool to use it with more words.

[Increment_strings.webm](https://github.com/user-attachments/assets/f74f6fec-64c4-4b65-a2ee-5ee4e7b82e9c)

If you're interested in, take a look on the list, we could add more words.
I'm also open to all critics about the code itself ^^

Thank you

### CODE REVIEW

**Comment by david-crespo** [comment]
You can do this in userspace as a script with `:pipe`. It seems very unlikely to me that the maintainers will go for this.

**Comment by flinguenheld** [comment]
The list of words could be added by the user in the config.toml for example.

**Comment by flinguenheld** [comment]
I would have checked, sorry

**Comment by eevleevs** [comment]
> Until this is possible via plugins/scripting it should be possible to do the same thing with the pipe commands

For anyone wanting to use a pipe, I made https://github.com/eevleevs/increment

**Pull request closed without merging**
