### PR TITLE
Added ability to define dotfiles to be exposed in file picker

### LINKED ISSUE #5724: global dot and hidden files/directories include for file picker
Currently, the `hidden` key under the `editor.file-picker` section for configuration is defaulted to `true`, which enables hiding dot and hidden files from being shown in the file picker. But, this can be inconvenient at times. There are dot and hidden files/directories that can be important to a project (such as `.gitattributes`, `.gitignore`, `.github/`, etc) that should be included in the file picker by default. This would prevent one from having to set `hidden` to `false` and have all dot and hidden files shown, which might not be desired by the individual. The common and important ones, such as the ones listed above, should be included in the file picker out of the box. If an individual wants to opt out of hiding other dot and hidden files/directories, there could be a key `include-hidden`, under the `editor.file-picker` section, that takes a list of other dot and hidden files/directories to include in the file picker.

### PR DESCRIPTION
**Pull request by KenCox94**
completed to resolve #5724

### CODE REVIEW

**Comment by penguincoder** [comment]
Can you help me understand how to use this? I am personally pretty vested in this feature since I am doing an absolute ton of work with Github Actions right now. I have cloned your branch, then built and installed it. I have tried leaving the default configuration in place and putting both `include-hidden = [".github"]` and `include-hidden = ["github"]`.

When I open the file picker `<space>f` and then try and type `.github/workflows`, by the time I hit the `/` the file picker is completely empty. Oddly enough, `.gitignore` works okay, but not `.github`.

Am I missing something?

**Comment by KenCox94** [comment]
> Can you help me understand how to use this? I am personally pretty vested in this feature since I am doing an absolute ton of work with Github Actions right now. I have cloned your branch, then built and installed it. I have tried leaving the default configuration in place and putting both `include-hidden = [".github"]` and `include-hidden = ["github"]`.
> 
> 
> 
> When I open the file picker `<space>f` and then try and type `.github/workflows`, by the time I hit the `/` the file picker is completely empty. Oddly enough, `.gitignore` works okay, but not `.github`.
> 
> 
> 
> Am I missing something?

Let me take a look at this today and I'll get back with you tomorrow! Just letting you know I did see it.

**Comment by KenCox94** [comment]
> Can you help me understand how to use this? I am personally pretty vested in this feature since I am doing an absolute ton of work with Github Actions right now. I have cloned your branch, then built and installed it. I have tried leaving the default configuration in place and putting both `include-hidden = [".github"]` and `include-hidden = ["github"]`.
> 
> When I open the file picker `<space>f` and then try and type `.github/workflows`, by the time I hit the `/` the file picker is completely empty. Oddly enough, `.gitignore` works okay, but not `.github`.
> 
> Am I missing something?

Apologies for the delay. Use this [link](https://github.com/KenCox94/helix/tree/KenCox94-hidden-picker-edit). I actually began work on another issue so I started from a clean branch and that's why this is not working. I am under the assumption you went to my repository and cloned the `master` branch. Let me know if this resolves your issue fi.

**Comment by KenCox94** [comment]
> Can you help me understand how to use this? I am personally pretty vested in this feature since I am doing an absolute ton of work with Github Actions right now. I have cloned your branch, then built and installed it. I have tried leaving the default configuration in place and putting both `include-hidden = [".github"]` and `include-hidden = ["github"]`.
> 
> When I open the file picker `<space>f` and then try and type `.github/workflows`, by the time I hit the `/` the file picker is completely empty. Oddly enough, `.gitignore` works okay, but not `.github`.
> 
> Am I missing something?

I think this may be because .github is a directory and .gitignore, .gitattributes are files? Let me investigate this further and Ill try and have a fix for this by this weekend!

**Comment by penguincoder** [comment]
That is the ticket! It's working very well now, thanks!

I guess it's not a typical workflow to have a hidden directory that you need to edit a lot of files in.

**Comment by penguincoder** [comment]
Has there been any progress on this? Do you just need to have it reviewed? I have been using this for the past month(s) and it's been working great. Thanks again!

**Comment by KenCox94** [comment]
@penguincoder 
as far as I know. Im just waiting on a review. It's saying my merge is blocked due to that.

**Comment by pascalkuthe** [comment]
This is covered by https://github.com/helix-editor/helix/issues/7423 (with negative ignore patterns both globally and pre workspace). I don't see us adding anything more purpose-built than that

**Comment by pascalkuthe** [comment]
closing as  #8099 was merged

**Pull request closed without merging**
