### PR TITLE
Adds `keymap-open` command

### PR DESCRIPTION
**Pull request by e-ivkov**
Relates to #2573

### CODE REVIEW

**Comment by e-ivkov** [comment]
Used a symlink instead of file copy as suggested in [matrix](https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$L7bLSLNpDw-_hJfMKyB1244Ts1lCDl7tj3odn40sopA?via=matrix.org&via=mozilla.org&via=tchncs.de) though I am not sure if this will work well on Windows for example

**Comment by dead10ck** [comment]
This isn't really going to work at all. This is is a symlink relative to the runtime directory, which does not contain the book markdown source. We don't distribute the book markdown files with the text editor. Symlinks won't work for anyone who doesn't have a local copy of the source code and their runtime dir linked to the source tree.

**Comment by e-ivkov** [comment]
@dead10ck do you think the keymap file should be copied into runtime then? I can add also a CI check to make sure the files stay the same

**Comment by the-mikedavis** [comment]
For unix it would probably be best if it were hard-linked but I don't know if Windows supports hard links at all.

**Comment by dead10ck** [comment]
Links aren't really a solution either way; we have to think about this as if the source code is not available on the target system, because for many users, that is the case.

I'm not really sure what the best solution is. It seems like a packaging issue. Perhaps we could plan to distribute the book markdown files under `~/.local/share/helix/book` or something? And the command could look there. This would push the onus of making this work onto packagers, but that's probably unadvisable either way. Whether it was the book or some other form, sooner or later, we'll have to distribute help files in some way.

**Comment by e-ivkov** [comment]
> Perhaps we could plan to distribute the book markdown files under ~/.local/share/helix/book or something? And the command could look there. This would push the onus of making this work onto packagers, but that's probably unavoidable either way. Whether it was the book or some other form, sooner or later, we'll have to distribute help files in some way.

So how would you suggest to proceed with this PR? Close it for now until book packaging is done? Btw is there an issue for it?

**Comment by the-mikedavis** [comment]
Since the packaging isn't very straightforward and I don't see much reason to include the rest of the book in the release, I'd say let's scrap this approach in favor of improving the command picker (<kbd>Space</kbd><kbd>?</kbd>). The workaround for this of downloading the `keymap.md` file and binding something to `:open` it seems acceptable in the meantime

**Comment by e-ivkov** [comment]
Is somebody working on improving the `Space ?`?

**Pull request closed without merging**
