### PR TITLE
Add Doom's Acario dark theme.

### PR DESCRIPTION
**Pull request by Rinnray**
This theme is ported from [acario themes](https://github.com/doomemacs/themes/blob/master/themes/doom-acario-dark-theme.el) from Doom Emacs.

I've however only focused on the dark one as that's the one I'm using.

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
Nice!

I ran it through https://github.com/helix-editor/helix/pull/3234 and got 
```json
"acario":[
	"ui.cursorline"
]
```

It may be argued that `ui.statusline.normal|insert|select` should be sepecified as well, in order to adhere to the `editor.color-modes` setting?

**Comment by Rinnray** [comment]
I didn't see anything different when I defined those, but I added them!
Statusline is the same color either way.

**Comment by AlexanderBrevig** [comment]
> I didn't see anything different when I defined those, but I added them! Statusline is the same color either way.

Both of them are behind setting. You must enable color-modes and cursorline (I just realized this may not be available if you use an official release. Thanks for adding anyway)

**Review by the-mikedavis — APPROVED** [review]
Looks nice, thanks! 🎨

Could you add a screenshot to the themes wiki? https://github.com/helix-editor/helix/wiki/Themes

**Comment by Rinnray** [comment]
> Looks nice, thanks! art
> 
> Could you add a screenshot to the themes wiki? https://github.com/helix-editor/helix/wiki/Themes

Will do!

**Pull request merged**
