### PR TITLE
Disable Tree-Sitter on Big Files

### PR DESCRIPTION
**Pull request by kirawi**
It's a draft while I move it into a global config instead of `languages.toml`.

```toml
[global]
max_file_size = 5000000 # 5 mb
```

### CODE REVIEW

**Comment by kirawi** [comment]
On another note, is there a better name other than `max_file_size`?

**Comment by pickfire** [comment]
I think it would be better if we could prompt to disable rather than just disable it.

**Comment by archseer** [comment]
> On another note, is there a better name other than `max_file_size`?

I think we can just have a hard-coded internal limit

**Comment by kirawi** [comment]
Should probably be redone, I'm not interested in continuing this PR at this time, but I may take another shot at it in the future if nobody else does it.

**Pull request closed without merging**
