### PR TITLE
Add preview for scratch buffers in buffer picker

### LINKED ISSUE #3420: No content preview for unsaved scratch buffers in buffer picker
Hi, 

There's no content preview for unsaved scratch buffers in buffer picker. Is this a bug?

Screen Shot 2022-08-14 at 00 55 52

### PR DESCRIPTION
**Pull request by A-Walrus**
Resolves #3420.

The diff is quite big mostly because a big block in `picker.rs` is now indented more...

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
I think this approach makes sense. I'm hung up on the new enum's name though - would it be too on-the-nose to call it a `File` instead of `PathOrId`?

**Comment by A-Walrus** [comment]
> would it be too on-the-nose to call it a `File` instead of `PathOrId`?

I feel like `File` is less descriptive, and also more confusing as people might assume it is `std::fs::File` or `tokio::fs::File`.

**Review by the-mikedavis — APPROVED** [review]

**Comment by archseer** [comment]
Can you resolve the conflict here? Looks good to merge otherwise

**Comment by the-mikedavis** [comment]
Thanks for working on this!

**Pull request merged**
