### PR TITLE
Fix cursor position bugs related to o and O

### LINKED ISSUE #127: Using `O` on the first line does not move the cursor
If you're on the first line in a file and press `O`, it inserts the newline correctly above the current one, but does not move the cursor accordingly.

### PR DESCRIPTION
**Pull request by sudormrfbin**
- `O` at the beginning of file didn't move cursor
- `o` and `O` messed up cursor position with multiple cursors

Fixes #127

### CODE REVIEW

**Review by pickfire — COMMENTED** [review]
Nice, I was trying this out the other day but I didn't know you need to do `change_by_selection`. Seemed bad that we need to keep a state around. The bug is fixed but the behavior seemed to be different from kakoune and vim. `10Oa` now does not write 10 a but instead just one a 10 lines above, I think this is a bit surprising.

**Comment by sudormrfbin** [comment]
> Nice, I was trying this out the other day but I didn't know you need to do change_by_selection

The problem doesn't stem from using `change` instead of `change_by_selection` though, the issue is with properly calculating how much an edit needs to be offset by prior edits in the same transaction. As @archseer said on Matrix it'd be cleaner of we could handle this in `change_by_selection` itself.

> 10Oa now does not write 10 a but instead just one a 10 lines above, I think this is a bit surprising.

It's deviant from vim and kakoune yeah but do we really need to keep that behavior in helix ? It feels at odds with the multiple cursor philosophy (this commit didn't change this behavior though, it previously did not write 10 a's either).

**Comment by archseer** [comment]
> 10Oa now does not write 10 a but instead just one a 10 lines above, I think this is a bit surprising.

This was already a problem before this PR, the implementation simply doesn't do that yet.

> do we really need to keep that behavior in helix ?

I do want this, 10o should make 10 lines and place a cursor on each. It's an easy way to start writing multiple lines with multiple cursors.

**Comment by sudormrfbin** [comment]
How should counts before `i`, `I`, etc be handled ? In vim `10i<text>Esc` inserts `<text>` on the same line 10 times, which isn't very useful. IMO something more useful would be putting cursors on the current line and the next 9 lines in the same column. Same for `10I` but in the beginning of each line.

**Comment by archseer** [comment]
I think it's OK if counts on `i` are just ignored.

Do you want to do the change for `10o` here, or should that be a follow-up?

**Comment by sudormrfbin** [comment]
I'll add it as a separate commit in this PR.

**Review by archseer — APPROVED** [review]
Verified on local. Thanks!

**Pull request merged**
