### PR TITLE
Add command to open recently closed files

### PR DESCRIPTION
**Pull request by thomasschafer**
This PR adds a command `open-recent` (with alias `or`) to open the most recently closed file. A maximum of 100 files are maintained in the `last_opened_docs` state to minimise memory usage.

https://github.com/helix-editor/helix/assets/54135831/111af104-31d9-4141-8669-094bd4021c78

### CODE REVIEW

**Comment by pascalkuthe** [comment]
This seems like an odd feature to me. Buffer in helix are not like tabs in vs-code where you would frequently need to close them to keep organized. Closing a buffer is fairly rare and usually a deliberate "I  am not interested in this anymore" action. So a list of those closed buffers wouldn't be too useful.

What I think would be useful would be a "recently opened files" picker that keeps state on disk between multiple helix invocations but that is an orthogonal feature.

**Comment by thomasschafer** [comment]
> This seems like an odd feature to me. Buffer in helix are not like tabs in vs-code where you would frequently need to close them to keep organized. Closing a buffer is fairly rare and usually a deliberate "I am not interested in this anymore" action. So a list of those closed buffers wouldn't be too useful.
> 
> What I think would be useful would be a "recently opened files" picker that keeps state on disk between multiple helix invocations but that is an orthogonal feature.

That makes sense when you have the bufferline disabled, but when it is enabled surely most people want to delete buffers to keep the bufferline tidy, especially given that the bufferline gets truncated once sufficiently many are open? Is there a better way of having a manageable bufferline?

I like the idea of a recently opened files picker - I can look at building that if you think it would be something that could get merged.

**Comment by pascalkuthe** [comment]
In retrospect it would have been better to not merge the buffer-line because we don't want to support a vscode tablike workflow where the buffers are closed or reordered to make the bufferline tidy. Helix buffers are like vim and kakoune buffers and generally just data in the background and not something that should be visible or kept tidy. I would recommend just leaving buffer open and using the buffer pickr instead. It's sorted by recently used so you can use it to quickly access recently accessed files or quickly fuzzy search.

**Comment by thomasschafer** [comment]
> In retrospect it would have been better to not merge the buffer-line because we don't want to support a vscode tablike workflow where the buffers are closed or reordered to make the bufferline tidy. Helix buffers are like vim and kakoune buffers and generally just data in the background and not something that should be visible or kept tidy. I would recommend just leaving buffer open and using the buffer pickr instead. It's sorted by recently used so you can use it to quickly access recently accessed files or quickly fuzzy search.

That makes sense, I will try that - thank you.

Given that bufferline support is available, and that some users will likely find it a useful to initially have a tab-like workflow (that's certainly been my experience moving from Neovim with [bufferline.nvim](https://github.com/akinsho/bufferline.nvim)), do you not think there's any value in slightly improving that workflow, e.g. I was thinking of trying to fix the issue with the bufferline overflowing - is there no point in me doing that as it won't get merged?

**Pull request closed without merging**
