### PR TITLE
Add prefix position to `hx` CLI file args

### PR DESCRIPTION
**Pull request by bheylin**
Resolves https://github.com/helix-editor/helix/issues/5437

A cursor position can now be specified using common prefix notation used by vim, nvim, kak, emacs and nano.

`hx +10 Cargo.toml`

This prefix notation also allows the user to set the cursor at the end of the file.

`hx +: Cargo.toml`

This allows `hx` to play nicely with other tools that want to open a file at a given position using prefix notation.

The existing postfix notation can still be used (`hx Cargo.toml:10`) but has been extended to support jumping to the end of a buffer.

`hx Cargo.toml:`

The prefix notation works for each file in the list.

`hx +10 Cargo.toml +20 README`

and can be intermixed with postfix notation.

`hx +10 Cargo.toml README:20`

Prefix notation also supports column indexing.

`hx +10:20 Cargo.toml`

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/pull/5603

**Comment by bheylin** [comment]
> Duplicate of #5603

I would highlight that this PR implements file positioning just like Kakoune's CLI 
so both positioning and the ability to jump to EOF.

**Comment by the-mikedavis** [comment]
This was partially superseded by https://github.com/helix-editor/helix/pull/8521

We wanted to support `+N` syntax only for tools like `less` that assume that editors support that syntax. Since we have that and the suffix way of specifying line/column (e.g. `file.txt:5:3`) I think we support enough ways to open lines/cols. I'm not sure what the use-case is for Kakoune's support of opening at the end with `:`. I think it would be ok to add that syntax (specifically `file.txt:`, not `+:`) in a separate PR but I will close this out because we want to keep the position handling relatively small/simple and supporting multiple `+N`s is not necessary

**Comment by bheylin** [comment]
@the-mikedavis All good Mike, as long as it works!

> I'm not sure what the use-case is for Kakoune's support of opening at the end with :.

I'm also not sure where that came from, I presumed it was some sort of standard across editors.

Anyways my need here was to integrate `helix` into `zellij` _with_ line number support and that's taken care of now.

**Pull request closed without merging**
