### PR TITLE
reset idle timeout when pushing a new compositor layer

### LINKED ISSUE #4956: No syntax highlighting in preview on global search
### Summary

The global search picker fails to show syntax highlighting when it's first shown. It works fine after navigating through the items.

### Reproduction Steps

 

I tried this:

1. Set up the file and open Helix:
    ```
    $ mkdir preview-bug && cd preview-bug
    $ printf "const a = 1;\nconst b = 2;\n" > test.ts
    $ hx -c /dev/null .
    ```
2. Quit the initial file picker: `<ESC>`
3. Do a global search: `<SPACE>/const<ENTER>`

I expected this to happen:

The file content on the preview is properly highlighted (after the idle timeout).

Instead, this happened:

The preview is not highlighted.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-12-01T16:00:47.682 helix_loader [DEBUG] Located configuration folders: []
2022-12-01T16:00:47.690 helix_view::clipboard [DEBUG] Using tmux to interact with the system clipboard
2022-12-01T16:00:47.691 globset [DEBUG] glob converted to regex: Glob { glob: "*.{zip,gz,bz2,zst,lzo,sz,tgz,tbz2,lz,lz4,lzma,lzo,z,Z,xz,7z,rar,cab}", re: "(?-u)^[^/]*\\.(cab|rar|7z|xz|Z|z|lzo|lzma|lz4|lz|tbz2|tgz|sz|lzo|zst|bz2|gz|zip)$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true }, tokens: Tokens([ZeroOrMore, Literal('.'), Alternates([Tokens([Literal('c'), Literal('a'), Literal('b')]), Tokens([Literal('r'), Literal('a'), Literal('r')]), Tokens([Literal('7'), Literal('z')]), Tokens([Literal('x'), Literal('z')]), Tokens([Literal('Z')]), Tokens([Literal('z')]), Tokens([Literal('l'), Literal('z'), Literal('o')]), Tokens([Literal('l'), Literal('z'), Literal('m'), Literal('a')]), Tokens([Literal('l'), Literal('z'), Literal('4')]), Tokens([Literal('l'), Literal('z')]), Tokens([Literal('t'), Literal('b'), Literal('z'), Literal('2')]), Tokens([Literal('t'), Literal('g'), Literal('z')]), Tokens([Literal('s'), Literal('z')]), Tokens([Literal('l'), Literal('z'), Literal('o')]), Tokens([Literal('z'), Literal('s'), Literal('t')]), Tokens([Literal('b'), Literal('z'), Literal('2')]), Tokens([Literal('g'), Literal('z')]), Tokens([Literal('z'), Literal('i'), Literal('p')])])]) }
2022-12-01T16:00:47.691 globset [DEBUG] built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
2022-12-01T16:00:47.691 helix_term::ui [DEBUG] file_picker init 633.02µs
2022-12-01T16:00:47.691 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
2022-12-01T16:00:47.691 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-12-01T16:00:47.691 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-12-01T16:00:47.691 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
2022-12-01T16:00:47.691 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:48.091 helix_term::application [DEBUG] received editor event: IdleTimer
2022-12-01T16:00:48.144 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:48.833 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:49.234 helix_term::application [DEBUG] received editor event: IdleTimer
2022-12-01T16:00:49.656 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:50.057 helix_term::application [DEBUG] received editor event: IdleTimer
2022-12-01T16:00:50.216 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:50.618 helix_term::application [DEBUG] received editor event: IdleTimer
2022-12-01T16:00:50.736 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:50.824 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:50.886 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:50.999 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:51.075 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:51.644 grep_regex::matcher [TRACE] final regex: "[Cc][Oo][Nn][Ssſ][Tt]"
2022-12-01T16:00:51.644 grep_searcher::searcher [TRACE] Some("/home/dev/repos/preview-bug/test.ts"): searching using generic reader
2022-12-01T16:00:51.644 grep_searcher::searcher [TRACE] generic reader: searching via roll buffer strategy
2022-12-01T16:00:51.644 grep_searcher::searcher::core [TRACE] searcher core: will use fast line searcher
2022-12-01T16:00:51.645 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:51.645 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:54.951 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:55.352 helix_term::application [DEBUG] received editor event: IdleTimer
2022-12-01T16:00:55.687 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:55.956 helix_term::commands::typed [DEBUG] quitting...
2022-12-01T16:00:55.956 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:56.088 helix_term::application [DEBUG] received editor event: IdleTimer
2022-12-01T16:00:56.111 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:56.198 helix_term::job [DEBUG] waiting on jobs...
2022-12-01T16:00:56.198 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-01T16:00:56.198 helix_term::job [DEBUG] waiting on jobs...
2022-12-01T16:00:56.199 mio::poll [TRACE] deregistering event source from poller
2022-12-01T16:00:56.199 mio::poll [TRACE] deregistering event source from poller
```

</details>

### Platform

Linux

### Terminal Emulator

tmux 3.3a

### Helix Version

22.08.1-526-g67415e09

### PR DESCRIPTION
**Pull request by pascalkuthe**
Fixes #4956

As suggested in https://github.com/helix-editor/helix/issues/4956#issuecomment-1335540871 the right fix is to
reset the idle timer when pushing new layers into the compositor.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
I see what you were saying in #5115 with the callsites all adding `editor` args and that being a bit noisy. I don't see a better way to give `Compositor::push` access to the idle timer though so I think this looks good 👍

**Review by the-mikedavis — APPROVED** [review]

**Review by Philipp-M — APPROVED** [review]
LGTM, fixes also when just opening the file-picker with a low idle-timeout (same issue as #4956)

**Comment by Philipp-M** [comment]
Is there anything blocking this? This seems relatively straight-forward.

**Comment by Philipp-M** [comment]
Well apart from the fact, being completely out of sync with master. I have decided against fixing merge/rebase conflicts and replay the changes (as it seemed simpler than fixing the conflicts) for my own fork.

Here's a version that is has no merge conflicts with master: 97f310a1eb19b6e0a4a2018124e8ecbbbf5917bf

**Comment by pascalkuthe** [comment]
I was waiting for a decision from @archseer whether he wants to go forward with this. If he approves of the general idea I would rebase. In the long term this is not really the fix I would want since I mostly want to rebase the kitchensinky idle timeout with a more granular event system

**Comment by Philipp-M** [comment]
Yeah absolutely agree with a finer-grained idle-timeout system, thought about that myself already.
But since this PR doesn't add up a lot of complexity and fixes an obvious bug, I think it makes sense to merge this in the mean time (can be refactored/rewritten later anyways).

**Comment by pascalkuthe** [comment]
I already have a working event system locally (just haven't go around to finishing it) so its not too far away :) 

I would be ok with rebasing and merging this it depends on what @archseer thinks

**Comment by the-mikedavis** [comment]
@pascalkuthe do we need this anymore now that we have #8021?

**Comment by pascalkuthe** [comment]
Flying this still needs so.e work to switch the picker away from the idle timeout but yeah let's close this. I don't think this is the right approach now thatwe have the Event system

**Pull request closed without merging**
