### PR TITLE
Add gruvbox-light theme

### PR DESCRIPTION
**Pull request by crodjer**
Similar to `gruvbox`, add the light version as well.

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Thanks. I think you might also want to add it to the wiki. https://github.com/helix-editor/helix/wiki/Themes

**Comment by archseer** [comment]
The theme is missing `markup.` scopes, can you add those as well?

**Comment by archseer** [comment]
They were a recent addition so they are missing from the dark theme too https://github.com/helix-editor/helix/blob/97e6f2a38f28bf0051b96fa6f0f5786746b83e74/theme.toml#L31-L36

It's used for styling markdown and will soon also be used for documentation popups

**Comment by crodjer** [comment]
@archseer Thanks for the suggestion, crated a PR: https://github.com/helix-editor/helix/pull/1518

**Pull request merged**
