### PR TITLE
remove build warnings

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by the-mikedavis** [comment]
What is emitting warnings for these lines?

**Comment by tshepang** [comment]
`cargo check`

**Comment by tshepang** [comment]
hm, I see it's not happening on Rust 1.70

**Comment by tshepang** [comment]
I did override the pinned toolchain (1.70) to nightly (1.76+), and that's how I got these warnings

**Review by the-mikedavis — APPROVED** [review]

**Pull request merged**
