### PR TITLE
add yd as alias for yank_diagnostic

### PR DESCRIPTION
**Pull request by darshanCommits**
adds an alias for the new command :yank_diagnostic as :yd.

### CODE REVIEW

**Review by pascalkuthe — COMMENTED** [review]
is this name standard somehow. thsi seems like a bit of an odd abbreviation. I see why you want an abbrevation just looking for any kind of precedant here. I dont love coming up with new aliases

**Comment by darshanCommits** [comment]
That I'm not sure about. I assumed that yank_diagnostic would have an alias of first char of each letter, just like all the common bc, bca, o, etc. 

One could have keybind it but that's another keybind consumed + the overhead of coming up with a reasonably intuitive keybind.

**Comment by pascalkuthe** [comment]
I like this as a typable command (altough you can add a keybinding to your ocndig if you want). I can't think of another alias either. What do you think @the-mikedavis?

**Comment by darshanCommits** [comment]
image

no other relevant cmd (yank/clipboard) has any alias and are all dependent upon keybind, mostly single keystroke. Unlike space,goto,view modes which have relevant commands in one place, it is not appropriate imo to put this in any of those modes.

**Comment by the-mikedavis** [comment]
This seems unnecessary to me. When you're running interactively you can use `:yd<tab><ret>` so that the tab expands the full command name

**Comment by darshanCommits** [comment]
Alright, I shall close this then.
Considering how useful this command is, I'd still like prefer it by default though.

**Pull request closed without merging**
