### PR TITLE
Add Pop-Dark Theme

### PR DESCRIPTION
**Pull request by workingJ**
This adds the Pop-Dark Theme https://github.com/workingJ/helix-pop-theme
I'll update the Wiki if it gets accepted.

Preview

btw. great editor!

### CODE REVIEW

**Comment by the-mikedavis** [comment]
#1802 just added a new scope `ui.virtual` for visible whitespace (they key might end up being used by #1796 too). In the existing themes I mostly used the same theming as what gets used for `comment` but you may want to tune this to something more faint. If you build from the latest source, `:set whitespace.render all` will enable visible whitespace temporarily so you can test it.

**Comment by the-mikedavis** [comment]
There's also `ui.virtual.ruler` from the recently merged #2060 and for that one you probably want `{ bg = "something_faint" }` (rather than the foreground being highlighted)

**Comment by the-mikedavis** [comment]
`ui.window` themes the split line between windows. To see it, try out `:vsplit` and make the foreground color something very noticeable

**Comment by workingJ** [comment]
@the-mikedavis thanks for your help.
now the theme is fixed and final, i am willing to maintain it.
The past few days i could not follow the project closely, so i don't know if there has some one volunteered to maintain themes over all. I can imagine to do that if you like.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
There isn't really an overall themes maintainer, I think the themes and scopes don't need that much upkeep work. If an issue pops up about a theme you wrote though there's a good chance you'll get CC'd so you can help decide the colors etc.

**Pull request merged**
