### PR TITLE
Allows open file at `+<line>:<column>` from the command line

### PR DESCRIPTION
**Pull request by Rational-Curiosity**
New command line parameter

```bash
hx +10:7 file.ext
hx +10 file.ext
```

### CODE REVIEW

**Comment by s1ck** [comment]
That's cool. I just opened https://github.com/helix-editor/helix/pull/1128 :)

**Comment by Curiosidad-Racional** [comment]
> That's cool. I just opened #1128 :)

Thanks, improving `helix`...

**Comment by sudormrfbin** [comment]
There's already #445 open which implements this in the format of `hx file.txt:line:col`.

**Comment by Curiosidad-Racional** [comment]
> There's already #445 open which implements this in the format of `hx file.txt:line:col`.

The `+line` is widely used, and many linux aplications assumes it. I would support both options but implementations are very different...

**Comment by pickfire** [comment]
> The +line is widely used, and many linux aplications assumes it. I would support both options but implementations are very different...

It's good to see this too, but I think it seemed limited to a single file.

**Comment by Curiosidad-Racional** [comment]
> > The +line is widely used, and many linux aplications assumes it. I would support both options but implementations are very different...
> 
> It's good to see this too, but I think it seemed limited to a single file.
> 
> I would like to see the other pull request I created merged first. Also, this pull request seemed to put the logic in a weird part, it should probably be in `editor.open`.

Of course, I'll pick up this issue after you finish. About the logic, I don't care where to put the code. The implementation has very few lines of code indicating how well it fits the solution to the problem.

**Comment by archseer** [comment]
With https://github.com/helix-editor/helix/pull/445 merged, feel free to reopen if you revisit this PR in the future

**Pull request closed without merging**
