### PR TITLE
Highlight sqlx's `query_scalar{,_unchecked}` macros as SQL

### PR DESCRIPTION
**Pull request by cole-h**
I noticed these two were missing, so I figured we should add them for completeness.

### CODE REVIEW

**Review by the-mikedavis — COMMENTED** [review]
I didn't notice the duplication before but I think we should collapse these patterns where "Only the first argument is SQL" into one pattern and change the `(#eq? @_query "query")` part to `(#match? @_query "^query(_as|_scalar|_scalar_unchecked)?$")` to match them all more concisely

**Comment by cole-h** [comment]
Sounds like a good idea.

However, my lisp skills are fairly low, and I don't currently have the time (or desire) to improve them to make that change. Would you be opposed to merging this as-is and then having someone file a follow-up PR that does improve this situation?

**Comment by archseer** [comment]
It seems more effort to open yet another PR than to just do the replacement @the-mikedavis gave you? Remove other queries, then replace `(#eq? @_query "query")` with `(#match? @_query "^query(_as|_scalar|_scalar_unchecked)?$")` should be possible to do without having to understand lisp :)

**Comment by cole-h** [comment]
Oh, sorry! That shows my lisp knowledge -- it sounded more involved than some simple replacements 😅 

I've hopefully addressed that in 041b116cab4030ce014773c51e457000185f544e.

**Review by the-mikedavis — APPROVED** [review]

**Pull request merged**
