### PR TITLE
set VERSION file to dev

### PR DESCRIPTION
**Pull request by the-mikedavis**
Forgot to follow up on this: the idea is that we set the VERSION file to include `-dev` after a release so it's easy to see when someone is building from source on a non-tagged version.

### CODE REVIEW

**Comment by kirawi** [comment]
Maybe a better solution would be using an environment var to check whether it's building in CI or not?

**Comment by the-mikedavis** [comment]
We could probably have the CI modify the VERSION file to remove the `-dev` suffix (so we'd still need to update the `VERSION` file before a release but not before _and_ after)

**Comment by archseer** [comment]
Should we bump this to `22.05-dev`?

**Comment by orhun** [comment]
Shouldn't this be set to e.g. `22.05` right before a new release? I've built `helix` from the last tagged release but `helix -V` shows `22.05-dev` 🤔

**Comment by archseer** [comment]
There's two ways: either bump right before a release, or do it right after. We tried doing it after a release so that builds from master have a different version from the latest stable release, but we forgot to remove the `-dev` suffix...

Will push a new `22.05` tag shortly!

**Comment by archseer** [comment]
New tag was pushed https://github.com/helix-editor/helix/releases/tag/22.05

**Pull request merged**
