### PR TITLE
Update gruvbox themes

### PR DESCRIPTION
**Pull request by 0rphee**
* stylize v2 picker column headers

Doing the same as #11459

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Are you running a Helix version behind the latest master? We changed the way these keys work in #11343 so this looks like



rather than what you posted in https://github.com/helix-editor/helix/pull/11459#issuecomment-2282268062

To make the header look like that column you can switch the key to be `"ui.picker.header.column"`.

You might also want to consider setting the active header (`"ui.picker.header.column.active"`) which indicates which column you're currently typing into. For example in my theme I have

```toml
"ui.picker.header.column" = { underline.style = "line" }
"ui.picker.header.column.active" = { fg = "fg0", modifiers = ["bold"], underline.style = "line" }
```

**Comment by 0rphee** [comment]
Hmm, I'm a little confused, because it looks like this to me:

Screenshot 2024-08-14 at 10 17 46 a m

This is after rebasing on the latest master...

**Comment by the-mikedavis** [comment]
What's your `hx --version` output and which terminal emulator are you using?

**Comment by 0rphee** [comment]
Oh, I'm so sorry, I forgot to actually use the newest version, and not just change the themes...

I was aiming at what you said in https://github.com/helix-editor/helix/pull/11477#issuecomment-2286179656. I've updated the changes to align with what you suggested. Thanks.

**Review by pascalkuthe — APPROVED** [review]

**Pull request merged**
