### PR TITLE
Add languages-open command

### PR DESCRIPTION
**Pull request by AceofSpades5757**
Solves #3206, which was opened by myself.

Adds `:languages-open` as a command.

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
> There are three possible `languages.toml` files. The first is compiled into

Which language file is opened?

**Comment by AceofSpades5757** [comment]
@AlexanderBrevig It opens the user `languages.toml` file, however, some good points were made in the referenced issue that makes me want to close this pull request.

**Comment by poliorcetics** [comment]
Maybe give a picker of active language files, in order from most specific to less specific ?

**Comment by AceofSpades5757** [comment]
@poliorcetics The same ideas are in the issue as well: #3206

I'm gonna close this pull request since its current implementation wouldn't add any benefit to Helix.

**Pull request closed without merging**
