### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by chunghha**
To fix the issue #2303, changed the followings. Please review.

- ~~rename overlayed() to overlaid()~~ _reverted_
- fix the typo in changelog
- fix typos in the comments
- fix the typo in book.js
- fix the typo in book/theme
- fix typos in book/src

### CODE REVIEW

**Comment by chunghha** [comment]
My local build with the changes is okay as the macOS build by CI.  Regarding the linux build failure, the comment changed from "mutiple" to "multiple" (counting of characters?) may cause the failure, but I am not sure what to fix. Please double check and let me know if I need to push something with this PR.

**Comment by archseer** [comment]
"overlayed" is a word. 

> simple past tense and past participle of [overlay](https://en.wiktionary.org/wiki/overlay#English)

**Comment by the-mikedavis** [comment]
To run all of the tests you'll need to use `cargo test --workspace` (`cargo test` doesn't run all of them). The failure I see:

```
failures:

---- syntax::test::test_textobject_queries stdout ----
thread 'syntax::test::test_textobject_queries' panicked at 'assertion failed: `(left == right)`
  left: `1..36`,
 right: `1..35`: @quantified_nodes expected 1..35', helix-core/src/syntax.rs:2000:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:154:5
   4: helix_core::syntax::test::test_textobject_queries::{{closure}}
             at ./src/syntax.rs:2000:13
   5: helix_core::syntax::test::test_textobject_queries
             at ./src/syntax.rs:2009:9
   6: helix_core::syntax::test::test_textobject_queries::{{closure}}
             at ./src/syntax.rs:1970:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    syntax::test::test_textobject_queries

test result: FAILED. 124 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s
```

**Review by the-mikedavis — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
