### PR TITLE
use `ui.menu` instead of `ui.statusline` for command completion menu theme

### PR DESCRIPTION
**Pull request by ChrHorn**
This should fix https://github.com/helix-editor/helix/issues/2379

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]
I tihnk this makes sense. On the one hand this component is sort-of attached to the statusline but it behaves the same as the auto-complete menu for example. What do others think?

**Comment by ChrHorn** [comment]
I would argue that the command completion menu serves the exact same purpose as the autocomplete menu. It also already uses `ui.menu.selected` for the highlighting. The statusline styling tends to be more muted in the background.

We could in theory create a seperate style for the command menu, but I don't think that it's really needed.

**Comment by archseer** [comment]
This is going to break all themes that don't have `ui.menu` defined (i.e. the default theme).

**Comment by ChrHorn** [comment]
You are correct. Think the default theme is the only theme that didn't define it. I kept the style for the default theme (statusline bg/fg) for the menu.

**Comment by ChrHorn** [comment]
Woops, seems I can't use regex correctly. There are some themes with missing `ui.menu`. Will add them tomorrow.

**Review by archseer — APPROVED** [review]

**Pull request merged**
