### PR TITLE
Format documentation for better diffing of #5534

### PR DESCRIPTION
**Pull request by David-Else**
This pull request simply formats all the current documentation using the same settings as https://github.com/helix-editor/helix/pull/5534 . There are absolutely no other changes applied.

I am waiting for a reply from @archseer https://github.com/helix-editor/helix/pull/5534#discussion_r1070638074 to confirm if he thinks doing this is the best solution to make reviewing easier by making the changes easier to see, but I put in this pull request in advance to save time if the idea is approved.

I have included the `.prettierrc` file for future reference.

@the-mikedavis I don't expect there to be any problems created by this for the mdBook generation, but maybe you could confirm that?

### CODE REVIEW

**Comment by thomkeh** [comment]
Don't you get the best diffs with [one sentence per line](https://nick.groenen.me/notes/one-sentence-per-line/)? (Or, more generally with “semantic line breaks”, so breaking at commas or colons or the start of a new clause.)

**Comment by David-Else** [comment]
It seems this fix might be preferable to GitHub prose diff mode.

**Comment by the-mikedavis** [comment]
The problem is with bundling content changes with auto-formatting changes - switching to different auto-formatting settings won't really make a difference.

I could go through the #5543 changes and rewrite them on master without the formatting changes and force-push that to your branch if you'd like. (This would be my way to work through and review the changes as well.)

**Comment by David-Else** [comment]
@the-mikedavis I am quite new to advanced Git and don't really understand what force pushing to my branch in GitHub would mean, would that result with a new commit from you appearing with your new version on my branch? If so, go for it!

You will have a fun job moving all the text back to the old non formatted version, a good test of your Helix keyboard skills :)

1. Do I need to do anything now (like merge in new changes from upstream master) or just wait to hear something from you over on https://github.com/helix-editor/helix/pull/5534 ?
2. Shall we get what I have done onto the master and then I make a new pull request for the other changes I detail in https://github.com/helix-editor/helix/pull/5534 ?

Cheers.

**Comment by the-mikedavis** [comment]
Yep it would just be rewritten commit(s) on your branch in that PR. You would still be the author on the commits too. I'll rebase the changes on master so no need to do anything to the branch. I'll try to take a look at this in the next few days.

> Shall we get what I have done onto the master and then I make a new pull request for the other changes I detail in #5534?

Yeah we can start with the changes in that branch and make improvements from there once it's merged

**Comment by pascalkuthe** [comment]
If I understood this comment https://github.com/helix-editor/helix/pull/5534#issuecomment-1407474833 right this PR can be closed now. Correct?

**Pull request closed without merging**
