### PR TITLE
Add support for Agda

### PR DESCRIPTION
**Pull request by omentic**
supersedes #3092 

todo:
- [x] try to get the updated tree-sitter code upstreamed (instead of relying on my fork)
  - https://github.com/tree-sitter/tree-sitter-agda/pull/19
- [x] make queries better
  - [ ] properly match functions
  - [x] more fine-grained matching of types, ex. `(expr (expr (expr... (atom) @type)))`
    - lost cause, see https://github.com/tree-sitter/tree-sitter/issues/880
- [ ] indentation queries?

### CODE REVIEW

**Comment by omentic** [comment]
Syntax highlighting just about working. Trying to get functions working, then I think this'll be ready to merge.

The language server does not appear to work at all, unfortunately. I might remove it or leave it in with a note.

image

**Comment by omentic** [comment]
This PR is ready for review. I may have a follow-up sometime adding proper function highlighting & als support, the former appears to be a legitimate upstream bug and the latter still a mystery. 

@the-mikedavis can you squash merge this or would you prefer me to rebase?

**Review by the-mikedavis — DISMISSED** [review]

**Comment by the-mikedavis** [comment]
We can squash + merge this, no need to rebase

**Review by the-mikedavis — DISMISSED** [review]

**Comment by Septias** [comment]
Is this stalling?

**Comment by omentic** [comment]
It's done on my end, I've been running it locally for a while. The syntax highlighting is unfortunately pretty terrible - but it's nothing that can be addressed until https://github.com/tree-sitter/tree-sitter/issues/880 is addressed. Any more specificity with regard to types kills performance exponentially (> 3 ish is unusable) and breaks highlighting for nested types above a certain level.

**Comment by Septias** [comment]
Do you use it regularly and would you advise others to do so aswell? @omentic

**Comment by omentic** [comment]
I mean, it's fine, it looks just like the above picture. I do not write Agda regularly in Helix and I would not advise others to do so as well because Helix lacks support for Unicode input, and Unicode input is required to write Agda.

When a snippets system lands, it'd be fine, I guess: but without a "proof assistant mode" or similar not great.

**Review by pascalkuthe — DISMISSED** [review]

**Comment by pascalkuthe** [comment]
This needs co flicts resolved before being g merged

**Review by the-mikedavis — APPROVED** [review]

**Comment by omentic** [comment]
(tangential re: a proof assistant mode: it's very likely it could piggyback off of debug mode, before or after a redesign. i've had no time to poke around and prototype something, unfortunately, but might in the far future...)

**Review by pascalkuthe — APPROVED** [review]

**Pull request merged**
