### PR TITLE
Add more coverage for CI

### PR DESCRIPTION
**Pull request by pickfire**
Runs every day as cron. Add matrix for test, includes windows and macos.

### CODE REVIEW

**Comment by archseer** [comment]
If the CI already runs on every PR and merge to master, do we really need a daily run?

I do agree that we should change the tests to run checks & lints on `ubuntu-latest` first, then run the tests in a cross platform matrix.

**Comment by pickfire** [comment]
> If the CI already runs on every PR and merge to master, do we really need a daily run?

Ripgrep does that and I think it's a good idea to run it every day in case something outside of our control breaks so we know it.

> I do agree that we should change the tests to run checks & lints on ubuntu-latest first, then run the tests in a cross platform matrix.

It's already running in ubuntu-latest, IIRC matrix runs in parallel which is very good, it should run ubuntu-latest first because I put it in the front.

**Comment by archseer** [comment]
Good point, I didn't see that the matrix was already limited to tests only.

**Comment by archseer** [comment]
Seems like there's some issues with the yml syntax: https://github.com/helix-editor/helix/actions/runs/911342759

**Pull request merged**
