### PR TITLE
Provide more details on runtime directory

### PR DESCRIPTION
**Pull request by aryzing**
Provides more details on what to do with the runtime directory.

### CODE REVIEW

**Comment by David-Else** [comment]
Thanks for the update, but I don't think:

> searched by 'hx'

is very clear or grammatically correct. How about something more like the following, maybe you could use some or all of it?


>Download the pre-built binaries from the [GitHub Releases page](https://github.com/helix-editor/helix/releases). The downloaded tarball includes an `hx` binary and a `runtime` directory. To set up Helix:

>1. Add the `hx` binary to your system's `$PATH` to allow it to be used from the command line.
>2. Copy the `runtime` directory to a location that `hx` searches for runtime files. A typical location on Linux/macOS is `~/.config/helix/runtime`.

>To see the runtime directories that `hx` searches, run `hx --health`. If necessary, you can override the default runtime location by setting the `HELIX_RUNTIME` environment variable.

**Comment by aryzing** [comment]
It's great, will use all of it

**Review by the-mikedavis — APPROVED** [review]

**Comment by aryzing** [comment]
@the-mikedavis still interested in merging this?

**Comment by the-mikedavis** [comment]
Yep I think it's a good change, we just need another reviewer to take a look

**Pull request merged**
