### PR TITLE
Fix: when goto normal mode, only want to remove indentation if the line is blank with no text following

### PR DESCRIPTION
**Pull request by WindSoilder**

### CODE REVIEW

**Review by dead10ck — APPROVED** [review]
This looks like it'll do the trick to me. As an aside, it may be worth adding unit tests to help with future maintenance and avoiding regressions.

**Comment by WindSoilder** [comment]
> This looks like it'll do the trick to me. As an aside, it may be worth adding unit tests to help with future maintenance and avoiding regressions.

I think it's integration test level? Currently I see no tests setup for `commands`

**Comment by dead10ck** [comment]
I meant unit style, but yeah, I recently noticed that there are no tests in commands. I haven't looked into how difficult it would be to set up a `Context` for tests.

**Comment by WindSoilder** [comment]
> you could always split out some of the logic into smaller more focused pieces that just take a Rope/Selection/etc as input to make it easier to test

It's a good idea.  I move the checking logic into `inserted_a_new_blank_line` function.

**Pull request merged**
