### PR TITLE
adds: base16 default dark theme for Helix editor

### PR DESCRIPTION
**Pull request by raygervais**
Theme sample: 

_Go_
Screen Shot 2021-10-12 at 9 11 29 PM

_Rust_
Screen Shot 2021-10-12 at 9 12 01 PM

### CODE REVIEW

**Comment by kirawi** [comment]
You can have a `[palette]` section as well so you don't have to copy-paste the same hex values over and over again.

**Comment by raygervais** [comment]
Corrected, thanks @Omnikar. 

Will update your tip @kirawi, thanks for suggestion. 

Any suggestions about determine the env and switching to this theme if appropriate?

**Comment by archseer** [comment]
A Base16 "true color" theme isn't quite the same as a 16 color theme that uses the terminal's default color scheme. So this won't close #791, but it's still appreciated :)

**Comment by archseer** [comment]
Which of the base16 themes is this by the way?

**Comment by archseer** [comment]
To use the terminal palette you specifically need to use `black`, `red`, `light-red`, etc. `"#181818"` is a hex color and requires true color support from the terminal.

**Comment by raygervais** [comment]
Default dark @archseer, and thanks for the explanation, will add to this existing PR the same which leverages exactly as you described and do my own research too. 

For reference relating to the theme, http://chriskempson.com/projects/base16/

**Comment by Omnikar** [comment]
> We might want a 256 color theme to be the fallback, the colors there are more standardized and most terminals support 256 colors.

Ah, right.

**Comment by raygervais** [comment]
Update, going to look more into this and produce a proper theme which closes #791. Updating the Base 16 default dark theme here based on recommendations in case you want another color theme :D

**Comment by raygervais** [comment]
Just rebased from master, somehow it included other commits that shouldn't be there, so I can clean that up.

**Comment by archseer** [comment]
Is this label enough or do you need it marked as `hacktoberfest-accepted`?

**Pull request merged**
