### PR TITLE
Theme: port of Zed's OneDark and OneLight themes

### PR DESCRIPTION
**Pull request by EricHenry**
I am a big fan of Zed's `OneDark` theme variation so I ported it over to helix. Here are some screen shot comparisons.

Zed
Screenshot 2023-06-06 at 10 32 46 PM

Helix:
Screenshot 2023-06-06 at 10 33 29 PM

edit: updated screenshots

### CODE REVIEW

**Comment by archseer** [comment]
How different is it from the regular one?

**Comment by EricHenry** [comment]
The color pallet and the colors used for tree sitter scopes are different. I think the only colors that are the same is the background and color used for comments.

Here are some screenshots of the current OneDark theme for reference.

OneDark of same code as above:

Screenshot 2023-06-06 at 8 47 36 AM
----------------------------------------------
### New code screen shots

One Dark:
Screenshot 2023-06-06 at 8 50 19 AM

Zed One Dark:
Screenshot 2023-06-06 at 8 50 40 AM

**Review by the-mikedavis — COMMENTED** [review]
It looks like light and dark are virtually the same except for the colors. Could they be refactored into one theme where the other inherits it (https://docs.helix-editor.com/master/themes.html#inheritance) and changes the palette? For example see the gruvbox themes

**Comment by EricHenry** [comment]
@the-mikedavis great idea! I'll refactor it, there is quite a bit of of overlap between the two.

**Comment by EricHenry** [comment]
thanks for the suggestion @the-mikedavis , this cleaned up the light theme a lot.

**Review by the-mikedavis — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Comment by gavlig** [comment]
I'm sorry for writing in a closed PR, but @EricHenry I need to know what is that beautiful font you're using (probably in all screenshots, but I like how it looks the most in the first post)

**Comment by EricHenry** [comment]
@gavlig hey I totally get it. Haha I like beautiful fonts myself. 

There are 2 fonts in the first post. The one marked Zed is from the zed editor. They built their own font (that I’m a big fan of too) called Zed Mono and Zed Sans. You can find them here: https://github.com/zed-industries/zed-fonts

The other screenshot marked helix is my other favorite font and daily driver. Cascading Code. Also free: https://github.com/microsoft/cascadia-code

**Comment by gavlig** [comment]
Thank you, much appreciated!

**Pull request merged**
