### PR TITLE
fix termcode yank/paste

### PR DESCRIPTION
**Pull request by rcgoodfellow**
#10839 broke the termcode clipboard implementation.

Previously termcode relied on the stateful `FallbackProvider` implementation of the `ClipboardProvider` trait to capture buffer data for yank/paste. Now that `FallbackProvider` is gone and `ClipboardProvider` is a stateless enum, yank/paste fails to function.

This PR re-introduces some of the `FallbackProvider` machinery in a new `TermcodeProvider` structure within the `ClipboardProvider::Termcode` enum. This allows yank/paste to work again. Because the overarching context in which clipboard providers now run is from a `DynAccess` type direct mutation is not possible, so I've put the mutable bits in a mutex (required instead of a RefCell as this code path is called from a threaded context).

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Can you describe the issue with the termcode provider after #10839? The refactor in #10839 eliminated statefulness from the providers themselves since the `Registers` type already stores yanks and we shouldn't be reintroducing that statefulness.

**Comment by the-mikedavis** [comment]
Ah actually I see the problem. #10839 introduced an error enum with a `ReadingNotSupported` variant for providers like termcode that can't read. We just need to handle that in `read_from_clipboard` and use the saved values instead.

**Comment by the-mikedavis** [comment]
I pushed a change to cover that case - could you rebuild master and give the termcode provider another try?

**Comment by rcgoodfellow** [comment]
Yup - that fixed it. Thanks!

**Pull request closed without merging**
