### PR TITLE
changed flag in build_cpp '/std:c++14' to '/std:c++17' due to tree_si…

### PR DESCRIPTION
**Pull request by janhrastnik**
…tter_haskell not compiling on msvc without it

### CODE REVIEW

**Comment by janhrastnik** [comment]
this should fix #117

**Comment by kirawi** [comment]
c++14 works as well after it was fixed in the haskell repo.

**Comment by janhrastnik** [comment]
Hmm, you're right. I thought it didn't work for me when I first tried it. Should we change this to c++14 then?

**Comment by kirawi** [comment]
Maybe, just to be safe?

**Pull request merged**
