### PR TITLE
Add insert_space command

### PR DESCRIPTION
**Pull request by yerlaser**
Add command to insert whitespace.
Motivation: I would like to add a special binding in normal mode to Shift-Space shortcut.
However, in insert mode it is very easy to hit this combination by accident as Shift often remains depressed after a previous character was inserted.
Therefore, I would like to assign Shift-Space to insert space, just like Space does, but only in insert mode.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/2116

**Comment by yerlaser** [comment]
> See #2116

Thanks, that's another use case that I didn't think of.
In general, though, this command can have a few other uses.

In that other PR you refer to the Macro Style Bindings, but that feature seems to be stalled since 2021.
May I suggest to have this now and once that arrives all three _insert_ commands can be replaced by one.

**Comment by tmke8** [comment]
This could also be generalized to an `:insert-text` typeable command, and then you'd use

```toml
"S-ret" = ":insert-text ' '"
```

There is an open issue for that: #2797

**Comment by yerlaser** [comment]
OK. I see.

**Pull request closed without merging**
