### PR TITLE
chore(theme): update markup styles for rose_pine themes

### PR DESCRIPTION
**Pull request by chunghha**
Update rose_pine themes per #1618

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Thanks.

**Comment by archseer** [comment]
Is this based on any upstream Rose Pine themes? I can't find heading styles for it anywhere

**Comment by archseer** [comment]
Neovim theme uses different scopes for example https://github.com/rose-pine/neovim/blob/3de9dadb96c71e7c020b6cc320fc1f6d6f2fdd4c/lua/rose-pine/init.lua#L126-L133

**Comment by chunghha** [comment]
I use the colors defined in the upstream's palette but applying the colors for the themes is my own selection. I don't mind these themes updated as (or if) this project likes to keep same as nvim's.

**Pull request merged**
