### PR TITLE
feat(languages): SQL

### PR DESCRIPTION
**Pull request by jaredramirez**
Finally got around to adding sql language support. The original PR is here: https://github.com/helix-editor/helix/pull/1464, but enough has changed since then (no submodules!) that I decided to just create a new branch & PR. 

Only thing I'm not sure of is why when I built with nix, `flake.lock` changed so much.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Oh hmm the flake lock change might be from an old nix version I would guess. Which version of the nix binary are you running?

**Comment by jaredramirez** [comment]
I'm on `nix (Nix) 2.6.0pre20211217_6e6e998`

**Comment by the-mikedavis** [comment]
I think it might be that the flake follows change (https://github.com/NixOS/nix/pull/6036) that showed up in 2.7.0 makes it so the lock is generated differently than older nix versions. The current flake is generated with 2.7.0. In any case, would you mind dropping it out of this PR since it's unrelated to the SQL change? We can merge it in later if it's reproducible on 2.7.0. I'll clear my store and try again in a bit to see if I can't reproduce it because of what I have cached locally.

**Comment by jaredramirez** [comment]
Done!

**Review by the-mikedavis — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
