### PR TITLE
feat(editor): Allow Ctrl-[ to function as Escape

### PR DESCRIPTION
**Pull request by harritaylor**
Issue:  https://github.com/helix-editor/helix/issues/6551

### CODE REVIEW

**Comment by pascalkuthe** [comment]
Its on purpose that these do not always act the same and sglukd be covered by keymaps not by patching krycodes: https://github.com/helix-editor/helix/issues/6551#issuecomment-1493359754

**Comment by harritaylor** [comment]
@pascalkuthe Sure, I understand - thanks for the reply. What is the recommended approach for "C-[ behaves like Esc" in this case? It is a core part of my muscle memory for terminal applications ([and I'm assuming it is for a few others too](https://github.com/helix-editor/helix/issues/6551#issuecomment-1502574646)).

I tried remapping in configs but there are still instances in `hx` where the `C-[` key is sent instead and I would prefer that particular key combo to always "do what I mean". I have seen https://github.com/helix-editor/helix/issues/5505 which I would be happy to play around with a solution for. I have also seen https://github.com/helix-editor/helix/pull/7020 but I agree with the author that opting out of kitty protocol support should probably not be the way to go.

**Comment by pascalkuthe** [comment]
Solving https://github.com/helix-editor/helix/issues/5505 is the way to fix that issue but that will take quite a while and should probably be done by a maintainer/in close coordination with a maintainer. Such fundamental large changes are hard to coordinate otherwise

**Comment by harritaylor** [comment]
@pascalkuthe Sure. Either way I'd like to contribute - anything tangentially related I can work on as a "good first issue"?

**Comment by pascalkuthe** [comment]
The following could be good things to work on:

* https://github.com/helix-editor/helix/issues/4274: prior work in https://github.com/helix-editor/helix/pull/5435, the author didn't have time to finish, you can use that PR as a starting point and address the remaining review comments. Past  review comments can also teach you more about the codebase)
* https://github.com/helix-editor/helix/issues/4153: add a variant of `:sort` that sorts numerically instead of lexigrahically (so `10` is sorted after `5` for example). Should be easy to just add an additional `numeric: bool` arg to `sort_impl` and add a `:sort-numeric` command that sets that arg to true. When that option is set simply sort with https://crates.io/crates/alphanumeric-sort
* https://github.com/helix-editor/helix/issues/6752#issuecomment-1608816732: a crash that is a bit more challenging to fix but would provide good onsight into the codebase. I left instructions in the comment.

**Comment by harritaylor** [comment]
@pascalkuthe great, thanks!

**Pull request closed without merging**
