### PR TITLE
helix-term: allow to backspace out-of the command prompt

### PR DESCRIPTION
**Pull request by markus-oberhumer-forks**
This makes helix behave like vim and kakoune.

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]
I forgot Kakoune had this behavior. Thanks!

**Review by archseer — APPROVED** [review]

**Comment by woojiq** [comment]
Perhaps it would be better to enter a config option for this? Many people are used to "old" behavior. I can't rename symbol because I always hold backspace😓

**Comment by the-mikedavis** [comment]
It also tripped up my muscle memory for a while but for prompts like rename you can use `C-w` to delete the current line rather than trying to backspace precisely

**Comment by archseer** [comment]
Hmm I also preferred the original behaviour since it seemed less surprising and it's really annoying when the prompt suddently closes when you backspace too far. I wasn't too opinonated though. If there's a clear preference I wouldn't be opposed to changing back

**Comment by the-mikedavis** [comment]
I'm not strongly opinionated on this either but I agree that the old behavior was less surprising. I think it would be fine to break with Vim and Kakoune here as @mo8it says we already have other ways of aborting. I definitely don't want inconsistency among the prompts though or a config option for a small behavior this.

**Pull request merged**
