### PR TITLE
Add ability to load files in the background without closing the picker

### LINKED ISSUE #3924: S-return in file picker should open file in the background and keep the picker open with the same search query
A lot of the time I want to open multiple files at once from the file picker and I think this small qol feature could make it easier to do so.

I would like to help write a PR to close this issue myself. Could anyone direct me as to where I should be looking to see how to make this work?

### PR DESCRIPTION
**Pull request by Itay123TheKing**
Closes #3924. This is a pretty small change but everyone has to start somewhere :P

### CODE REVIEW

**Review by the-mikedavis — APPROVED** [review]
I'm a fan of this - I run into this situation a lot too where you want to open a file and keep the picker open (usually to change query) but want to open the file, as a more convenient way than `<space>'`

**Review by dead10ck — APPROVED** [review]
Thanks!

**Comment by lukepighetti** [comment]
What's stopping this from merging?

**Comment by dead10ck** [comment]
A review from @archseer.

**Pull request merged**
