### PR TITLE
Fix: Panic when using multi layer key mapping

### PR DESCRIPTION
**Pull request by Nehliin**
I was playing around with the helix editor and put the following in my `config.toml`:

```toml
[keys.normal]
"space" = { "." = "hover", "s" = { "v" = "vsplit" , "h" = "hsplit"}}
```
Which caused a panic when pressing `space + s` . This happend because it was trying to sort the infobox body but the `self.order` list was empty. Changing from a `unwrap` to `unwrap_or(0)` makes the sorting not panic even if the `self.order` list is empty and fixed the bug for me. The mapping worked as expected after the fix. 

I also moved the unit test to its own module to prevent the test function from being compiled when not testing.

### CODE REVIEW

**Comment by archseer** [comment]
@sudormrfbin I wonder if we should specify an order here?

**Comment by Nehliin** [comment]
@archseer there is a comment on line 137 that the current order is random for the `keys` vec used in the sort. But even if there was a defined order it wouldn't help since `self.order` is empty unless I'm missing something?

**Comment by sudormrfbin** [comment]
I think the root of the problem occurs the default keymap is merged with the user keymap:

https://github.com/helix-editor/helix/blob/ac5449a32bf431fdda362df3c30ebbf79addb627/helix-term/src/keymap.rs#L111-L127

I didn't get time to investigate properly, but I guess it originates from here.

**Comment by archseer** [comment]
> since `self.order` is empty

It shouldn't be empty, an order vec should be generated during/after parsing so that the infobox has a consistent sort order. I think the code for this is probably missing when parsing the user config.

**Comment by Nehliin** [comment]
@archseer @sudormrfbin the problem seems to be that the order wasn't set recursively when merging. You were right that it was indeed never set when parsing the user config. When the order was set during merge child nodes weren't taken into account. 

I also added a test for it and remove the previous fix.

**Comment by Nehliin** [comment]
@sudormrfbin I agree with your solution. I didn't think about custom `Deserialize `impl.  It works for me without crashes so I'm happy with the it and can change this pr if you'd like. But perhaps you want to figure out the crash first?

**Comment by sudormrfbin** [comment]
The backtrace says ```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-term/src/keymap.rs:147:59```, so it's pretty much the original error. It happens when I press space quickly (as soon as helix starts), but even then I cannot reproduce it reliably:

helix-config-key-serde-bug

(It starts fine the first time but crashes the second time, with space being pressed started in both instances).

**Pull request merged**
