### PR TITLE
Command `new` open named buffer

### PR DESCRIPTION
**Pull request by sillent**
Hello

Refactor the `new` command, now it open a named buffer  that passed as arg
For resolving #5867

### CODE REVIEW

**Comment by the-mikedavis** [comment]
I would prefer the other idea from #5867:

> provide an error message if parameters are passed [to `:new`]

I don't like having `:new` and `:open` overlap so much in functionality.

**Comment by sillent** [comment]
> I don't like having :new and :open overlap so much in functionality.

Why? If we look on the VIM, there :new can take additional argument, or :edit that take required argument, and they both open the new named buffer.

I think it's very comfortable

For quick save you can just tap :w - and work is saved, your mind is clean, no needs to write additional arguments for :w

**Comment by pascalkuthe** [comment]
I think merging both commands and just making `:open` do the same and just making `:new` an alias for `:open` would be the nicest option (that was one of the options in https://github.com/helix-editor/helix/issues/5867) not sure if that is what you meant too @the-mikedavis

**Comment by the-mikedavis** [comment]
`:new` should always open a fresh scratch document, so if we allow an argument passed to `:new` I think it should open an empty document even if the file exists, and it should return an error if the path passed is an existing directory. I don't want `:new` and `:open` to be essentially the same command.

My preference though would be to just to add a line to `new_file`:

```rust
ensure!(args.len() == 0, "Expected no arguments");
```

**Comment by pascalkuthe** [comment]
> `:new` should always open a fresh scratch document, so if we allow an argument passed to `:new` I think it should open an empty document even if the file exists, and it should return an error if the path passed is an existing directory. I don't want `:new` and `:open` to be essentially the same command.
> 
> My preference though would be to just to add a line to `new_file`:
> 
> ```rust
> ensure!(args.len() == 0, "Expected no arguments");
> ```

Ah I see where you are coming from `:new` opening an existing file feels odd so these should probably be kept seperate. I didn't quite think that trough. If we would allow `:new` to accept a path then (which would create a scratch buffer or an error if the file exists) then to be consistent we should make `:open` also an error if the file doesn't exist yet.

This doesn't really feel that great to me though since `:open foo.rs` is usually not taught of as a scratch buffer but rather an on-disk file that just happens to be empty (and is treated that way by LSP integration and so on). The scratch buffer by comparison really is special and is not an on-disk file so `: new` not accepting any arguments also makes the most sense to me and keeps the current behaviour (just with the explicit check) :+1:

**Comment by sillent** [comment]
So, it turns out these changes are not needed? 

Close the PR?

**Comment by the-mikedavis** [comment]
I won't approve the current changes but I would be interested in the [other approaches](https://github.com/helix-editor/helix/pull/6668#issuecomment-1509249878) (especially the `ensure!` since the change would be so small), either in this PR or a new one

**Comment by sillent** [comment]
Ok, I'm closing the PR because these changes should have changed the logic :new

**Pull request closed without merging**
