### PR TITLE
Add spacebones light theme

### PR DESCRIPTION
**Pull request by atog**
This adds a new light theme: spacebones.

CleanShot 2021-11-19 at 14 54 33@2x

### CODE REVIEW

**Comment by sudormrfbin** [comment]
The background for the error dot looks out of place ? The theme itself looks quite pretty btw :)

**Comment by atog** [comment]
Yes, you are right. Fixed!

CleanShot 2021-11-19 at 17 24 22@2x

**Review by sudormrfbin — APPROVED** [review]
Thanks ! Could you also add it to the [wiki](https://github.com/helix-editor/helix/wiki/Themes) ?

**Comment by atog** [comment]
Done!

**Pull request merged**
