### PR TITLE
File keymap yank file name

### LINKED ISSUE #2985: Add a command to copy the filename and cursor line number in the clipboard.
I am not sure If we already have something like that or not.
I like to have a command that will copy the file path from the workspace("`workspace/dir1/dir/2/file.rs:567`") so we can share it with other team members and they can open it like  `hx  workspace/dir1/dir/2/file.rs:567`

Is it too much to ask in the same request to add this feature in the file finder too where we can add the line number after file with `: `?

### PR DESCRIPTION
**Pull request by QiBaobin**
Fixes #2985

### CODE REVIEW

**Comment by sudormrfbin** [comment]
Going the special register route and storing the filename on the `%` register like vim and kakoune might be better here since registers can be used in prompt areas like the command line and picker directly.

**Comment by sudormrfbin** [comment]
Ah I didn't see #3008. If it adds `%` as the filename register, I don't think we need a separate keybind for copying filenames since it can be done with `"%y` or `"%<space>y"`.

**Comment by QiBaobin** [comment]
> 



> Ah I didn't see #3008. If it adds `%` as the filename register, I don't think we need a separate keybind for copying filenames since it can be done with `"%y` or `"%<space>y"`.

Does `"%y` or `"%<space>y"` copy the selection to the register instead of copying from it?

**Comment by sudormrfbin** [comment]
Nope, `y` always copies from the register, and `"%` selects the register to copy from.

**Comment by QiBaobin** [comment]
> Nope, `y` always copies from the register, and `"%` selects the register to copy from. Since the `%` register would hold the name of the file, `"%y` would copy the the filename into the default register and `"%<space>y` would copy the filename to the system clipboard.

This is not what I understand, I think `"%y` mean copy the selection to register %, this is constant with the behavior as below:

https://user-images.githubusercontent.com/7072/179348195-337d2ba7-b27f-49b0-a4d5-14f1ed23842a.mov

To copy content from a register to another, I think we need paste from it and select it then copy to another. Let me know if I miss some features here.

**Comment by sudormrfbin** [comment]
Ah you're right, I mixed up `y` and `ctrl-r` in insert mode, sorry for the confusion 😅. In that case I think it's better to have a typable `:command` instead of a keybind for copying the filename to the system clilpboard.

**Comment by QiBaobin** [comment]
> You're right, I mixed up `y` and `ctrl-r` in insert mode, sorry for the confusion 😅. In that case I think it's better to have a typable `:command` instead of a keybind for copying the filename to the system clilpboard. I don't think it's a frequent enough thing to do that would require a default keybind, but if required it can be easily binded in the config file.

Sure

**Pull request closed without merging**
