### PR TITLE
Implement buffer ordering

### LINKED ISSUE #3707: Buffer reordering
With the new bufferline feature introduced by #2759, the order of buffers becomes much more apparent and important. As a result, I feel it necessary to have commands that can be used to reorder buffers. Unfortunately, it would appear that the data structure currently used to store buffers, `BTreeMap`, does not allow its data to be in an arbitrary order.

### PR DESCRIPTION
**Pull request by masonj5n**
Closes #3707

This is WIP, but I figured I'd put it up to start gathering some feedback.

This PR implements buffer reordering, currently only supporting incrementing and decrementing the ordering of the current buffer. 

It adds a new `document_ordering` field to the `Editor` which must be kept in-sync with the actual documents in the editor (I'd be surprised if what I have currently doesn't contain any bugs that let the documents and document ordering go out-of-sync, I tried to find all the places where docs are actually added and removed) and uses the document ordering to power the way the bufferline is drawn as well as how the `goto_next_buffer` and `goto_previous_buffer` commands work.

If we're okay with the general approach I'm curious if we should add ordering to the bufferline picker or expose in some other way what the actual current ordering is, since it's no longer solely based on the document ID.

https://github.com/helix-editor/helix/assets/25966620/74953da9-c239-400f-ad9b-0b9b213f9d26

### CODE REVIEW

**Comment by pascalkuthe** [comment]
Thank you for contributing .

I don't think this is something we will windup merging. I think bufferline and gn/gp encouraged a more gui/mouse driven tab like workflow which motivated this featured. But with helix we would like to remain focused on buffer picker / recently used style ordering. 


We already have automatically recently used ordering in the buffer picker and we would like to keep that. If anyrhing we should sort the bufferline the same as the buffer picker (altough there are some performance blockers for that right now).

**Comment by DoctorRyner** [comment]
> I think bufferline and gn/gp encouraged a more gui/mouse driven tab like workflow which motivated this featured

It is not, I have zero usages for mouse in helix but tabs are a faster way than space-b. How is it connected to mouse?

**Comment by adamcavendish** [comment]
> > I think bufferline and gn/gp encouraged a more gui/mouse driven tab like workflow which motivated this featured
> 
> It is not, I have zero usages for mouse in helix but tabs are a faster way than space-b. How is it connected to mouse?

I have similar usages too. I use next/previous buffer a lot to quickly switch between buffers. It's much faster than buffer picker (space-b) and I personally think reordering is a useful feature.

**Comment by DoctorRyner** [comment]
Yup, we don’t ask for drag&drop with mouse

**Pull request closed without merging**
